// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: events/historical_event_events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalEventCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Thumbnail     *string                `protobuf:"bytes,4,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`
	FromDateType  string                 `protobuf:"bytes,5,opt,name=from_date_type,json=fromDateType,proto3" json:"from_date_type,omitempty"`
	FromDay       *int32                 `protobuf:"varint,6,opt,name=from_day,json=fromDay,proto3,oneof" json:"from_day,omitempty"`
	FromMonth     *int32                 `protobuf:"varint,7,opt,name=from_month,json=fromMonth,proto3,oneof" json:"from_month,omitempty"`
	FromYear      int32                  `protobuf:"varint,8,opt,name=from_year,json=fromYear,proto3" json:"from_year,omitempty"`
	ToDateType    *string                `protobuf:"bytes,9,opt,name=to_date_type,json=toDateType,proto3,oneof" json:"to_date_type,omitempty"`
	ToDay         *int32                 `protobuf:"varint,10,opt,name=to_day,json=toDay,proto3,oneof" json:"to_day,omitempty"`
	ToMonth       *int32                 `protobuf:"varint,11,opt,name=to_month,json=toMonth,proto3,oneof" json:"to_month,omitempty"`
	ToYear        *int32                 `protobuf:"varint,12,opt,name=to_year,json=toYear,proto3,oneof" json:"to_year,omitempty"`
	Content       string                 `protobuf:"bytes,13,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalEventCreatedEvent) Reset() {
	*x = HistoricalEventCreatedEvent{}
	mi := &file_events_historical_event_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalEventCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalEventCreatedEvent) ProtoMessage() {}

func (x *HistoricalEventCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_historical_event_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalEventCreatedEvent.ProtoReflect.Descriptor instead.
func (*HistoricalEventCreatedEvent) Descriptor() ([]byte, []int) {
	return file_events_historical_event_events_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalEventCreatedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoricalEventCreatedEvent) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *HistoricalEventCreatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HistoricalEventCreatedEvent) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

func (x *HistoricalEventCreatedEvent) GetFromDateType() string {
	if x != nil {
		return x.FromDateType
	}
	return ""
}

func (x *HistoricalEventCreatedEvent) GetFromDay() int32 {
	if x != nil && x.FromDay != nil {
		return *x.FromDay
	}
	return 0
}

func (x *HistoricalEventCreatedEvent) GetFromMonth() int32 {
	if x != nil && x.FromMonth != nil {
		return *x.FromMonth
	}
	return 0
}

func (x *HistoricalEventCreatedEvent) GetFromYear() int32 {
	if x != nil {
		return x.FromYear
	}
	return 0
}

func (x *HistoricalEventCreatedEvent) GetToDateType() string {
	if x != nil && x.ToDateType != nil {
		return *x.ToDateType
	}
	return ""
}

func (x *HistoricalEventCreatedEvent) GetToDay() int32 {
	if x != nil && x.ToDay != nil {
		return *x.ToDay
	}
	return 0
}

func (x *HistoricalEventCreatedEvent) GetToMonth() int32 {
	if x != nil && x.ToMonth != nil {
		return *x.ToMonth
	}
	return 0
}

func (x *HistoricalEventCreatedEvent) GetToYear() int32 {
	if x != nil && x.ToYear != nil {
		return *x.ToYear
	}
	return 0
}

func (x *HistoricalEventCreatedEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HistoricalEventCreatedEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HistoricalEventCreatedEvent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type HistoricalEventUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Thumbnail     *string                `protobuf:"bytes,3,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`
	FromDateType  *string                `protobuf:"bytes,4,opt,name=from_date_type,json=fromDateType,proto3,oneof" json:"from_date_type,omitempty"`
	FromDay       *int32                 `protobuf:"varint,5,opt,name=from_day,json=fromDay,proto3,oneof" json:"from_day,omitempty"`
	FromMonth     *int32                 `protobuf:"varint,6,opt,name=from_month,json=fromMonth,proto3,oneof" json:"from_month,omitempty"`
	FromYear      *int32                 `protobuf:"varint,7,opt,name=from_year,json=fromYear,proto3,oneof" json:"from_year,omitempty"`
	ToDateType    *string                `protobuf:"bytes,8,opt,name=to_date_type,json=toDateType,proto3,oneof" json:"to_date_type,omitempty"`
	ToDay         *int32                 `protobuf:"varint,9,opt,name=to_day,json=toDay,proto3,oneof" json:"to_day,omitempty"`
	ToMonth       *int32                 `protobuf:"varint,10,opt,name=to_month,json=toMonth,proto3,oneof" json:"to_month,omitempty"`
	ToYear        *int32                 `protobuf:"varint,11,opt,name=to_year,json=toYear,proto3,oneof" json:"to_year,omitempty"`
	Content       *string                `protobuf:"bytes,12,opt,name=content,proto3,oneof" json:"content,omitempty"`
	UpdatedAt     *string                `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalEventUpdatedEvent) Reset() {
	*x = HistoricalEventUpdatedEvent{}
	mi := &file_events_historical_event_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalEventUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalEventUpdatedEvent) ProtoMessage() {}

func (x *HistoricalEventUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_historical_event_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalEventUpdatedEvent.ProtoReflect.Descriptor instead.
func (*HistoricalEventUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_events_historical_event_events_proto_rawDescGZIP(), []int{1}
}

func (x *HistoricalEventUpdatedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoricalEventUpdatedEvent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *HistoricalEventUpdatedEvent) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

func (x *HistoricalEventUpdatedEvent) GetFromDateType() string {
	if x != nil && x.FromDateType != nil {
		return *x.FromDateType
	}
	return ""
}

func (x *HistoricalEventUpdatedEvent) GetFromDay() int32 {
	if x != nil && x.FromDay != nil {
		return *x.FromDay
	}
	return 0
}

func (x *HistoricalEventUpdatedEvent) GetFromMonth() int32 {
	if x != nil && x.FromMonth != nil {
		return *x.FromMonth
	}
	return 0
}

func (x *HistoricalEventUpdatedEvent) GetFromYear() int32 {
	if x != nil && x.FromYear != nil {
		return *x.FromYear
	}
	return 0
}

func (x *HistoricalEventUpdatedEvent) GetToDateType() string {
	if x != nil && x.ToDateType != nil {
		return *x.ToDateType
	}
	return ""
}

func (x *HistoricalEventUpdatedEvent) GetToDay() int32 {
	if x != nil && x.ToDay != nil {
		return *x.ToDay
	}
	return 0
}

func (x *HistoricalEventUpdatedEvent) GetToMonth() int32 {
	if x != nil && x.ToMonth != nil {
		return *x.ToMonth
	}
	return 0
}

func (x *HistoricalEventUpdatedEvent) GetToYear() int32 {
	if x != nil && x.ToYear != nil {
		return *x.ToYear
	}
	return 0
}

func (x *HistoricalEventUpdatedEvent) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *HistoricalEventUpdatedEvent) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

type HistoricalEventDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalEventDeletedEvent) Reset() {
	*x = HistoricalEventDeletedEvent{}
	mi := &file_events_historical_event_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalEventDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalEventDeletedEvent) ProtoMessage() {}

func (x *HistoricalEventDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_historical_event_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalEventDeletedEvent.ProtoReflect.Descriptor instead.
func (*HistoricalEventDeletedEvent) Descriptor() ([]byte, []int) {
	return file_events_historical_event_events_proto_rawDescGZIP(), []int{2}
}

func (x *HistoricalEventDeletedEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoricalEventDeletedEvent) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

var File_events_historical_event_events_proto protoreflect.FileDescriptor

const file_events_historical_event_events_proto_rawDesc = "" +
	"\n" +
	"$events/historical_event_events.proto\x12\x06events\"\xc0\x04\n" +
	"\x1bHistoricalEventCreatedEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\tthumbnail\x18\x04 \x01(\tH\x00R\tthumbnail\x88\x01\x01\x12$\n" +
	"\x0efrom_date_type\x18\x05 \x01(\tR\ffromDateType\x12\x1e\n" +
	"\bfrom_day\x18\x06 \x01(\x05H\x01R\afromDay\x88\x01\x01\x12\"\n" +
	"\n" +
	"from_month\x18\a \x01(\x05H\x02R\tfromMonth\x88\x01\x01\x12\x1b\n" +
	"\tfrom_year\x18\b \x01(\x05R\bfromYear\x12%\n" +
	"\fto_date_type\x18\t \x01(\tH\x03R\n" +
	"toDateType\x88\x01\x01\x12\x1a\n" +
	"\x06to_day\x18\n" +
	" \x01(\x05H\x04R\x05toDay\x88\x01\x01\x12\x1e\n" +
	"\bto_month\x18\v \x01(\x05H\x05R\atoMonth\x88\x01\x01\x12\x1c\n" +
	"\ato_year\x18\f \x01(\x05H\x06R\x06toYear\x88\x01\x01\x12\x18\n" +
	"\acontent\x18\r \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAtB\f\n" +
	"\n" +
	"_thumbnailB\v\n" +
	"\t_from_dayB\r\n" +
	"\v_from_monthB\x0f\n" +
	"\r_to_date_typeB\t\n" +
	"\a_to_dayB\v\n" +
	"\t_to_monthB\n" +
	"\n" +
	"\b_to_year\"\xe2\x04\n" +
	"\x1bHistoricalEventUpdatedEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12!\n" +
	"\tthumbnail\x18\x03 \x01(\tH\x01R\tthumbnail\x88\x01\x01\x12)\n" +
	"\x0efrom_date_type\x18\x04 \x01(\tH\x02R\ffromDateType\x88\x01\x01\x12\x1e\n" +
	"\bfrom_day\x18\x05 \x01(\x05H\x03R\afromDay\x88\x01\x01\x12\"\n" +
	"\n" +
	"from_month\x18\x06 \x01(\x05H\x04R\tfromMonth\x88\x01\x01\x12 \n" +
	"\tfrom_year\x18\a \x01(\x05H\x05R\bfromYear\x88\x01\x01\x12%\n" +
	"\fto_date_type\x18\b \x01(\tH\x06R\n" +
	"toDateType\x88\x01\x01\x12\x1a\n" +
	"\x06to_day\x18\t \x01(\x05H\aR\x05toDay\x88\x01\x01\x12\x1e\n" +
	"\bto_month\x18\n" +
	" \x01(\x05H\bR\atoMonth\x88\x01\x01\x12\x1c\n" +
	"\ato_year\x18\v \x01(\x05H\tR\x06toYear\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\f \x01(\tH\n" +
	"R\acontent\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\r \x01(\tH\vR\tupdatedAt\x88\x01\x01B\a\n" +
	"\x05_nameB\f\n" +
	"\n" +
	"_thumbnailB\x11\n" +
	"\x0f_from_date_typeB\v\n" +
	"\t_from_dayB\r\n" +
	"\v_from_monthB\f\n" +
	"\n" +
	"_from_yearB\x0f\n" +
	"\r_to_date_typeB\t\n" +
	"\a_to_dayB\v\n" +
	"\t_to_monthB\n" +
	"\n" +
	"\b_to_yearB\n" +
	"\n" +
	"\b_contentB\r\n" +
	"\v_updated_at\"J\n" +
	"\x1bHistoricalEventDeletedEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorIdBIZGgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/events;eventsb\x06proto3"

var (
	file_events_historical_event_events_proto_rawDescOnce sync.Once
	file_events_historical_event_events_proto_rawDescData []byte
)

func file_events_historical_event_events_proto_rawDescGZIP() []byte {
	file_events_historical_event_events_proto_rawDescOnce.Do(func() {
		file_events_historical_event_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_historical_event_events_proto_rawDesc), len(file_events_historical_event_events_proto_rawDesc)))
	})
	return file_events_historical_event_events_proto_rawDescData
}

var file_events_historical_event_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_historical_event_events_proto_goTypes = []any{
	(*HistoricalEventCreatedEvent)(nil), // 0: events.HistoricalEventCreatedEvent
	(*HistoricalEventUpdatedEvent)(nil), // 1: events.HistoricalEventUpdatedEvent
	(*HistoricalEventDeletedEvent)(nil), // 2: events.HistoricalEventDeletedEvent
}
var file_events_historical_event_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_historical_event_events_proto_init() }
func file_events_historical_event_events_proto_init() {
	if File_events_historical_event_events_proto != nil {
		return
	}
	file_events_historical_event_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_events_historical_event_events_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_historical_event_events_proto_rawDesc), len(file_events_historical_event_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_historical_event_events_proto_goTypes,
		DependencyIndexes: file_events_historical_event_events_proto_depIdxs,
		MessageInfos:      file_events_historical_event_events_proto_msgTypes,
	}.Build()
	File_events_historical_event_events_proto = out.File
	file_events_historical_event_events_proto_goTypes = nil
	file_events_historical_event_events_proto_depIdxs = nil
}
