// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: events/user_event.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddedToOrganization struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IsPremium      bool                   `protobuf:"varint,3,opt,name=is_premium,json=isPremium,proto3" json:"is_premium,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserAddedToOrganization) Reset() {
	*x = UserAddedToOrganization{}
	mi := &file_events_user_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddedToOrganization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddedToOrganization) ProtoMessage() {}

func (x *UserAddedToOrganization) ProtoReflect() protoreflect.Message {
	mi := &file_events_user_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddedToOrganization.ProtoReflect.Descriptor instead.
func (*UserAddedToOrganization) Descriptor() ([]byte, []int) {
	return file_events_user_event_proto_rawDescGZIP(), []int{0}
}

func (x *UserAddedToOrganization) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAddedToOrganization) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UserAddedToOrganization) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

var File_events_user_event_proto protoreflect.FileDescriptor

const file_events_user_event_proto_rawDesc = "" +
	"\n" +
	"\x17events/user_event.proto\x12\x06events\"z\n" +
	"\x17UserAddedToOrganization\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"is_premium\x18\x03 \x01(\bR\tisPremiumBIZGgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/events;eventsb\x06proto3"

var (
	file_events_user_event_proto_rawDescOnce sync.Once
	file_events_user_event_proto_rawDescData []byte
)

func file_events_user_event_proto_rawDescGZIP() []byte {
	file_events_user_event_proto_rawDescOnce.Do(func() {
		file_events_user_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_user_event_proto_rawDesc), len(file_events_user_event_proto_rawDesc)))
	})
	return file_events_user_event_proto_rawDescData
}

var file_events_user_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_user_event_proto_goTypes = []any{
	(*UserAddedToOrganization)(nil), // 0: events.UserAddedToOrganization
}
var file_events_user_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_user_event_proto_init() }
func file_events_user_event_proto_init() {
	if File_events_user_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_user_event_proto_rawDesc), len(file_events_user_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_user_event_proto_goTypes,
		DependencyIndexes: file_events_user_event_proto_depIdxs,
		MessageInfos:      file_events_user_event_proto_msgTypes,
	}.Build()
	File_events_user_event_proto = out.File
	file_events_user_event_proto_goTypes = nil
	file_events_user_event_proto_depIdxs = nil
}
