// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: billing_service/payment_attempts.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { Struct } from "../google/protobuf/struct";
import { Timestamp } from "../google/protobuf/timestamp";
import { Money } from "./billing";
import { PaymentTransaction } from "./payment_transactions";

export const protobufPackage = "billing_service";

export enum PaymentAttemptStatus {
  PAYMENT_ATTEMPT_STATUS_UNSPECIFIED = 0,
  PAYMENT_ATTEMPT_STATUS_CREATED = 1,
  PAYMENT_ATTEMPT_STATUS_PENDING = 2,
  PAYMENT_ATTEMPT_STATUS_SUCCEEDED = 3,
  PAYMENT_ATTEMPT_STATUS_FAILED = 4,
  PAYMENT_ATTEMPT_STATUS_EXPIRED = 5,
  PAYMENT_ATTEMPT_STATUS_CANCELED = 6,
  UNRECOGNIZED = -1,
}

export interface PaymentAttempt {
  id: string;
  purchaseId: string;
  /** "stripe", "momo", "zalopay" */
  provider: string;
  status: PaymentAttemptStatus;
  amount:
    | Money
    | undefined;
  /** session/order id */
  providerTransactionId: string;
  checkoutUrl: string;
  providerMetadata: { [key: string]: any } | undefined;
  expiresAt: Timestamp | undefined;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}

export interface CreatePaymentAttemptRequest {
  purchaseId: string;
  /** Which provider to use for this attempt ("momo", "zalopay", "stripe", ...) */
  provider: string;
  /**
   * Optional: specify amounts if you allow partial payments; otherwise server
   * should take from purchase.amount.
   */
  amount:
    | Money
    | undefined;
  /** Extra provider-specific options (return URLs, locale, bank code, etc.) */
  providerOptions:
    | { [key: string]: any }
    | undefined;
  /** Recommended: idempotency key for attempt creation */
  idempotencyKey: string;
}

export interface CreatePaymentAttemptResponse {
  paymentAttempt: PaymentAttempt | undefined;
}

export interface GetPaymentAttemptRequest {
  paymentAttemptId: string;
}

export interface GetPaymentAttemptResponse {
  paymentAttempt: PaymentAttempt | undefined;
}

export interface ListPaymentAttemptsByPurchaseRequest {
  purchaseId: string;
}

export interface ListPaymentAttemptsByPurchaseResponse {
  paymentAttempts: PaymentAttempt[];
}

/**
 * Initiate a refund for a specific purchase.
 * Server should:
 * - locate successful attempt(s) for that purchase,
 * - pick the capture transaction(s),
 * - call provider API,
 * - record refund transaction(s).
 */
export interface RefundPurchaseRequest {
  purchaseId: string;
  /**
   * If empty => full refund (server decides amount)
   * If set => partial refund (must be <= captured - already_refunded)
   */
  amount:
    | Money
    | undefined;
  /** Optional free-form reason */
  reason: string;
  /** Idempotency for refund requests */
  idempotencyKey: string;
  /**
   * Optional: force a particular provider rail.
   * If set, server must ensure the purchase was paid via this provider, otherwise error.
   */
  provider: string;
}

export interface RefundPurchaseResponse {
  /**
   * The refund transaction(s) created as a result.
   * Some providers may create multiple records (fees, partials, etc.)
   */
  refundTransactions: PaymentTransaction[];
}

export const BILLING_SERVICE_PACKAGE_NAME = "billing_service";

wrappers[".google.protobuf.Struct"] = { fromObject: Struct.wrap, toObject: Struct.unwrap } as any;

export interface PaymentServiceClient {
  createPaymentAttempt(request: CreatePaymentAttemptRequest): Observable<CreatePaymentAttemptResponse>;

  getPaymentAttempt(request: GetPaymentAttemptRequest): Observable<GetPaymentAttemptResponse>;

  listPaymentAttemptsByPurchase(
    request: ListPaymentAttemptsByPurchaseRequest,
  ): Observable<ListPaymentAttemptsByPurchaseResponse>;

  refundPurchase(request: RefundPurchaseRequest): Observable<RefundPurchaseResponse>;
}

export interface PaymentServiceController {
  createPaymentAttempt(
    request: CreatePaymentAttemptRequest,
  ): Promise<CreatePaymentAttemptResponse> | Observable<CreatePaymentAttemptResponse> | CreatePaymentAttemptResponse;

  getPaymentAttempt(
    request: GetPaymentAttemptRequest,
  ): Promise<GetPaymentAttemptResponse> | Observable<GetPaymentAttemptResponse> | GetPaymentAttemptResponse;

  listPaymentAttemptsByPurchase(
    request: ListPaymentAttemptsByPurchaseRequest,
  ):
    | Promise<ListPaymentAttemptsByPurchaseResponse>
    | Observable<ListPaymentAttemptsByPurchaseResponse>
    | ListPaymentAttemptsByPurchaseResponse;

  refundPurchase(
    request: RefundPurchaseRequest,
  ): Promise<RefundPurchaseResponse> | Observable<RefundPurchaseResponse> | RefundPurchaseResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createPaymentAttempt",
      "getPaymentAttempt",
      "listPaymentAttemptsByPurchase",
      "refundPurchase",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
