// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/billing.proto

package billing_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`    // minor units (cents). For VND, typically whole units.
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // ISO-4217, e.g. "USD", "VND"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_billing_service_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_billing_service_billing_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PaymentWebhookEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalEventId string                 `protobuf:"bytes,3,opt,name=external_event_id,json=externalEventId,proto3" json:"external_event_id,omitempty"`
	EventType       string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload         *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Processed       bool                   `protobuf:"varint,6,opt,name=processed,proto3" json:"processed,omitempty"`
	ProcessedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentWebhookEvent) Reset() {
	*x = PaymentWebhookEvent{}
	mi := &file_billing_service_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentWebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentWebhookEvent) ProtoMessage() {}

func (x *PaymentWebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentWebhookEvent.ProtoReflect.Descriptor instead.
func (*PaymentWebhookEvent) Descriptor() ([]byte, []int) {
	return file_billing_service_billing_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentWebhookEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentWebhookEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentWebhookEvent) GetExternalEventId() string {
	if x != nil {
		return x.ExternalEventId
	}
	return ""
}

func (x *PaymentWebhookEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PaymentWebhookEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PaymentWebhookEvent) GetProcessed() bool {
	if x != nil {
		return x.Processed
	}
	return false
}

func (x *PaymentWebhookEvent) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *PaymentWebhookEvent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PaymentWebhookEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Generic webhook ingest. Your edge/API gateway can call this after verifying
// provider signatures, or your service can verify internally (your choice).
type IngestWebhookRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalEventId string                 `protobuf:"bytes,2,opt,name=external_event_id,json=externalEventId,proto3" json:"external_event_id,omitempty"`
	EventType       string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload         *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// When you received it (optional).
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestWebhookRequest) Reset() {
	*x = IngestWebhookRequest{}
	mi := &file_billing_service_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestWebhookRequest) ProtoMessage() {}

func (x *IngestWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestWebhookRequest.ProtoReflect.Descriptor instead.
func (*IngestWebhookRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_billing_proto_rawDescGZIP(), []int{2}
}

func (x *IngestWebhookRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *IngestWebhookRequest) GetExternalEventId() string {
	if x != nil {
		return x.ExternalEventId
	}
	return ""
}

func (x *IngestWebhookRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IngestWebhookRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngestWebhookRequest) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

type IngestWebhookResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StoredEvent *PaymentWebhookEvent   `protobuf:"bytes,1,opt,name=stored_event,json=storedEvent,proto3" json:"stored_event,omitempty"`
	// true if this webhook event was newly accepted (not a duplicate)
	Accepted      bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestWebhookResponse) Reset() {
	*x = IngestWebhookResponse{}
	mi := &file_billing_service_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestWebhookResponse) ProtoMessage() {}

func (x *IngestWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestWebhookResponse.ProtoReflect.Descriptor instead.
func (*IngestWebhookResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_billing_proto_rawDescGZIP(), []int{3}
}

func (x *IngestWebhookResponse) GetStoredEvent() *PaymentWebhookEvent {
	if x != nil {
		return x.StoredEvent
	}
	return nil
}

func (x *IngestWebhookResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_billing_service_billing_proto protoreflect.FileDescriptor

const file_billing_service_billing_proto_rawDesc = "" +
	"\n" +
	"\x1dbilling_service/billing.proto\x12\x0fbilling_service\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xfc\x02\n" +
	"\x13PaymentWebhookEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12*\n" +
	"\x11external_event_id\x18\x03 \x01(\tR\x0fexternalEventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1c\n" +
	"\tprocessed\x18\x06 \x01(\bR\tprocessed\x12=\n" +
	"\fprocessed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xed\x01\n" +
	"\x14IngestWebhookRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12*\n" +
	"\x11external_event_id\x18\x02 \x01(\tR\x0fexternalEventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x12;\n" +
	"\vreceived_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"|\n" +
	"\x15IngestWebhookResponse\x12G\n" +
	"\fstored_event\x18\x01 \x01(\v2$.billing_service.PaymentWebhookEventR\vstoredEvent\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted2w\n" +
	"\x15PaymentWebhookService\x12^\n" +
	"\rIngestWebhook\x12%.billing_service.IngestWebhookRequest\x1a&.billing_service.IngestWebhookResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_billing_proto_rawDescOnce sync.Once
	file_billing_service_billing_proto_rawDescData []byte
)

func file_billing_service_billing_proto_rawDescGZIP() []byte {
	file_billing_service_billing_proto_rawDescOnce.Do(func() {
		file_billing_service_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_billing_proto_rawDesc), len(file_billing_service_billing_proto_rawDesc)))
	})
	return file_billing_service_billing_proto_rawDescData
}

var file_billing_service_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_billing_service_billing_proto_goTypes = []any{
	(*Money)(nil),                 // 0: billing_service.Money
	(*PaymentWebhookEvent)(nil),   // 1: billing_service.PaymentWebhookEvent
	(*IngestWebhookRequest)(nil),  // 2: billing_service.IngestWebhookRequest
	(*IngestWebhookResponse)(nil), // 3: billing_service.IngestWebhookResponse
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_billing_service_billing_proto_depIdxs = []int32{
	4, // 0: billing_service.PaymentWebhookEvent.payload:type_name -> google.protobuf.Struct
	5, // 1: billing_service.PaymentWebhookEvent.processed_at:type_name -> google.protobuf.Timestamp
	5, // 2: billing_service.PaymentWebhookEvent.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: billing_service.IngestWebhookRequest.payload:type_name -> google.protobuf.Struct
	5, // 4: billing_service.IngestWebhookRequest.received_at:type_name -> google.protobuf.Timestamp
	1, // 5: billing_service.IngestWebhookResponse.stored_event:type_name -> billing_service.PaymentWebhookEvent
	2, // 6: billing_service.PaymentWebhookService.IngestWebhook:input_type -> billing_service.IngestWebhookRequest
	3, // 7: billing_service.PaymentWebhookService.IngestWebhook:output_type -> billing_service.IngestWebhookResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_billing_service_billing_proto_init() }
func file_billing_service_billing_proto_init() {
	if File_billing_service_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_billing_proto_rawDesc), len(file_billing_service_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_billing_proto_goTypes,
		DependencyIndexes: file_billing_service_billing_proto_depIdxs,
		MessageInfos:      file_billing_service_billing_proto_msgTypes,
	}.Build()
	File_billing_service_billing_proto = out.File
	file_billing_service_billing_proto_goTypes = nil
	file_billing_service_billing_proto_depIdxs = nil
}
