// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/inbox_events.proto

package billing_service

import (
	common "github.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InboxEventStatus represents the lifecycle state of an event in the inbox pattern.
type InboxEventStatus int32

const (
	InboxEventStatus_INBOX_EVENT_STATUS_UNSPECIFIED InboxEventStatus = 0
	InboxEventStatus_INBOX_EVENT_STATUS_PENDING     InboxEventStatus = 1
	InboxEventStatus_INBOX_EVENT_STATUS_PUBLISHED   InboxEventStatus = 2
	InboxEventStatus_INBOX_EVENT_STATUS_FAILED      InboxEventStatus = 3
	InboxEventStatus_INBOX_EVENT_STATUS_RETRYING    InboxEventStatus = 4
	InboxEventStatus_INBOX_EVENT_STATUS_DEAD        InboxEventStatus = 5
)

// Enum value maps for InboxEventStatus.
var (
	InboxEventStatus_name = map[int32]string{
		0: "INBOX_EVENT_STATUS_UNSPECIFIED",
		1: "INBOX_EVENT_STATUS_PENDING",
		2: "INBOX_EVENT_STATUS_PUBLISHED",
		3: "INBOX_EVENT_STATUS_FAILED",
		4: "INBOX_EVENT_STATUS_RETRYING",
		5: "INBOX_EVENT_STATUS_DEAD",
	}
	InboxEventStatus_value = map[string]int32{
		"INBOX_EVENT_STATUS_UNSPECIFIED": 0,
		"INBOX_EVENT_STATUS_PENDING":     1,
		"INBOX_EVENT_STATUS_PUBLISHED":   2,
		"INBOX_EVENT_STATUS_FAILED":      3,
		"INBOX_EVENT_STATUS_RETRYING":    4,
		"INBOX_EVENT_STATUS_DEAD":        5,
	}
)

func (x InboxEventStatus) Enum() *InboxEventStatus {
	p := new(InboxEventStatus)
	*p = x
	return p
}

func (x InboxEventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InboxEventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_service_inbox_events_proto_enumTypes[0].Descriptor()
}

func (InboxEventStatus) Type() protoreflect.EnumType {
	return &file_billing_service_inbox_events_proto_enumTypes[0]
}

func (x InboxEventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InboxEventStatus.Descriptor instead.
func (InboxEventStatus) EnumDescriptor() ([]byte, []int) {
	return file_billing_service_inbox_events_proto_rawDescGZIP(), []int{0}
}

type InboxEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventType       string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Provider        string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalEventId string                 `protobuf:"bytes,4,opt,name=external_event_id,json=externalEventId,proto3" json:"external_event_id,omitempty"`
	Payload         *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature       string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Status          InboxEventStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=billing_service.InboxEventStatus" json:"status,omitempty"`
	RetryCount      int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	NextRetryAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	PublishedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InboxEvent) Reset() {
	*x = InboxEvent{}
	mi := &file_billing_service_inbox_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxEvent) ProtoMessage() {}

func (x *InboxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_inbox_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxEvent.ProtoReflect.Descriptor instead.
func (*InboxEvent) Descriptor() ([]byte, []int) {
	return file_billing_service_inbox_events_proto_rawDescGZIP(), []int{0}
}

func (x *InboxEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InboxEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *InboxEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *InboxEvent) GetExternalEventId() string {
	if x != nil {
		return x.ExternalEventId
	}
	return ""
}

func (x *InboxEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InboxEvent) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *InboxEvent) GetStatus() InboxEventStatus {
	if x != nil {
		return x.Status
	}
	return InboxEventStatus_INBOX_EVENT_STATUS_UNSPECIFIED
}

func (x *InboxEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *InboxEvent) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

func (x *InboxEvent) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *InboxEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetInboxEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboxEventRequest) Reset() {
	*x = GetInboxEventRequest{}
	mi := &file_billing_service_inbox_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboxEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboxEventRequest) ProtoMessage() {}

func (x *GetInboxEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_inbox_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboxEventRequest.ProtoReflect.Descriptor instead.
func (*GetInboxEventRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_inbox_events_proto_rawDescGZIP(), []int{1}
}

func (x *GetInboxEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInboxEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *InboxEvent            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInboxEventResponse) Reset() {
	*x = GetInboxEventResponse{}
	mi := &file_billing_service_inbox_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInboxEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInboxEventResponse) ProtoMessage() {}

func (x *GetInboxEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_inbox_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInboxEventResponse.ProtoReflect.Descriptor instead.
func (*GetInboxEventResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_inbox_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetInboxEventResponse) GetData() *InboxEvent {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListInboxEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        InboxEventStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=billing_service.InboxEventStatus" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboxEventsRequest) Reset() {
	*x = ListInboxEventsRequest{}
	mi := &file_billing_service_inbox_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboxEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxEventsRequest) ProtoMessage() {}

func (x *ListInboxEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_inbox_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxEventsRequest.ProtoReflect.Descriptor instead.
func (*ListInboxEventsRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_inbox_events_proto_rawDescGZIP(), []int{3}
}

func (x *ListInboxEventsRequest) GetStatus() InboxEventStatus {
	if x != nil {
		return x.Status
	}
	return InboxEventStatus_INBOX_EVENT_STATUS_UNSPECIFIED
}

func (x *ListInboxEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInboxEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListInboxEventsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*InboxEvent              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboxEventsResponse) Reset() {
	*x = ListInboxEventsResponse{}
	mi := &file_billing_service_inbox_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboxEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxEventsResponse) ProtoMessage() {}

func (x *ListInboxEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_inbox_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxEventsResponse.ProtoReflect.Descriptor instead.
func (*ListInboxEventsResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_inbox_events_proto_rawDescGZIP(), []int{4}
}

func (x *ListInboxEventsResponse) GetData() []*InboxEvent {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListInboxEventsResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_billing_service_inbox_events_proto protoreflect.FileDescriptor

const file_billing_service_inbox_events_proto_rawDesc = "" +
	"\n" +
	"\"billing_service/inbox_events.proto\x12\x0fbilling_service\x1a\x17common/pagination.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x03\n" +
	"\n" +
	"InboxEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12*\n" +
	"\x11external_event_id\x18\x04 \x01(\tR\x0fexternalEventId\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.billing_service.InboxEventStatusR\x06status\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12>\n" +
	"\rnext_retry_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt\x12=\n" +
	"\fpublished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"&\n" +
	"\x14GetInboxEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x15GetInboxEventResponse\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.billing_service.InboxEventR\x04data\"\x8f\x01\n" +
	"\x16ListInboxEventsRequest\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.billing_service.InboxEventStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x17ListInboxEventsResponse\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.billing_service.InboxEventR\x04data\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination*\xd5\x01\n" +
	"\x10InboxEventStatus\x12\"\n" +
	"\x1eINBOX_EVENT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aINBOX_EVENT_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cINBOX_EVENT_STATUS_PUBLISHED\x10\x02\x12\x1d\n" +
	"\x19INBOX_EVENT_STATUS_FAILED\x10\x03\x12\x1f\n" +
	"\x1bINBOX_EVENT_STATUS_RETRYING\x10\x04\x12\x1b\n" +
	"\x17INBOX_EVENT_STATUS_DEAD\x10\x052\xd4\x01\n" +
	"\fInboxService\x12^\n" +
	"\rGetInboxEvent\x12%.billing_service.GetInboxEventRequest\x1a&.billing_service.GetInboxEventResponse\x12d\n" +
	"\x0fListInboxEvents\x12'.billing_service.ListInboxEventsRequest\x1a(.billing_service.ListInboxEventsResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_inbox_events_proto_rawDescOnce sync.Once
	file_billing_service_inbox_events_proto_rawDescData []byte
)

func file_billing_service_inbox_events_proto_rawDescGZIP() []byte {
	file_billing_service_inbox_events_proto_rawDescOnce.Do(func() {
		file_billing_service_inbox_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_inbox_events_proto_rawDesc), len(file_billing_service_inbox_events_proto_rawDesc)))
	})
	return file_billing_service_inbox_events_proto_rawDescData
}

var file_billing_service_inbox_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_service_inbox_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_billing_service_inbox_events_proto_goTypes = []any{
	(InboxEventStatus)(0),             // 0: billing_service.InboxEventStatus
	(*InboxEvent)(nil),                // 1: billing_service.InboxEvent
	(*GetInboxEventRequest)(nil),      // 2: billing_service.GetInboxEventRequest
	(*GetInboxEventResponse)(nil),     // 3: billing_service.GetInboxEventResponse
	(*ListInboxEventsRequest)(nil),    // 4: billing_service.ListInboxEventsRequest
	(*ListInboxEventsResponse)(nil),   // 5: billing_service.ListInboxEventsResponse
	(*structpb.Struct)(nil),           // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
	(*common.PaginationMetadata)(nil), // 8: common.PaginationMetadata
}
var file_billing_service_inbox_events_proto_depIdxs = []int32{
	6,  // 0: billing_service.InboxEvent.payload:type_name -> google.protobuf.Struct
	0,  // 1: billing_service.InboxEvent.status:type_name -> billing_service.InboxEventStatus
	7,  // 2: billing_service.InboxEvent.next_retry_at:type_name -> google.protobuf.Timestamp
	7,  // 3: billing_service.InboxEvent.published_at:type_name -> google.protobuf.Timestamp
	7,  // 4: billing_service.InboxEvent.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: billing_service.GetInboxEventResponse.data:type_name -> billing_service.InboxEvent
	0,  // 6: billing_service.ListInboxEventsRequest.status:type_name -> billing_service.InboxEventStatus
	1,  // 7: billing_service.ListInboxEventsResponse.data:type_name -> billing_service.InboxEvent
	8,  // 8: billing_service.ListInboxEventsResponse.pagination:type_name -> common.PaginationMetadata
	2,  // 9: billing_service.InboxService.GetInboxEvent:input_type -> billing_service.GetInboxEventRequest
	4,  // 10: billing_service.InboxService.ListInboxEvents:input_type -> billing_service.ListInboxEventsRequest
	3,  // 11: billing_service.InboxService.GetInboxEvent:output_type -> billing_service.GetInboxEventResponse
	5,  // 12: billing_service.InboxService.ListInboxEvents:output_type -> billing_service.ListInboxEventsResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_billing_service_inbox_events_proto_init() }
func file_billing_service_inbox_events_proto_init() {
	if File_billing_service_inbox_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_inbox_events_proto_rawDesc), len(file_billing_service_inbox_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_inbox_events_proto_goTypes,
		DependencyIndexes: file_billing_service_inbox_events_proto_depIdxs,
		EnumInfos:         file_billing_service_inbox_events_proto_enumTypes,
		MessageInfos:      file_billing_service_inbox_events_proto_msgTypes,
	}.Build()
	File_billing_service_inbox_events_proto = out.File
	file_billing_service_inbox_events_proto_goTypes = nil
	file_billing_service_inbox_events_proto_depIdxs = nil
}
