// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: billing_service/outbox_events.proto

package billing_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutboxService_GetOutboxEvent_FullMethodName   = "/billing_service.OutboxService/GetOutboxEvent"
	OutboxService_ListOutboxEvents_FullMethodName = "/billing_service.OutboxService/ListOutboxEvents"
)

// OutboxServiceClient is the client API for OutboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutboxServiceClient interface {
	GetOutboxEvent(ctx context.Context, in *GetOutboxEventRequest, opts ...grpc.CallOption) (*GetOutboxEventResponse, error)
	ListOutboxEvents(ctx context.Context, in *ListOutboxEventsRequest, opts ...grpc.CallOption) (*ListOutboxEventsResponse, error)
}

type outboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutboxServiceClient(cc grpc.ClientConnInterface) OutboxServiceClient {
	return &outboxServiceClient{cc}
}

func (c *outboxServiceClient) GetOutboxEvent(ctx context.Context, in *GetOutboxEventRequest, opts ...grpc.CallOption) (*GetOutboxEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOutboxEventResponse)
	err := c.cc.Invoke(ctx, OutboxService_GetOutboxEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboxServiceClient) ListOutboxEvents(ctx context.Context, in *ListOutboxEventsRequest, opts ...grpc.CallOption) (*ListOutboxEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOutboxEventsResponse)
	err := c.cc.Invoke(ctx, OutboxService_ListOutboxEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutboxServiceServer is the server API for OutboxService service.
// All implementations should embed UnimplementedOutboxServiceServer
// for forward compatibility.
type OutboxServiceServer interface {
	GetOutboxEvent(context.Context, *GetOutboxEventRequest) (*GetOutboxEventResponse, error)
	ListOutboxEvents(context.Context, *ListOutboxEventsRequest) (*ListOutboxEventsResponse, error)
}

// UnimplementedOutboxServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutboxServiceServer struct{}

func (UnimplementedOutboxServiceServer) GetOutboxEvent(context.Context, *GetOutboxEventRequest) (*GetOutboxEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOutboxEvent not implemented")
}
func (UnimplementedOutboxServiceServer) ListOutboxEvents(context.Context, *ListOutboxEventsRequest) (*ListOutboxEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOutboxEvents not implemented")
}
func (UnimplementedOutboxServiceServer) testEmbeddedByValue() {}

// UnsafeOutboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutboxServiceServer will
// result in compilation errors.
type UnsafeOutboxServiceServer interface {
	mustEmbedUnimplementedOutboxServiceServer()
}

func RegisterOutboxServiceServer(s grpc.ServiceRegistrar, srv OutboxServiceServer) {
	// If the following call panics, it indicates UnimplementedOutboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutboxService_ServiceDesc, srv)
}

func _OutboxService_GetOutboxEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOutboxEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboxServiceServer).GetOutboxEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutboxService_GetOutboxEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboxServiceServer).GetOutboxEvent(ctx, req.(*GetOutboxEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboxService_ListOutboxEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOutboxEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboxServiceServer).ListOutboxEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutboxService_ListOutboxEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboxServiceServer).ListOutboxEvents(ctx, req.(*ListOutboxEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutboxService_ServiceDesc is the grpc.ServiceDesc for OutboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing_service.OutboxService",
	HandlerType: (*OutboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOutboxEvent",
			Handler:    _OutboxService_GetOutboxEvent_Handler,
		},
		{
			MethodName: "ListOutboxEvents",
			Handler:    _OutboxService_ListOutboxEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_service/outbox_events.proto",
}
