// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/outbox_events.proto

package billing_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OutboxEventStatus represents the lifecycle state of an event in the outbox pattern.
// The outbox pattern ensures reliable event publishing by storing events in the database
// and processing them asynchronously.
type OutboxEventStatus int32

const (
	// Unspecified status; should not be used
	OutboxEventStatus_OUTBOX_EVENT_STATUS_UNSPECIFIED OutboxEventStatus = 0
	// Event has been created but not yet published to message broker
	OutboxEventStatus_OUTBOX_EVENT_STATUS_PENDING OutboxEventStatus = 1
	// Event has been successfully published to message broker
	OutboxEventStatus_OUTBOX_EVENT_STATUS_PUBLISHED OutboxEventStatus = 2
	// Event publication failed; will be retried
	OutboxEventStatus_OUTBOX_EVENT_STATUS_FAILED OutboxEventStatus = 3
	// Event is currently being retried after a previous failure
	OutboxEventStatus_OUTBOX_EVENT_STATUS_RETRYING OutboxEventStatus = 4
	// Event reached maximum retry count; permanently failed and abandoned
	OutboxEventStatus_OUTBOX_EVENT_STATUS_DEAD OutboxEventStatus = 5
)

// Enum value maps for OutboxEventStatus.
var (
	OutboxEventStatus_name = map[int32]string{
		0: "OUTBOX_EVENT_STATUS_UNSPECIFIED",
		1: "OUTBOX_EVENT_STATUS_PENDING",
		2: "OUTBOX_EVENT_STATUS_PUBLISHED",
		3: "OUTBOX_EVENT_STATUS_FAILED",
		4: "OUTBOX_EVENT_STATUS_RETRYING",
		5: "OUTBOX_EVENT_STATUS_DEAD",
	}
	OutboxEventStatus_value = map[string]int32{
		"OUTBOX_EVENT_STATUS_UNSPECIFIED": 0,
		"OUTBOX_EVENT_STATUS_PENDING":     1,
		"OUTBOX_EVENT_STATUS_PUBLISHED":   2,
		"OUTBOX_EVENT_STATUS_FAILED":      3,
		"OUTBOX_EVENT_STATUS_RETRYING":    4,
		"OUTBOX_EVENT_STATUS_DEAD":        5,
	}
)

func (x OutboxEventStatus) Enum() *OutboxEventStatus {
	p := new(OutboxEventStatus)
	*p = x
	return p
}

func (x OutboxEventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutboxEventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_service_outbox_events_proto_enumTypes[0].Descriptor()
}

func (OutboxEventStatus) Type() protoreflect.EnumType {
	return &file_billing_service_outbox_events_proto_enumTypes[0]
}

func (x OutboxEventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutboxEventStatus.Descriptor instead.
func (OutboxEventStatus) EnumDescriptor() ([]byte, []int) {
	return file_billing_service_outbox_events_proto_rawDescGZIP(), []int{0}
}

type OutboxEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	AggregateType string                 `protobuf:"bytes,2,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateId   string                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"` // UUID-as-string
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// This should be a JSON-encoded string of the EventEnvelope.
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        OutboxEventStatus      `protobuf:"varint,6,opt,name=status,proto3,enum=billing_service.OutboxEventStatus" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	NextRetryAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboxEvent) Reset() {
	*x = OutboxEvent{}
	mi := &file_billing_service_outbox_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxEvent) ProtoMessage() {}

func (x *OutboxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_outbox_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxEvent.ProtoReflect.Descriptor instead.
func (*OutboxEvent) Descriptor() ([]byte, []int) {
	return file_billing_service_outbox_events_proto_rawDescGZIP(), []int{0}
}

func (x *OutboxEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboxEvent) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *OutboxEvent) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *OutboxEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OutboxEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OutboxEvent) GetStatus() OutboxEventStatus {
	if x != nil {
		return x.Status
	}
	return OutboxEventStatus_OUTBOX_EVENT_STATUS_UNSPECIFIED
}

func (x *OutboxEvent) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *OutboxEvent) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

func (x *OutboxEvent) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *OutboxEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetOutboxEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutboxEventRequest) Reset() {
	*x = GetOutboxEventRequest{}
	mi := &file_billing_service_outbox_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutboxEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutboxEventRequest) ProtoMessage() {}

func (x *GetOutboxEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_outbox_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutboxEventRequest.ProtoReflect.Descriptor instead.
func (*GetOutboxEventRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_outbox_events_proto_rawDescGZIP(), []int{1}
}

func (x *GetOutboxEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOutboxEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *OutboxEvent           `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutboxEventResponse) Reset() {
	*x = GetOutboxEventResponse{}
	mi := &file_billing_service_outbox_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutboxEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutboxEventResponse) ProtoMessage() {}

func (x *GetOutboxEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_outbox_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutboxEventResponse.ProtoReflect.Descriptor instead.
func (*GetOutboxEventResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_outbox_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetOutboxEventResponse) GetEvent() *OutboxEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type ListOutboxEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filter examples
	Status        OutboxEventStatus `protobuf:"varint,1,opt,name=status,proto3,enum=billing_service.OutboxEventStatus" json:"status,omitempty"`
	PageSize      int32             `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string            `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutboxEventsRequest) Reset() {
	*x = ListOutboxEventsRequest{}
	mi := &file_billing_service_outbox_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutboxEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutboxEventsRequest) ProtoMessage() {}

func (x *ListOutboxEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_outbox_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutboxEventsRequest.ProtoReflect.Descriptor instead.
func (*ListOutboxEventsRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_outbox_events_proto_rawDescGZIP(), []int{3}
}

func (x *ListOutboxEventsRequest) GetStatus() OutboxEventStatus {
	if x != nil {
		return x.Status
	}
	return OutboxEventStatus_OUTBOX_EVENT_STATUS_UNSPECIFIED
}

func (x *ListOutboxEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOutboxEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOutboxEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*OutboxEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutboxEventsResponse) Reset() {
	*x = ListOutboxEventsResponse{}
	mi := &file_billing_service_outbox_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutboxEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutboxEventsResponse) ProtoMessage() {}

func (x *ListOutboxEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_outbox_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutboxEventsResponse.ProtoReflect.Descriptor instead.
func (*ListOutboxEventsResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_outbox_events_proto_rawDescGZIP(), []int{4}
}

func (x *ListOutboxEventsResponse) GetEvents() []*OutboxEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListOutboxEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_billing_service_outbox_events_proto protoreflect.FileDescriptor

const file_billing_service_outbox_events_proto_rawDesc = "" +
	"\n" +
	"#billing_service/outbox_events.proto\x12\x0fbilling_service\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x03\n" +
	"\vOutboxEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaggregate_type\x18\x02 \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\x03 \x01(\tR\vaggregateId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12:\n" +
	"\x06status\x18\x06 \x01(\x0e2\".billing_service.OutboxEventStatusR\x06status\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x12>\n" +
	"\rnext_retry_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt\x12=\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"'\n" +
	"\x15GetOutboxEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16GetOutboxEventResponse\x122\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.billing_service.OutboxEventR\x05event\"\x91\x01\n" +
	"\x17ListOutboxEventsRequest\x12:\n" +
	"\x06status\x18\x01 \x01(\x0e2\".billing_service.OutboxEventStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"x\n" +
	"\x18ListOutboxEventsResponse\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.billing_service.OutboxEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\xdc\x01\n" +
	"\x11OutboxEventStatus\x12#\n" +
	"\x1fOUTBOX_EVENT_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bOUTBOX_EVENT_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dOUTBOX_EVENT_STATUS_PUBLISHED\x10\x02\x12\x1e\n" +
	"\x1aOUTBOX_EVENT_STATUS_FAILED\x10\x03\x12 \n" +
	"\x1cOUTBOX_EVENT_STATUS_RETRYING\x10\x04\x12\x1c\n" +
	"\x18OUTBOX_EVENT_STATUS_DEAD\x10\x052\xdb\x01\n" +
	"\rOutboxService\x12a\n" +
	"\x0eGetOutboxEvent\x12&.billing_service.GetOutboxEventRequest\x1a'.billing_service.GetOutboxEventResponse\x12g\n" +
	"\x10ListOutboxEvents\x12(.billing_service.ListOutboxEventsRequest\x1a).billing_service.ListOutboxEventsResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_outbox_events_proto_rawDescOnce sync.Once
	file_billing_service_outbox_events_proto_rawDescData []byte
)

func file_billing_service_outbox_events_proto_rawDescGZIP() []byte {
	file_billing_service_outbox_events_proto_rawDescOnce.Do(func() {
		file_billing_service_outbox_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_outbox_events_proto_rawDesc), len(file_billing_service_outbox_events_proto_rawDesc)))
	})
	return file_billing_service_outbox_events_proto_rawDescData
}

var file_billing_service_outbox_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_service_outbox_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_billing_service_outbox_events_proto_goTypes = []any{
	(OutboxEventStatus)(0),           // 0: billing_service.OutboxEventStatus
	(*OutboxEvent)(nil),              // 1: billing_service.OutboxEvent
	(*GetOutboxEventRequest)(nil),    // 2: billing_service.GetOutboxEventRequest
	(*GetOutboxEventResponse)(nil),   // 3: billing_service.GetOutboxEventResponse
	(*ListOutboxEventsRequest)(nil),  // 4: billing_service.ListOutboxEventsRequest
	(*ListOutboxEventsResponse)(nil), // 5: billing_service.ListOutboxEventsResponse
	(*structpb.Struct)(nil),          // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_billing_service_outbox_events_proto_depIdxs = []int32{
	6,  // 0: billing_service.OutboxEvent.payload:type_name -> google.protobuf.Struct
	0,  // 1: billing_service.OutboxEvent.status:type_name -> billing_service.OutboxEventStatus
	7,  // 2: billing_service.OutboxEvent.next_retry_at:type_name -> google.protobuf.Timestamp
	7,  // 3: billing_service.OutboxEvent.published_at:type_name -> google.protobuf.Timestamp
	7,  // 4: billing_service.OutboxEvent.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: billing_service.GetOutboxEventResponse.event:type_name -> billing_service.OutboxEvent
	0,  // 6: billing_service.ListOutboxEventsRequest.status:type_name -> billing_service.OutboxEventStatus
	1,  // 7: billing_service.ListOutboxEventsResponse.events:type_name -> billing_service.OutboxEvent
	2,  // 8: billing_service.OutboxService.GetOutboxEvent:input_type -> billing_service.GetOutboxEventRequest
	4,  // 9: billing_service.OutboxService.ListOutboxEvents:input_type -> billing_service.ListOutboxEventsRequest
	3,  // 10: billing_service.OutboxService.GetOutboxEvent:output_type -> billing_service.GetOutboxEventResponse
	5,  // 11: billing_service.OutboxService.ListOutboxEvents:output_type -> billing_service.ListOutboxEventsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_billing_service_outbox_events_proto_init() }
func file_billing_service_outbox_events_proto_init() {
	if File_billing_service_outbox_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_outbox_events_proto_rawDesc), len(file_billing_service_outbox_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_outbox_events_proto_goTypes,
		DependencyIndexes: file_billing_service_outbox_events_proto_depIdxs,
		EnumInfos:         file_billing_service_outbox_events_proto_enumTypes,
		MessageInfos:      file_billing_service_outbox_events_proto_msgTypes,
	}.Build()
	File_billing_service_outbox_events_proto = out.File
	file_billing_service_outbox_events_proto_goTypes = nil
	file_billing_service_outbox_events_proto_depIdxs = nil
}
