// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/payment_attempts.proto

package billing_service

import (
	common "github.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentAttemptStatus tracks the lifecycle of a payment attempt with a specific provider.
// A purchase may have multiple payment attempts across different providers or retries.
type PaymentAttemptStatus int32

const (
	// Unspecified status; should not be used
	PaymentAttemptStatus_PAYMENT_ATTEMPT_STATUS_UNSPECIFIED PaymentAttemptStatus = 0
	// Payment attempt has been created but not yet sent to payment gateway
	PaymentAttemptStatus_PAYMENT_ATTEMPT_STATUS_CREATED PaymentAttemptStatus = 1
	// Payment attempt is in progress (e.g., awaiting user confirmation on payment gateway)
	PaymentAttemptStatus_PAYMENT_ATTEMPT_STATUS_PENDING PaymentAttemptStatus = 2
	// Payment attempt succeeded and payment was captured
	PaymentAttemptStatus_PAYMENT_ATTEMPT_STATUS_SUCCEEDED PaymentAttemptStatus = 3
	// Payment attempt failed; may be retried with same or different provider
	PaymentAttemptStatus_PAYMENT_ATTEMPT_STATUS_FAILED PaymentAttemptStatus = 4
	// Payment attempt expired before completion (e.g., checkout link timed out)
	PaymentAttemptStatus_PAYMENT_ATTEMPT_STATUS_EXPIRED PaymentAttemptStatus = 5
	// Payment attempt was canceled by user (switching payment method) or system
	PaymentAttemptStatus_PAYMENT_ATTEMPT_STATUS_CANCELED PaymentAttemptStatus = 6
)

// Enum value maps for PaymentAttemptStatus.
var (
	PaymentAttemptStatus_name = map[int32]string{
		0: "PAYMENT_ATTEMPT_STATUS_UNSPECIFIED",
		1: "PAYMENT_ATTEMPT_STATUS_CREATED",
		2: "PAYMENT_ATTEMPT_STATUS_PENDING",
		3: "PAYMENT_ATTEMPT_STATUS_SUCCEEDED",
		4: "PAYMENT_ATTEMPT_STATUS_FAILED",
		5: "PAYMENT_ATTEMPT_STATUS_EXPIRED",
		6: "PAYMENT_ATTEMPT_STATUS_CANCELED",
	}
	PaymentAttemptStatus_value = map[string]int32{
		"PAYMENT_ATTEMPT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_ATTEMPT_STATUS_CREATED":     1,
		"PAYMENT_ATTEMPT_STATUS_PENDING":     2,
		"PAYMENT_ATTEMPT_STATUS_SUCCEEDED":   3,
		"PAYMENT_ATTEMPT_STATUS_FAILED":      4,
		"PAYMENT_ATTEMPT_STATUS_EXPIRED":     5,
		"PAYMENT_ATTEMPT_STATUS_CANCELED":    6,
	}
)

func (x PaymentAttemptStatus) Enum() *PaymentAttemptStatus {
	p := new(PaymentAttemptStatus)
	*p = x
	return p
}

func (x PaymentAttemptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentAttemptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_service_payment_attempts_proto_enumTypes[0].Descriptor()
}

func (PaymentAttemptStatus) Type() protoreflect.EnumType {
	return &file_billing_service_payment_attempts_proto_enumTypes[0]
}

func (x PaymentAttemptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentAttemptStatus.Descriptor instead.
func (PaymentAttemptStatus) EnumDescriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{0}
}

type PaymentAttempt struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PurchaseId            string                 `protobuf:"bytes,2,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	Provider              string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"` // "stripe", "momo", "zalopay"
	Status                PaymentAttemptStatus   `protobuf:"varint,4,opt,name=status,proto3,enum=billing_service.PaymentAttemptStatus" json:"status,omitempty"`
	Amount                *Money                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ProviderTransactionId string                 `protobuf:"bytes,6,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"` // session/order id
	CheckoutUrl           string                 `protobuf:"bytes,7,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	ProviderMetadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=provider_metadata,json=providerMetadata,proto3" json:"provider_metadata,omitempty"`
	ExpiresAt             *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PaymentAttempt) Reset() {
	*x = PaymentAttempt{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAttempt) ProtoMessage() {}

func (x *PaymentAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAttempt.ProtoReflect.Descriptor instead.
func (*PaymentAttempt) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentAttempt) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *PaymentAttempt) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentAttempt) GetStatus() PaymentAttemptStatus {
	if x != nil {
		return x.Status
	}
	return PaymentAttemptStatus_PAYMENT_ATTEMPT_STATUS_UNSPECIFIED
}

func (x *PaymentAttempt) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentAttempt) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

func (x *PaymentAttempt) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *PaymentAttempt) GetProviderMetadata() *structpb.Struct {
	if x != nil {
		return x.ProviderMetadata
	}
	return nil
}

func (x *PaymentAttempt) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PaymentAttempt) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PaymentAttempt) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePaymentAttemptRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	// Which provider to use for this attempt ("momo", "zalopay", "stripe", ...)
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// Optional: specify amounts if you allow partial payments; otherwise server
	// should take from purchase.amount.
	Amount *Money `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Extra provider-specific options (return URLs, locale, bank code, etc.)
	ProviderOptions *structpb.Struct `protobuf:"bytes,4,opt,name=provider_options,json=providerOptions,proto3" json:"provider_options,omitempty"`
	// Recommended: idempotency key for attempt creation
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentAttemptRequest) Reset() {
	*x = CreatePaymentAttemptRequest{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentAttemptRequest) ProtoMessage() {}

func (x *CreatePaymentAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentAttemptRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentAttemptRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentAttemptRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *CreatePaymentAttemptRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreatePaymentAttemptRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreatePaymentAttemptRequest) GetProviderOptions() *structpb.Struct {
	if x != nil {
		return x.ProviderOptions
	}
	return nil
}

func (x *CreatePaymentAttemptRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreatePaymentAttemptResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *common.OperationMetadata `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentAttemptResponse) Reset() {
	*x = CreatePaymentAttemptResponse{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentAttemptResponse) ProtoMessage() {}

func (x *CreatePaymentAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentAttemptResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentAttemptResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentAttemptResponse) GetData() *common.OperationMetadata {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPaymentAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentAttemptRequest) Reset() {
	*x = GetPaymentAttemptRequest{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentAttemptRequest) ProtoMessage() {}

func (x *GetPaymentAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentAttemptRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentAttemptRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentAttemptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPaymentAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *PaymentAttempt        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentAttemptResponse) Reset() {
	*x = GetPaymentAttemptResponse{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentAttemptResponse) ProtoMessage() {}

func (x *GetPaymentAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentAttemptResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentAttemptResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentAttemptResponse) GetData() *PaymentAttempt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListPaymentAttemptsByPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentAttemptsByPurchaseRequest) Reset() {
	*x = ListPaymentAttemptsByPurchaseRequest{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentAttemptsByPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentAttemptsByPurchaseRequest) ProtoMessage() {}

func (x *ListPaymentAttemptsByPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentAttemptsByPurchaseRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentAttemptsByPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{5}
}

func (x *ListPaymentAttemptsByPurchaseRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type ListPaymentAttemptsByPurchaseResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*PaymentAttempt          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentAttemptsByPurchaseResponse) Reset() {
	*x = ListPaymentAttemptsByPurchaseResponse{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentAttemptsByPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentAttemptsByPurchaseResponse) ProtoMessage() {}

func (x *ListPaymentAttemptsByPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentAttemptsByPurchaseResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentAttemptsByPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{6}
}

func (x *ListPaymentAttemptsByPurchaseResponse) GetData() []*PaymentAttempt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPaymentAttemptsByPurchaseResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Initiate a refund for a specific purchase.
// Server should:
// - locate successful attempt(s) for that purchase,
// - pick the capture transaction(s),
// - call provider API,
// - record refund transaction(s).
type RefundPurchaseRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	// If empty => full refund (server decides amount)
	// If set => partial refund (must be <= captured - already_refunded)
	Amount *Money `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Optional free-form reason
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Idempotency for refund requests
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Optional: force a particular provider rail.
	// If set, server must ensure the purchase was paid via this provider, otherwise error.
	Provider      string `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPurchaseRequest) Reset() {
	*x = RefundPurchaseRequest{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPurchaseRequest) ProtoMessage() {}

func (x *RefundPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPurchaseRequest.ProtoReflect.Descriptor instead.
func (*RefundPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{7}
}

func (x *RefundPurchaseRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *RefundPurchaseRequest) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *RefundPurchaseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RefundPurchaseRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RefundPurchaseRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type RefundPurchaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The refund transaction(s) created as a result.
	// Some providers may create multiple records (fees, partials, etc.)
	Data          []*PaymentTransaction `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPurchaseResponse) Reset() {
	*x = RefundPurchaseResponse{}
	mi := &file_billing_service_payment_attempts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPurchaseResponse) ProtoMessage() {}

func (x *RefundPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_attempts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPurchaseResponse.ProtoReflect.Descriptor instead.
func (*RefundPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_attempts_proto_rawDescGZIP(), []int{8}
}

func (x *RefundPurchaseResponse) GetData() []*PaymentTransaction {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_billing_service_payment_attempts_proto protoreflect.FileDescriptor

const file_billing_service_payment_attempts_proto_rawDesc = "" +
	"\n" +
	"&billing_service/payment_attempts.proto\x12\x0fbilling_service\x1a\x1dbilling_service/billing.proto\x1a*billing_service/payment_transactions.proto\x1a\x17common/pagination.proto\x1a\x15common/response.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x04\n" +
	"\x0ePaymentAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpurchase_id\x18\x02 \x01(\tR\n" +
	"purchaseId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12=\n" +
	"\x06status\x18\x04 \x01(\x0e2%.billing_service.PaymentAttemptStatusR\x06status\x12.\n" +
	"\x06amount\x18\x05 \x01(\v2\x16.billing_service.MoneyR\x06amount\x126\n" +
	"\x17provider_transaction_id\x18\x06 \x01(\tR\x15providerTransactionId\x12!\n" +
	"\fcheckout_url\x18\a \x01(\tR\vcheckoutUrl\x12D\n" +
	"\x11provider_metadata\x18\b \x01(\v2\x17.google.protobuf.StructR\x10providerMetadata\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf7\x01\n" +
	"\x1bCreatePaymentAttemptRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12.\n" +
	"\x06amount\x18\x03 \x01(\v2\x16.billing_service.MoneyR\x06amount\x12B\n" +
	"\x10provider_options\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0fproviderOptions\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"M\n" +
	"\x1cCreatePaymentAttemptResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.common.OperationMetadataR\x04data\"*\n" +
	"\x18GetPaymentAttemptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x19GetPaymentAttemptResponse\x123\n" +
	"\x04data\x18\x01 \x01(\v2\x1f.billing_service.PaymentAttemptR\x04data\"G\n" +
	"$ListPaymentAttemptsByPurchaseRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"\x98\x01\n" +
	"%ListPaymentAttemptsByPurchaseResponse\x123\n" +
	"\x04data\x18\x01 \x03(\v2\x1f.billing_service.PaymentAttemptR\x04data\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination\"\xc5\x01\n" +
	"\x15RefundPurchaseRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\x12.\n" +
	"\x06amount\x18\x02 \x01(\v2\x16.billing_service.MoneyR\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\"Q\n" +
	"\x16RefundPurchaseResponse\x127\n" +
	"\x04data\x18\x01 \x03(\v2#.billing_service.PaymentTransactionR\x04data*\x98\x02\n" +
	"\x14PaymentAttemptStatus\x12&\n" +
	"\"PAYMENT_ATTEMPT_STATUS_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1ePAYMENT_ATTEMPT_STATUS_CREATED\x10\x01\x12\"\n" +
	"\x1ePAYMENT_ATTEMPT_STATUS_PENDING\x10\x02\x12$\n" +
	" PAYMENT_ATTEMPT_STATUS_SUCCEEDED\x10\x03\x12!\n" +
	"\x1dPAYMENT_ATTEMPT_STATUS_FAILED\x10\x04\x12\"\n" +
	"\x1ePAYMENT_ATTEMPT_STATUS_EXPIRED\x10\x05\x12#\n" +
	"\x1fPAYMENT_ATTEMPT_STATUS_CANCELED\x10\x062\xe5\x03\n" +
	"\x0ePaymentService\x12s\n" +
	"\x14CreatePaymentAttempt\x12,.billing_service.CreatePaymentAttemptRequest\x1a-.billing_service.CreatePaymentAttemptResponse\x12j\n" +
	"\x11GetPaymentAttempt\x12).billing_service.GetPaymentAttemptRequest\x1a*.billing_service.GetPaymentAttemptResponse\x12\x8e\x01\n" +
	"\x1dListPaymentAttemptsByPurchase\x125.billing_service.ListPaymentAttemptsByPurchaseRequest\x1a6.billing_service.ListPaymentAttemptsByPurchaseResponse\x12a\n" +
	"\x0eRefundPurchase\x12&.billing_service.RefundPurchaseRequest\x1a'.billing_service.RefundPurchaseResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_payment_attempts_proto_rawDescOnce sync.Once
	file_billing_service_payment_attempts_proto_rawDescData []byte
)

func file_billing_service_payment_attempts_proto_rawDescGZIP() []byte {
	file_billing_service_payment_attempts_proto_rawDescOnce.Do(func() {
		file_billing_service_payment_attempts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_payment_attempts_proto_rawDesc), len(file_billing_service_payment_attempts_proto_rawDesc)))
	})
	return file_billing_service_payment_attempts_proto_rawDescData
}

var file_billing_service_payment_attempts_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_service_payment_attempts_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_billing_service_payment_attempts_proto_goTypes = []any{
	(PaymentAttemptStatus)(0),                     // 0: billing_service.PaymentAttemptStatus
	(*PaymentAttempt)(nil),                        // 1: billing_service.PaymentAttempt
	(*CreatePaymentAttemptRequest)(nil),           // 2: billing_service.CreatePaymentAttemptRequest
	(*CreatePaymentAttemptResponse)(nil),          // 3: billing_service.CreatePaymentAttemptResponse
	(*GetPaymentAttemptRequest)(nil),              // 4: billing_service.GetPaymentAttemptRequest
	(*GetPaymentAttemptResponse)(nil),             // 5: billing_service.GetPaymentAttemptResponse
	(*ListPaymentAttemptsByPurchaseRequest)(nil),  // 6: billing_service.ListPaymentAttemptsByPurchaseRequest
	(*ListPaymentAttemptsByPurchaseResponse)(nil), // 7: billing_service.ListPaymentAttemptsByPurchaseResponse
	(*RefundPurchaseRequest)(nil),                 // 8: billing_service.RefundPurchaseRequest
	(*RefundPurchaseResponse)(nil),                // 9: billing_service.RefundPurchaseResponse
	(*Money)(nil),                                 // 10: billing_service.Money
	(*structpb.Struct)(nil),                       // 11: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),                 // 12: google.protobuf.Timestamp
	(*common.OperationMetadata)(nil),              // 13: common.OperationMetadata
	(*common.PaginationMetadata)(nil),             // 14: common.PaginationMetadata
	(*PaymentTransaction)(nil),                    // 15: billing_service.PaymentTransaction
}
var file_billing_service_payment_attempts_proto_depIdxs = []int32{
	0,  // 0: billing_service.PaymentAttempt.status:type_name -> billing_service.PaymentAttemptStatus
	10, // 1: billing_service.PaymentAttempt.amount:type_name -> billing_service.Money
	11, // 2: billing_service.PaymentAttempt.provider_metadata:type_name -> google.protobuf.Struct
	12, // 3: billing_service.PaymentAttempt.expires_at:type_name -> google.protobuf.Timestamp
	12, // 4: billing_service.PaymentAttempt.created_at:type_name -> google.protobuf.Timestamp
	12, // 5: billing_service.PaymentAttempt.updated_at:type_name -> google.protobuf.Timestamp
	10, // 6: billing_service.CreatePaymentAttemptRequest.amount:type_name -> billing_service.Money
	11, // 7: billing_service.CreatePaymentAttemptRequest.provider_options:type_name -> google.protobuf.Struct
	13, // 8: billing_service.CreatePaymentAttemptResponse.data:type_name -> common.OperationMetadata
	1,  // 9: billing_service.GetPaymentAttemptResponse.data:type_name -> billing_service.PaymentAttempt
	1,  // 10: billing_service.ListPaymentAttemptsByPurchaseResponse.data:type_name -> billing_service.PaymentAttempt
	14, // 11: billing_service.ListPaymentAttemptsByPurchaseResponse.pagination:type_name -> common.PaginationMetadata
	10, // 12: billing_service.RefundPurchaseRequest.amount:type_name -> billing_service.Money
	15, // 13: billing_service.RefundPurchaseResponse.data:type_name -> billing_service.PaymentTransaction
	2,  // 14: billing_service.PaymentService.CreatePaymentAttempt:input_type -> billing_service.CreatePaymentAttemptRequest
	4,  // 15: billing_service.PaymentService.GetPaymentAttempt:input_type -> billing_service.GetPaymentAttemptRequest
	6,  // 16: billing_service.PaymentService.ListPaymentAttemptsByPurchase:input_type -> billing_service.ListPaymentAttemptsByPurchaseRequest
	8,  // 17: billing_service.PaymentService.RefundPurchase:input_type -> billing_service.RefundPurchaseRequest
	3,  // 18: billing_service.PaymentService.CreatePaymentAttempt:output_type -> billing_service.CreatePaymentAttemptResponse
	5,  // 19: billing_service.PaymentService.GetPaymentAttempt:output_type -> billing_service.GetPaymentAttemptResponse
	7,  // 20: billing_service.PaymentService.ListPaymentAttemptsByPurchase:output_type -> billing_service.ListPaymentAttemptsByPurchaseResponse
	9,  // 21: billing_service.PaymentService.RefundPurchase:output_type -> billing_service.RefundPurchaseResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_billing_service_payment_attempts_proto_init() }
func file_billing_service_payment_attempts_proto_init() {
	if File_billing_service_payment_attempts_proto != nil {
		return
	}
	file_billing_service_billing_proto_init()
	file_billing_service_payment_transactions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_payment_attempts_proto_rawDesc), len(file_billing_service_payment_attempts_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_payment_attempts_proto_goTypes,
		DependencyIndexes: file_billing_service_payment_attempts_proto_depIdxs,
		EnumInfos:         file_billing_service_payment_attempts_proto_enumTypes,
		MessageInfos:      file_billing_service_payment_attempts_proto_msgTypes,
	}.Build()
	File_billing_service_payment_attempts_proto = out.File
	file_billing_service_payment_attempts_proto_goTypes = nil
	file_billing_service_payment_attempts_proto_depIdxs = nil
}
