// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: billing_service/payment_attempts.proto

package billing_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_CreatePaymentAttempt_FullMethodName          = "/billing_service.PaymentService/CreatePaymentAttempt"
	PaymentService_GetPaymentAttempt_FullMethodName             = "/billing_service.PaymentService/GetPaymentAttempt"
	PaymentService_ListPaymentAttemptsByPurchase_FullMethodName = "/billing_service.PaymentService/ListPaymentAttemptsByPurchase"
	PaymentService_RefundPurchase_FullMethodName                = "/billing_service.PaymentService/RefundPurchase"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreatePaymentAttempt(ctx context.Context, in *CreatePaymentAttemptRequest, opts ...grpc.CallOption) (*CreatePaymentAttemptResponse, error)
	GetPaymentAttempt(ctx context.Context, in *GetPaymentAttemptRequest, opts ...grpc.CallOption) (*GetPaymentAttemptResponse, error)
	ListPaymentAttemptsByPurchase(ctx context.Context, in *ListPaymentAttemptsByPurchaseRequest, opts ...grpc.CallOption) (*ListPaymentAttemptsByPurchaseResponse, error)
	RefundPurchase(ctx context.Context, in *RefundPurchaseRequest, opts ...grpc.CallOption) (*RefundPurchaseResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreatePaymentAttempt(ctx context.Context, in *CreatePaymentAttemptRequest, opts ...grpc.CallOption) (*CreatePaymentAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentAttemptResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreatePaymentAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentAttempt(ctx context.Context, in *GetPaymentAttemptRequest, opts ...grpc.CallOption) (*GetPaymentAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentAttemptResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPaymentAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListPaymentAttemptsByPurchase(ctx context.Context, in *ListPaymentAttemptsByPurchaseRequest, opts ...grpc.CallOption) (*ListPaymentAttemptsByPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentAttemptsByPurchaseResponse)
	err := c.cc.Invoke(ctx, PaymentService_ListPaymentAttemptsByPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) RefundPurchase(ctx context.Context, in *RefundPurchaseRequest, opts ...grpc.CallOption) (*RefundPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundPurchaseResponse)
	err := c.cc.Invoke(ctx, PaymentService_RefundPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations should embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	CreatePaymentAttempt(context.Context, *CreatePaymentAttemptRequest) (*CreatePaymentAttemptResponse, error)
	GetPaymentAttempt(context.Context, *GetPaymentAttemptRequest) (*GetPaymentAttemptResponse, error)
	ListPaymentAttemptsByPurchase(context.Context, *ListPaymentAttemptsByPurchaseRequest) (*ListPaymentAttemptsByPurchaseResponse, error)
	RefundPurchase(context.Context, *RefundPurchaseRequest) (*RefundPurchaseResponse, error)
}

// UnimplementedPaymentServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreatePaymentAttempt(context.Context, *CreatePaymentAttemptRequest) (*CreatePaymentAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentAttempt not implemented")
}
func (UnimplementedPaymentServiceServer) GetPaymentAttempt(context.Context, *GetPaymentAttemptRequest) (*GetPaymentAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentAttempt not implemented")
}
func (UnimplementedPaymentServiceServer) ListPaymentAttemptsByPurchase(context.Context, *ListPaymentAttemptsByPurchaseRequest) (*ListPaymentAttemptsByPurchaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPaymentAttemptsByPurchase not implemented")
}
func (UnimplementedPaymentServiceServer) RefundPurchase(context.Context, *RefundPurchaseRequest) (*RefundPurchaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundPurchase not implemented")
}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue() {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreatePaymentAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePaymentAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreatePaymentAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePaymentAttempt(ctx, req.(*CreatePaymentAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPaymentAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentAttempt(ctx, req.(*GetPaymentAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListPaymentAttemptsByPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentAttemptsByPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListPaymentAttemptsByPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ListPaymentAttemptsByPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListPaymentAttemptsByPurchase(ctx, req.(*ListPaymentAttemptsByPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_RefundPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).RefundPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_RefundPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).RefundPurchase(ctx, req.(*RefundPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing_service.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePaymentAttempt",
			Handler:    _PaymentService_CreatePaymentAttempt_Handler,
		},
		{
			MethodName: "GetPaymentAttempt",
			Handler:    _PaymentService_GetPaymentAttempt_Handler,
		},
		{
			MethodName: "ListPaymentAttemptsByPurchase",
			Handler:    _PaymentService_ListPaymentAttemptsByPurchase_Handler,
		},
		{
			MethodName: "RefundPurchase",
			Handler:    _PaymentService_RefundPurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_service/payment_attempts.proto",
}
