// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/payment_transactions.proto

package billing_service

import (
	common "github.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentTransactionType int32

const (
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_UNSPECIFIED PaymentTransactionType = 0
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_PAYMENT     PaymentTransactionType = 1
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_AUTH        PaymentTransactionType = 2
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_CAPTURE     PaymentTransactionType = 3
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_REFUND      PaymentTransactionType = 4
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_VOID        PaymentTransactionType = 5
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_CHARGEBACK  PaymentTransactionType = 6
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_ADJUSTMENT  PaymentTransactionType = 7
	PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_FEE         PaymentTransactionType = 8
)

// Enum value maps for PaymentTransactionType.
var (
	PaymentTransactionType_name = map[int32]string{
		0: "PAYMENT_TRANSACTION_TYPE_UNSPECIFIED",
		1: "PAYMENT_TRANSACTION_TYPE_PAYMENT",
		2: "PAYMENT_TRANSACTION_TYPE_AUTH",
		3: "PAYMENT_TRANSACTION_TYPE_CAPTURE",
		4: "PAYMENT_TRANSACTION_TYPE_REFUND",
		5: "PAYMENT_TRANSACTION_TYPE_VOID",
		6: "PAYMENT_TRANSACTION_TYPE_CHARGEBACK",
		7: "PAYMENT_TRANSACTION_TYPE_ADJUSTMENT",
		8: "PAYMENT_TRANSACTION_TYPE_FEE",
	}
	PaymentTransactionType_value = map[string]int32{
		"PAYMENT_TRANSACTION_TYPE_UNSPECIFIED": 0,
		"PAYMENT_TRANSACTION_TYPE_PAYMENT":     1,
		"PAYMENT_TRANSACTION_TYPE_AUTH":        2,
		"PAYMENT_TRANSACTION_TYPE_CAPTURE":     3,
		"PAYMENT_TRANSACTION_TYPE_REFUND":      4,
		"PAYMENT_TRANSACTION_TYPE_VOID":        5,
		"PAYMENT_TRANSACTION_TYPE_CHARGEBACK":  6,
		"PAYMENT_TRANSACTION_TYPE_ADJUSTMENT":  7,
		"PAYMENT_TRANSACTION_TYPE_FEE":         8,
	}
)

func (x PaymentTransactionType) Enum() *PaymentTransactionType {
	p := new(PaymentTransactionType)
	*p = x
	return p
}

func (x PaymentTransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentTransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_service_payment_transactions_proto_enumTypes[0].Descriptor()
}

func (PaymentTransactionType) Type() protoreflect.EnumType {
	return &file_billing_service_payment_transactions_proto_enumTypes[0]
}

func (x PaymentTransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentTransactionType.Descriptor instead.
func (PaymentTransactionType) EnumDescriptor() ([]byte, []int) {
	return file_billing_service_payment_transactions_proto_rawDescGZIP(), []int{0}
}

type PaymentTransactionStatus int32

const (
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_UNSPECIFIED PaymentTransactionStatus = 0
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_PENDING     PaymentTransactionStatus = 1
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_SUCCEEDED   PaymentTransactionStatus = 2
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_FAILED      PaymentTransactionStatus = 3
	PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_CANCELED    PaymentTransactionStatus = 4
)

// Enum value maps for PaymentTransactionStatus.
var (
	PaymentTransactionStatus_name = map[int32]string{
		0: "PAYMENT_TRANSACTION_STATUS_UNSPECIFIED",
		1: "PAYMENT_TRANSACTION_STATUS_PENDING",
		2: "PAYMENT_TRANSACTION_STATUS_SUCCEEDED",
		3: "PAYMENT_TRANSACTION_STATUS_FAILED",
		4: "PAYMENT_TRANSACTION_STATUS_CANCELED",
	}
	PaymentTransactionStatus_value = map[string]int32{
		"PAYMENT_TRANSACTION_STATUS_UNSPECIFIED": 0,
		"PAYMENT_TRANSACTION_STATUS_PENDING":     1,
		"PAYMENT_TRANSACTION_STATUS_SUCCEEDED":   2,
		"PAYMENT_TRANSACTION_STATUS_FAILED":      3,
		"PAYMENT_TRANSACTION_STATUS_CANCELED":    4,
	}
)

func (x PaymentTransactionStatus) Enum() *PaymentTransactionStatus {
	p := new(PaymentTransactionStatus)
	*p = x
	return p
}

func (x PaymentTransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentTransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_service_payment_transactions_proto_enumTypes[1].Descriptor()
}

func (PaymentTransactionStatus) Type() protoreflect.EnumType {
	return &file_billing_service_payment_transactions_proto_enumTypes[1]
}

func (x PaymentTransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentTransactionStatus.Descriptor instead.
func (PaymentTransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_billing_service_payment_transactions_proto_rawDescGZIP(), []int{1}
}

type PaymentTransaction struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Id                string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentAttemptId  string                   `protobuf:"bytes,2,opt,name=payment_attempt_id,json=paymentAttemptId,proto3" json:"payment_attempt_id,omitempty"`
	Type              PaymentTransactionType   `protobuf:"varint,3,opt,name=type,proto3,enum=billing_service.PaymentTransactionType" json:"type,omitempty"`
	Status            PaymentTransactionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=billing_service.PaymentTransactionStatus" json:"status,omitempty"`
	Amount            *Money                   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ProviderReference string                   `protobuf:"bytes,6,opt,name=provider_reference,json=providerReference,proto3" json:"provider_reference,omitempty"`
	Metadata          *structpb.Struct         `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProcessedAt       *timestamppb.Timestamp   `protobuf:"bytes,8,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentTransaction) Reset() {
	*x = PaymentTransaction{}
	mi := &file_billing_service_payment_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentTransaction) ProtoMessage() {}

func (x *PaymentTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentTransaction.ProtoReflect.Descriptor instead.
func (*PaymentTransaction) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentTransaction) GetPaymentAttemptId() string {
	if x != nil {
		return x.PaymentAttemptId
	}
	return ""
}

func (x *PaymentTransaction) GetType() PaymentTransactionType {
	if x != nil {
		return x.Type
	}
	return PaymentTransactionType_PAYMENT_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *PaymentTransaction) GetStatus() PaymentTransactionStatus {
	if x != nil {
		return x.Status
	}
	return PaymentTransactionStatus_PAYMENT_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *PaymentTransaction) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentTransaction) GetProviderReference() string {
	if x != nil {
		return x.ProviderReference
	}
	return ""
}

func (x *PaymentTransaction) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PaymentTransaction) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *PaymentTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListPaymentTransactionsByPurchaseRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PurchaseId    string                   `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	Query         *common.ListQueryRequest `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentTransactionsByPurchaseRequest) Reset() {
	*x = ListPaymentTransactionsByPurchaseRequest{}
	mi := &file_billing_service_payment_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentTransactionsByPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentTransactionsByPurchaseRequest) ProtoMessage() {}

func (x *ListPaymentTransactionsByPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentTransactionsByPurchaseRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentTransactionsByPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *ListPaymentTransactionsByPurchaseRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *ListPaymentTransactionsByPurchaseRequest) GetQuery() *common.ListQueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListPaymentTransactionsByPurchaseResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Transactions  []*PaymentTransaction      `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentTransactionsByPurchaseResponse) Reset() {
	*x = ListPaymentTransactionsByPurchaseResponse{}
	mi := &file_billing_service_payment_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentTransactionsByPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentTransactionsByPurchaseResponse) ProtoMessage() {}

func (x *ListPaymentTransactionsByPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentTransactionsByPurchaseResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentTransactionsByPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *ListPaymentTransactionsByPurchaseResponse) GetTransactions() []*PaymentTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListPaymentTransactionsByPurchaseResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPaymentTransactionsByAttemptRequest struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	PaymentAttemptId string                   `protobuf:"bytes,1,opt,name=payment_attempt_id,json=paymentAttemptId,proto3" json:"payment_attempt_id,omitempty"`
	Query            *common.ListQueryRequest `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListPaymentTransactionsByAttemptRequest) Reset() {
	*x = ListPaymentTransactionsByAttemptRequest{}
	mi := &file_billing_service_payment_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentTransactionsByAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentTransactionsByAttemptRequest) ProtoMessage() {}

func (x *ListPaymentTransactionsByAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentTransactionsByAttemptRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentTransactionsByAttemptRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *ListPaymentTransactionsByAttemptRequest) GetPaymentAttemptId() string {
	if x != nil {
		return x.PaymentAttemptId
	}
	return ""
}

func (x *ListPaymentTransactionsByAttemptRequest) GetQuery() *common.ListQueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListPaymentTransactionsByAttemptResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Transactions  []*PaymentTransaction      `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentTransactionsByAttemptResponse) Reset() {
	*x = ListPaymentTransactionsByAttemptResponse{}
	mi := &file_billing_service_payment_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentTransactionsByAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentTransactionsByAttemptResponse) ProtoMessage() {}

func (x *ListPaymentTransactionsByAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_payment_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentTransactionsByAttemptResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentTransactionsByAttemptResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_payment_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *ListPaymentTransactionsByAttemptResponse) GetTransactions() []*PaymentTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListPaymentTransactionsByAttemptResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_billing_service_payment_transactions_proto protoreflect.FileDescriptor

const file_billing_service_payment_transactions_proto_rawDesc = "" +
	"\n" +
	"*billing_service/payment_transactions.proto\x12\x0fbilling_service\x1a\x1dbilling_service/billing.proto\x1a\x17common/pagination.proto\x1a\x14common/request.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x03\n" +
	"\x12PaymentTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12payment_attempt_id\x18\x02 \x01(\tR\x10paymentAttemptId\x12;\n" +
	"\x04type\x18\x03 \x01(\x0e2'.billing_service.PaymentTransactionTypeR\x04type\x12A\n" +
	"\x06status\x18\x04 \x01(\x0e2).billing_service.PaymentTransactionStatusR\x06status\x12.\n" +
	"\x06amount\x18\x05 \x01(\v2\x16.billing_service.MoneyR\x06amount\x12-\n" +
	"\x12provider_reference\x18\x06 \x01(\tR\x11providerReference\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12=\n" +
	"\fprocessed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n" +
	"(ListPaymentTransactionsByPurchaseRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\x12.\n" +
	"\x05query\x18\x02 \x01(\v2\x18.common.ListQueryRequestR\x05query\"\xb0\x01\n" +
	")ListPaymentTransactionsByPurchaseResponse\x12G\n" +
	"\ftransactions\x18\x01 \x03(\v2#.billing_service.PaymentTransactionR\ftransactions\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination\"\x87\x01\n" +
	"'ListPaymentTransactionsByAttemptRequest\x12,\n" +
	"\x12payment_attempt_id\x18\x01 \x01(\tR\x10paymentAttemptId\x12.\n" +
	"\x05query\x18\x02 \x01(\v2\x18.common.ListQueryRequestR\x05query\"\xaf\x01\n" +
	"(ListPaymentTransactionsByAttemptResponse\x12G\n" +
	"\ftransactions\x18\x01 \x03(\v2#.billing_service.PaymentTransactionR\ftransactions\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination*\xed\x02\n" +
	"\x16PaymentTransactionType\x12(\n" +
	"$PAYMENT_TRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" PAYMENT_TRANSACTION_TYPE_PAYMENT\x10\x01\x12!\n" +
	"\x1dPAYMENT_TRANSACTION_TYPE_AUTH\x10\x02\x12$\n" +
	" PAYMENT_TRANSACTION_TYPE_CAPTURE\x10\x03\x12#\n" +
	"\x1fPAYMENT_TRANSACTION_TYPE_REFUND\x10\x04\x12!\n" +
	"\x1dPAYMENT_TRANSACTION_TYPE_VOID\x10\x05\x12'\n" +
	"#PAYMENT_TRANSACTION_TYPE_CHARGEBACK\x10\x06\x12'\n" +
	"#PAYMENT_TRANSACTION_TYPE_ADJUSTMENT\x10\a\x12 \n" +
	"\x1cPAYMENT_TRANSACTION_TYPE_FEE\x10\b*\xe8\x01\n" +
	"\x18PaymentTransactionStatus\x12*\n" +
	"&PAYMENT_TRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"PAYMENT_TRANSACTION_STATUS_PENDING\x10\x01\x12(\n" +
	"$PAYMENT_TRANSACTION_STATUS_SUCCEEDED\x10\x02\x12%\n" +
	"!PAYMENT_TRANSACTION_STATUS_FAILED\x10\x03\x12'\n" +
	"#PAYMENT_TRANSACTION_STATUS_CANCELED\x10\x042\xac\x02\n" +
	"\x19PaymentTransactionService\x12\x87\x01\n" +
	"\x0eListByPurchase\x129.billing_service.ListPaymentTransactionsByPurchaseRequest\x1a:.billing_service.ListPaymentTransactionsByPurchaseResponse\x12\x84\x01\n" +
	"\rListByAttempt\x128.billing_service.ListPaymentTransactionsByAttemptRequest\x1a9.billing_service.ListPaymentTransactionsByAttemptResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_payment_transactions_proto_rawDescOnce sync.Once
	file_billing_service_payment_transactions_proto_rawDescData []byte
)

func file_billing_service_payment_transactions_proto_rawDescGZIP() []byte {
	file_billing_service_payment_transactions_proto_rawDescOnce.Do(func() {
		file_billing_service_payment_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_payment_transactions_proto_rawDesc), len(file_billing_service_payment_transactions_proto_rawDesc)))
	})
	return file_billing_service_payment_transactions_proto_rawDescData
}

var file_billing_service_payment_transactions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_billing_service_payment_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_billing_service_payment_transactions_proto_goTypes = []any{
	(PaymentTransactionType)(0),                       // 0: billing_service.PaymentTransactionType
	(PaymentTransactionStatus)(0),                     // 1: billing_service.PaymentTransactionStatus
	(*PaymentTransaction)(nil),                        // 2: billing_service.PaymentTransaction
	(*ListPaymentTransactionsByPurchaseRequest)(nil),  // 3: billing_service.ListPaymentTransactionsByPurchaseRequest
	(*ListPaymentTransactionsByPurchaseResponse)(nil), // 4: billing_service.ListPaymentTransactionsByPurchaseResponse
	(*ListPaymentTransactionsByAttemptRequest)(nil),   // 5: billing_service.ListPaymentTransactionsByAttemptRequest
	(*ListPaymentTransactionsByAttemptResponse)(nil),  // 6: billing_service.ListPaymentTransactionsByAttemptResponse
	(*Money)(nil),                     // 7: billing_service.Money
	(*structpb.Struct)(nil),           // 8: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*common.ListQueryRequest)(nil),   // 10: common.ListQueryRequest
	(*common.PaginationMetadata)(nil), // 11: common.PaginationMetadata
}
var file_billing_service_payment_transactions_proto_depIdxs = []int32{
	0,  // 0: billing_service.PaymentTransaction.type:type_name -> billing_service.PaymentTransactionType
	1,  // 1: billing_service.PaymentTransaction.status:type_name -> billing_service.PaymentTransactionStatus
	7,  // 2: billing_service.PaymentTransaction.amount:type_name -> billing_service.Money
	8,  // 3: billing_service.PaymentTransaction.metadata:type_name -> google.protobuf.Struct
	9,  // 4: billing_service.PaymentTransaction.processed_at:type_name -> google.protobuf.Timestamp
	9,  // 5: billing_service.PaymentTransaction.created_at:type_name -> google.protobuf.Timestamp
	10, // 6: billing_service.ListPaymentTransactionsByPurchaseRequest.query:type_name -> common.ListQueryRequest
	2,  // 7: billing_service.ListPaymentTransactionsByPurchaseResponse.transactions:type_name -> billing_service.PaymentTransaction
	11, // 8: billing_service.ListPaymentTransactionsByPurchaseResponse.pagination:type_name -> common.PaginationMetadata
	10, // 9: billing_service.ListPaymentTransactionsByAttemptRequest.query:type_name -> common.ListQueryRequest
	2,  // 10: billing_service.ListPaymentTransactionsByAttemptResponse.transactions:type_name -> billing_service.PaymentTransaction
	11, // 11: billing_service.ListPaymentTransactionsByAttemptResponse.pagination:type_name -> common.PaginationMetadata
	3,  // 12: billing_service.PaymentTransactionService.ListByPurchase:input_type -> billing_service.ListPaymentTransactionsByPurchaseRequest
	5,  // 13: billing_service.PaymentTransactionService.ListByAttempt:input_type -> billing_service.ListPaymentTransactionsByAttemptRequest
	4,  // 14: billing_service.PaymentTransactionService.ListByPurchase:output_type -> billing_service.ListPaymentTransactionsByPurchaseResponse
	6,  // 15: billing_service.PaymentTransactionService.ListByAttempt:output_type -> billing_service.ListPaymentTransactionsByAttemptResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_billing_service_payment_transactions_proto_init() }
func file_billing_service_payment_transactions_proto_init() {
	if File_billing_service_payment_transactions_proto != nil {
		return
	}
	file_billing_service_billing_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_payment_transactions_proto_rawDesc), len(file_billing_service_payment_transactions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_payment_transactions_proto_goTypes,
		DependencyIndexes: file_billing_service_payment_transactions_proto_depIdxs,
		EnumInfos:         file_billing_service_payment_transactions_proto_enumTypes,
		MessageInfos:      file_billing_service_payment_transactions_proto_msgTypes,
	}.Build()
	File_billing_service_payment_transactions_proto = out.File
	file_billing_service_payment_transactions_proto_goTypes = nil
	file_billing_service_payment_transactions_proto_depIdxs = nil
}
