// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: billing_service/payment_transactions.proto

package billing_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentTransactionService_ListByPurchase_FullMethodName = "/billing_service.PaymentTransactionService/ListByPurchase"
	PaymentTransactionService_ListByAttempt_FullMethodName  = "/billing_service.PaymentTransactionService/ListByAttempt"
)

// PaymentTransactionServiceClient is the client API for PaymentTransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentTransactionServiceClient interface {
	ListByPurchase(ctx context.Context, in *ListPaymentTransactionsByPurchaseRequest, opts ...grpc.CallOption) (*ListPaymentTransactionsByPurchaseResponse, error)
	ListByAttempt(ctx context.Context, in *ListPaymentTransactionsByAttemptRequest, opts ...grpc.CallOption) (*ListPaymentTransactionsByAttemptResponse, error)
}

type paymentTransactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentTransactionServiceClient(cc grpc.ClientConnInterface) PaymentTransactionServiceClient {
	return &paymentTransactionServiceClient{cc}
}

func (c *paymentTransactionServiceClient) ListByPurchase(ctx context.Context, in *ListPaymentTransactionsByPurchaseRequest, opts ...grpc.CallOption) (*ListPaymentTransactionsByPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentTransactionsByPurchaseResponse)
	err := c.cc.Invoke(ctx, PaymentTransactionService_ListByPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentTransactionServiceClient) ListByAttempt(ctx context.Context, in *ListPaymentTransactionsByAttemptRequest, opts ...grpc.CallOption) (*ListPaymentTransactionsByAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPaymentTransactionsByAttemptResponse)
	err := c.cc.Invoke(ctx, PaymentTransactionService_ListByAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentTransactionServiceServer is the server API for PaymentTransactionService service.
// All implementations should embed UnimplementedPaymentTransactionServiceServer
// for forward compatibility.
type PaymentTransactionServiceServer interface {
	ListByPurchase(context.Context, *ListPaymentTransactionsByPurchaseRequest) (*ListPaymentTransactionsByPurchaseResponse, error)
	ListByAttempt(context.Context, *ListPaymentTransactionsByAttemptRequest) (*ListPaymentTransactionsByAttemptResponse, error)
}

// UnimplementedPaymentTransactionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentTransactionServiceServer struct{}

func (UnimplementedPaymentTransactionServiceServer) ListByPurchase(context.Context, *ListPaymentTransactionsByPurchaseRequest) (*ListPaymentTransactionsByPurchaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByPurchase not implemented")
}
func (UnimplementedPaymentTransactionServiceServer) ListByAttempt(context.Context, *ListPaymentTransactionsByAttemptRequest) (*ListPaymentTransactionsByAttemptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListByAttempt not implemented")
}
func (UnimplementedPaymentTransactionServiceServer) testEmbeddedByValue() {}

// UnsafePaymentTransactionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentTransactionServiceServer will
// result in compilation errors.
type UnsafePaymentTransactionServiceServer interface {
	mustEmbedUnimplementedPaymentTransactionServiceServer()
}

func RegisterPaymentTransactionServiceServer(s grpc.ServiceRegistrar, srv PaymentTransactionServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentTransactionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentTransactionService_ServiceDesc, srv)
}

func _PaymentTransactionService_ListByPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentTransactionsByPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentTransactionServiceServer).ListByPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentTransactionService_ListByPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentTransactionServiceServer).ListByPurchase(ctx, req.(*ListPaymentTransactionsByPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentTransactionService_ListByAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPaymentTransactionsByAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentTransactionServiceServer).ListByAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentTransactionService_ListByAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentTransactionServiceServer).ListByAttempt(ctx, req.(*ListPaymentTransactionsByAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentTransactionService_ServiceDesc is the grpc.ServiceDesc for PaymentTransactionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentTransactionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing_service.PaymentTransactionService",
	HandlerType: (*PaymentTransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListByPurchase",
			Handler:    _PaymentTransactionService_ListByPurchase_Handler,
		},
		{
			MethodName: "ListByAttempt",
			Handler:    _PaymentTransactionService_ListByAttempt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_service/payment_transactions.proto",
}
