// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/plans.proto

package billing_service

import (
	common "github.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BillingInterval defines the frequency at which subscription billing occurs.
// Used to calculate the next renewal date based on current period dates.
type BillingInterval int32

const (
	// Unspecified interval; should not be used
	BillingInterval_BILLING_INTERVAL_UNSPECIFIED BillingInterval = 0
	// Subscription renews every day
	BillingInterval_BILLING_INTERVAL_DAY BillingInterval = 1
	// Subscription renews every week (7 days)
	BillingInterval_BILLING_INTERVAL_WEEK BillingInterval = 2
	// Subscription renews every month (calendar-based)
	BillingInterval_BILLING_INTERVAL_MONTH BillingInterval = 3
	// Subscription renews every year (calendar-based)
	BillingInterval_BILLING_INTERVAL_YEAR BillingInterval = 4
)

// Enum value maps for BillingInterval.
var (
	BillingInterval_name = map[int32]string{
		0: "BILLING_INTERVAL_UNSPECIFIED",
		1: "BILLING_INTERVAL_DAY",
		2: "BILLING_INTERVAL_WEEK",
		3: "BILLING_INTERVAL_MONTH",
		4: "BILLING_INTERVAL_YEAR",
	}
	BillingInterval_value = map[string]int32{
		"BILLING_INTERVAL_UNSPECIFIED": 0,
		"BILLING_INTERVAL_DAY":         1,
		"BILLING_INTERVAL_WEEK":        2,
		"BILLING_INTERVAL_MONTH":       3,
		"BILLING_INTERVAL_YEAR":        4,
	}
)

func (x BillingInterval) Enum() *BillingInterval {
	p := new(BillingInterval)
	*p = x
	return p
}

func (x BillingInterval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BillingInterval) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_service_plans_proto_enumTypes[0].Descriptor()
}

func (BillingInterval) Type() protoreflect.EnumType {
	return &file_billing_service_plans_proto_enumTypes[0]
}

func (x BillingInterval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BillingInterval.Descriptor instead.
func (BillingInterval) EnumDescriptor() ([]byte, []int) {
	return file_billing_service_plans_proto_rawDescGZIP(), []int{0}
}

type SubscriptionPlan struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price           *Money                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	BillingInterval BillingInterval        `protobuf:"varint,5,opt,name=billing_interval,json=billingInterval,proto3,enum=billing_service.BillingInterval" json:"billing_interval,omitempty"`
	IsActive        bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscriptionPlan) Reset() {
	*x = SubscriptionPlan{}
	mi := &file_billing_service_plans_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPlan) ProtoMessage() {}

func (x *SubscriptionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_plans_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionPlan.ProtoReflect.Descriptor instead.
func (*SubscriptionPlan) Descriptor() ([]byte, []int) {
	return file_billing_service_plans_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscriptionPlan) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SubscriptionPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubscriptionPlan) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *SubscriptionPlan) GetBillingInterval() BillingInterval {
	if x != nil {
		return x.BillingInterval
	}
	return BillingInterval_BILLING_INTERVAL_UNSPECIFIED
}

func (x *SubscriptionPlan) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SubscriptionPlan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListPlansRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	OnlyActive    bool                     `protobuf:"varint,1,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	Query         *common.ListQueryRequest `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_billing_service_plans_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_plans_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_plans_proto_rawDescGZIP(), []int{1}
}

func (x *ListPlansRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *ListPlansRequest) GetQuery() *common.ListQueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListPlansResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*SubscriptionPlan        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_billing_service_plans_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_plans_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_plans_proto_rawDescGZIP(), []int{2}
}

func (x *ListPlansResponse) GetData() []*SubscriptionPlan {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPlansResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_billing_service_plans_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_plans_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_plans_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SubscriptionPlan      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanResponse) Reset() {
	*x = GetPlanResponse{}
	mi := &file_billing_service_plans_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanResponse) ProtoMessage() {}

func (x *GetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_plans_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanResponse.ProtoReflect.Descriptor instead.
func (*GetPlanResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_plans_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlanResponse) GetData() *SubscriptionPlan {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_billing_service_plans_proto protoreflect.FileDescriptor

const file_billing_service_plans_proto_rawDesc = "" +
	"\n" +
	"\x1bbilling_service/plans.proto\x12\x0fbilling_service\x1a\x1dbilling_service/billing.proto\x1a\x17common/pagination.proto\x1a\x14common/request.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\x10SubscriptionPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12,\n" +
	"\x05price\x18\x04 \x01(\v2\x16.billing_service.MoneyR\x05price\x12K\n" +
	"\x10billing_interval\x18\x05 \x01(\x0e2 .billing_service.BillingIntervalR\x0fbillingInterval\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"c\n" +
	"\x10ListPlansRequest\x12\x1f\n" +
	"\vonly_active\x18\x01 \x01(\bR\n" +
	"onlyActive\x12.\n" +
	"\x05query\x18\x02 \x01(\v2\x18.common.ListQueryRequestR\x05query\"\x86\x01\n" +
	"\x11ListPlansResponse\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.billing_service.SubscriptionPlanR\x04data\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination\" \n" +
	"\x0eGetPlanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x0fGetPlanResponse\x125\n" +
	"\x04data\x18\x01 \x01(\v2!.billing_service.SubscriptionPlanR\x04data*\x9f\x01\n" +
	"\x0fBillingInterval\x12 \n" +
	"\x1cBILLING_INTERVAL_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BILLING_INTERVAL_DAY\x10\x01\x12\x19\n" +
	"\x15BILLING_INTERVAL_WEEK\x10\x02\x12\x1a\n" +
	"\x16BILLING_INTERVAL_MONTH\x10\x03\x12\x19\n" +
	"\x15BILLING_INTERVAL_YEAR\x10\x042\xbb\x01\n" +
	"\x17SubscriptionPlanService\x12R\n" +
	"\tListPlans\x12!.billing_service.ListPlansRequest\x1a\".billing_service.ListPlansResponse\x12L\n" +
	"\aGetPlan\x12\x1f.billing_service.GetPlanRequest\x1a .billing_service.GetPlanResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_plans_proto_rawDescOnce sync.Once
	file_billing_service_plans_proto_rawDescData []byte
)

func file_billing_service_plans_proto_rawDescGZIP() []byte {
	file_billing_service_plans_proto_rawDescOnce.Do(func() {
		file_billing_service_plans_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_plans_proto_rawDesc), len(file_billing_service_plans_proto_rawDesc)))
	})
	return file_billing_service_plans_proto_rawDescData
}

var file_billing_service_plans_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_service_plans_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_billing_service_plans_proto_goTypes = []any{
	(BillingInterval)(0),              // 0: billing_service.BillingInterval
	(*SubscriptionPlan)(nil),          // 1: billing_service.SubscriptionPlan
	(*ListPlansRequest)(nil),          // 2: billing_service.ListPlansRequest
	(*ListPlansResponse)(nil),         // 3: billing_service.ListPlansResponse
	(*GetPlanRequest)(nil),            // 4: billing_service.GetPlanRequest
	(*GetPlanResponse)(nil),           // 5: billing_service.GetPlanResponse
	(*Money)(nil),                     // 6: billing_service.Money
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
	(*common.ListQueryRequest)(nil),   // 8: common.ListQueryRequest
	(*common.PaginationMetadata)(nil), // 9: common.PaginationMetadata
}
var file_billing_service_plans_proto_depIdxs = []int32{
	6, // 0: billing_service.SubscriptionPlan.price:type_name -> billing_service.Money
	0, // 1: billing_service.SubscriptionPlan.billing_interval:type_name -> billing_service.BillingInterval
	7, // 2: billing_service.SubscriptionPlan.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: billing_service.ListPlansRequest.query:type_name -> common.ListQueryRequest
	1, // 4: billing_service.ListPlansResponse.data:type_name -> billing_service.SubscriptionPlan
	9, // 5: billing_service.ListPlansResponse.pagination:type_name -> common.PaginationMetadata
	1, // 6: billing_service.GetPlanResponse.data:type_name -> billing_service.SubscriptionPlan
	2, // 7: billing_service.SubscriptionPlanService.ListPlans:input_type -> billing_service.ListPlansRequest
	4, // 8: billing_service.SubscriptionPlanService.GetPlan:input_type -> billing_service.GetPlanRequest
	3, // 9: billing_service.SubscriptionPlanService.ListPlans:output_type -> billing_service.ListPlansResponse
	5, // 10: billing_service.SubscriptionPlanService.GetPlan:output_type -> billing_service.GetPlanResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_billing_service_plans_proto_init() }
func file_billing_service_plans_proto_init() {
	if File_billing_service_plans_proto != nil {
		return
	}
	file_billing_service_billing_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_plans_proto_rawDesc), len(file_billing_service_plans_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_plans_proto_goTypes,
		DependencyIndexes: file_billing_service_plans_proto_depIdxs,
		EnumInfos:         file_billing_service_plans_proto_enumTypes,
		MessageInfos:      file_billing_service_plans_proto_msgTypes,
	}.Build()
	File_billing_service_plans_proto = out.File
	file_billing_service_plans_proto_goTypes = nil
	file_billing_service_plans_proto_depIdxs = nil
}
