// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/processed_events.proto

package billing_service

import (
	common "github.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	ConsumerName  string                 `protobuf:"bytes,2,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedMessage) Reset() {
	*x = ProcessedMessage{}
	mi := &file_billing_service_processed_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedMessage) ProtoMessage() {}

func (x *ProcessedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_processed_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedMessage.ProtoReflect.Descriptor instead.
func (*ProcessedMessage) Descriptor() ([]byte, []int) {
	return file_billing_service_processed_events_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessedMessage) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *ProcessedMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ProcessedMessage) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

type GetProcessedMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessedMessageRequest) Reset() {
	*x = GetProcessedMessageRequest{}
	mi := &file_billing_service_processed_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessedMessageRequest) ProtoMessage() {}

func (x *GetProcessedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_processed_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessedMessageRequest.ProtoReflect.Descriptor instead.
func (*GetProcessedMessageRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_processed_events_proto_rawDescGZIP(), []int{1}
}

func (x *GetProcessedMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProcessedMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ProcessedMessage      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessedMessageResponse) Reset() {
	*x = GetProcessedMessageResponse{}
	mi := &file_billing_service_processed_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessedMessageResponse) ProtoMessage() {}

func (x *GetProcessedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_processed_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessedMessageResponse.ProtoReflect.Descriptor instead.
func (*GetProcessedMessageResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_processed_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetProcessedMessageResponse) GetData() *ProcessedMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListProcessedMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters (add more as needed)
	ConsumerName  string `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"` // empty => all consumers
	Page          int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessedMessagesRequest) Reset() {
	*x = ListProcessedMessagesRequest{}
	mi := &file_billing_service_processed_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessedMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessedMessagesRequest) ProtoMessage() {}

func (x *ListProcessedMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_processed_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessedMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessedMessagesRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_processed_events_proto_rawDescGZIP(), []int{3}
}

func (x *ListProcessedMessagesRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

func (x *ListProcessedMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProcessedMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProcessedMessagesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*ProcessedMessage        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessedMessagesResponse) Reset() {
	*x = ListProcessedMessagesResponse{}
	mi := &file_billing_service_processed_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessedMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessedMessagesResponse) ProtoMessage() {}

func (x *ListProcessedMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_processed_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessedMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessedMessagesResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_processed_events_proto_rawDescGZIP(), []int{4}
}

func (x *ListProcessedMessagesResponse) GetData() []*ProcessedMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListProcessedMessagesResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_billing_service_processed_events_proto protoreflect.FileDescriptor

const file_billing_service_processed_events_proto_rawDesc = "" +
	"\n" +
	"&billing_service/processed_events.proto\x12\x0fbilling_service\x1a\x17common/pagination.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\x10ProcessedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rconsumer_name\x18\x02 \x01(\tR\fconsumerName\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12=\n" +
	"\fprocessed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\",\n" +
	"\x1aGetProcessedMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x1bGetProcessedMessageResponse\x125\n" +
	"\x04data\x18\x01 \x01(\v2!.billing_service.ProcessedMessageR\x04data\"m\n" +
	"\x1cListProcessedMessagesRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x92\x01\n" +
	"\x1dListProcessedMessagesResponse\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.billing_service.ProcessedMessageR\x04data\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination2\x83\x02\n" +
	"\x17ProcessedMessageService\x12p\n" +
	"\x13GetProcessedMessage\x12+.billing_service.GetProcessedMessageRequest\x1a,.billing_service.GetProcessedMessageResponse\x12v\n" +
	"\x15ListProcessedMessages\x12-.billing_service.ListProcessedMessagesRequest\x1a..billing_service.ListProcessedMessagesResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_processed_events_proto_rawDescOnce sync.Once
	file_billing_service_processed_events_proto_rawDescData []byte
)

func file_billing_service_processed_events_proto_rawDescGZIP() []byte {
	file_billing_service_processed_events_proto_rawDescOnce.Do(func() {
		file_billing_service_processed_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_processed_events_proto_rawDesc), len(file_billing_service_processed_events_proto_rawDesc)))
	})
	return file_billing_service_processed_events_proto_rawDescData
}

var file_billing_service_processed_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_billing_service_processed_events_proto_goTypes = []any{
	(*ProcessedMessage)(nil),              // 0: billing_service.ProcessedMessage
	(*GetProcessedMessageRequest)(nil),    // 1: billing_service.GetProcessedMessageRequest
	(*GetProcessedMessageResponse)(nil),   // 2: billing_service.GetProcessedMessageResponse
	(*ListProcessedMessagesRequest)(nil),  // 3: billing_service.ListProcessedMessagesRequest
	(*ListProcessedMessagesResponse)(nil), // 4: billing_service.ListProcessedMessagesResponse
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
	(*common.PaginationMetadata)(nil),     // 6: common.PaginationMetadata
}
var file_billing_service_processed_events_proto_depIdxs = []int32{
	5, // 0: billing_service.ProcessedMessage.processed_at:type_name -> google.protobuf.Timestamp
	0, // 1: billing_service.GetProcessedMessageResponse.data:type_name -> billing_service.ProcessedMessage
	0, // 2: billing_service.ListProcessedMessagesResponse.data:type_name -> billing_service.ProcessedMessage
	6, // 3: billing_service.ListProcessedMessagesResponse.pagination:type_name -> common.PaginationMetadata
	1, // 4: billing_service.ProcessedMessageService.GetProcessedMessage:input_type -> billing_service.GetProcessedMessageRequest
	3, // 5: billing_service.ProcessedMessageService.ListProcessedMessages:input_type -> billing_service.ListProcessedMessagesRequest
	2, // 6: billing_service.ProcessedMessageService.GetProcessedMessage:output_type -> billing_service.GetProcessedMessageResponse
	4, // 7: billing_service.ProcessedMessageService.ListProcessedMessages:output_type -> billing_service.ListProcessedMessagesResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_billing_service_processed_events_proto_init() }
func file_billing_service_processed_events_proto_init() {
	if File_billing_service_processed_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_processed_events_proto_rawDesc), len(file_billing_service_processed_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_processed_events_proto_goTypes,
		DependencyIndexes: file_billing_service_processed_events_proto_depIdxs,
		MessageInfos:      file_billing_service_processed_events_proto_msgTypes,
	}.Build()
	File_billing_service_processed_events_proto = out.File
	file_billing_service_processed_events_proto_goTypes = nil
	file_billing_service_processed_events_proto_depIdxs = nil
}
