// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: billing_service/processed_events.proto

package billing_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessedMessageService_GetProcessedMessage_FullMethodName   = "/billing_service.ProcessedMessageService/GetProcessedMessage"
	ProcessedMessageService_ListProcessedMessages_FullMethodName = "/billing_service.ProcessedMessageService/ListProcessedMessages"
)

// ProcessedMessageServiceClient is the client API for ProcessedMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This is usually internal-only for debugging/admin.
// Many systems don’t expose this at all; they only query DB directly.
type ProcessedMessageServiceClient interface {
	GetProcessedMessage(ctx context.Context, in *GetProcessedMessageRequest, opts ...grpc.CallOption) (*GetProcessedMessageResponse, error)
	ListProcessedMessages(ctx context.Context, in *ListProcessedMessagesRequest, opts ...grpc.CallOption) (*ListProcessedMessagesResponse, error)
}

type processedMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessedMessageServiceClient(cc grpc.ClientConnInterface) ProcessedMessageServiceClient {
	return &processedMessageServiceClient{cc}
}

func (c *processedMessageServiceClient) GetProcessedMessage(ctx context.Context, in *GetProcessedMessageRequest, opts ...grpc.CallOption) (*GetProcessedMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessedMessageResponse)
	err := c.cc.Invoke(ctx, ProcessedMessageService_GetProcessedMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processedMessageServiceClient) ListProcessedMessages(ctx context.Context, in *ListProcessedMessagesRequest, opts ...grpc.CallOption) (*ListProcessedMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessedMessagesResponse)
	err := c.cc.Invoke(ctx, ProcessedMessageService_ListProcessedMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessedMessageServiceServer is the server API for ProcessedMessageService service.
// All implementations should embed UnimplementedProcessedMessageServiceServer
// for forward compatibility.
//
// This is usually internal-only for debugging/admin.
// Many systems don’t expose this at all; they only query DB directly.
type ProcessedMessageServiceServer interface {
	GetProcessedMessage(context.Context, *GetProcessedMessageRequest) (*GetProcessedMessageResponse, error)
	ListProcessedMessages(context.Context, *ListProcessedMessagesRequest) (*ListProcessedMessagesResponse, error)
}

// UnimplementedProcessedMessageServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessedMessageServiceServer struct{}

func (UnimplementedProcessedMessageServiceServer) GetProcessedMessage(context.Context, *GetProcessedMessageRequest) (*GetProcessedMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcessedMessage not implemented")
}
func (UnimplementedProcessedMessageServiceServer) ListProcessedMessages(context.Context, *ListProcessedMessagesRequest) (*ListProcessedMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcessedMessages not implemented")
}
func (UnimplementedProcessedMessageServiceServer) testEmbeddedByValue() {}

// UnsafeProcessedMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessedMessageServiceServer will
// result in compilation errors.
type UnsafeProcessedMessageServiceServer interface {
	mustEmbedUnimplementedProcessedMessageServiceServer()
}

func RegisterProcessedMessageServiceServer(s grpc.ServiceRegistrar, srv ProcessedMessageServiceServer) {
	// If the following call panics, it indicates UnimplementedProcessedMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessedMessageService_ServiceDesc, srv)
}

func _ProcessedMessageService_GetProcessedMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessedMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessedMessageServiceServer).GetProcessedMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessedMessageService_GetProcessedMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessedMessageServiceServer).GetProcessedMessage(ctx, req.(*GetProcessedMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessedMessageService_ListProcessedMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessedMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessedMessageServiceServer).ListProcessedMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessedMessageService_ListProcessedMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessedMessageServiceServer).ListProcessedMessages(ctx, req.(*ListProcessedMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessedMessageService_ServiceDesc is the grpc.ServiceDesc for ProcessedMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessedMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing_service.ProcessedMessageService",
	HandlerType: (*ProcessedMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProcessedMessage",
			Handler:    _ProcessedMessageService_GetProcessedMessage_Handler,
		},
		{
			MethodName: "ListProcessedMessages",
			Handler:    _ProcessedMessageService_ListProcessedMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_service/processed_events.proto",
}
