// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/purchases.proto

package billing_service

import (
	common "github.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PurchaseStatus represents the lifecycle state of a purchase transaction.
// A purchase progresses through these states during the payment and fulfillment process.
type PurchaseStatus int32

const (
	// Unspecified status; should not be used
	PurchaseStatus_PURCHASE_STATUS_UNSPECIFIED PurchaseStatus = 0
	// User initiated checkout but has not yet completed payment
	PurchaseStatus_PURCHASE_STATUS_PENDING PurchaseStatus = 1
	// Payment completed successfully; webhook processed; new subscription period created
	PurchaseStatus_PURCHASE_STATUS_COMPLETED PurchaseStatus = 2
	// Payment processing failed; purchase will not result in subscription
	PurchaseStatus_PURCHASE_STATUS_FAILED PurchaseStatus = 3
	// Payment attempt expired before completion; purchase was abandoned
	PurchaseStatus_PURCHASE_STATUS_CANCELED PurchaseStatus = 4
)

// Enum value maps for PurchaseStatus.
var (
	PurchaseStatus_name = map[int32]string{
		0: "PURCHASE_STATUS_UNSPECIFIED",
		1: "PURCHASE_STATUS_PENDING",
		2: "PURCHASE_STATUS_COMPLETED",
		3: "PURCHASE_STATUS_FAILED",
		4: "PURCHASE_STATUS_CANCELED",
	}
	PurchaseStatus_value = map[string]int32{
		"PURCHASE_STATUS_UNSPECIFIED": 0,
		"PURCHASE_STATUS_PENDING":     1,
		"PURCHASE_STATUS_COMPLETED":   2,
		"PURCHASE_STATUS_FAILED":      3,
		"PURCHASE_STATUS_CANCELED":    4,
	}
)

func (x PurchaseStatus) Enum() *PurchaseStatus {
	p := new(PurchaseStatus)
	*p = x
	return p
}

func (x PurchaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PurchaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_service_purchases_proto_enumTypes[0].Descriptor()
}

func (PurchaseStatus) Type() protoreflect.EnumType {
	return &file_billing_service_purchases_proto_enumTypes[0]
}

func (x PurchaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PurchaseStatus.Descriptor instead.
func (PurchaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{0}
}

type Purchase struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	PlanId         string                 `protobuf:"bytes,4,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Amount         *Money                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         PurchaseStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=billing_service.PurchaseStatus" json:"status,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_billing_service_purchases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchase.ProtoReflect.Descriptor instead.
func (*Purchase) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{0}
}

func (x *Purchase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Purchase) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Purchase) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Purchase) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Purchase) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Purchase) GetStatus() PurchaseStatus {
	if x != nil {
		return x.Status
	}
	return PurchaseStatus_PURCHASE_STATUS_UNSPECIFIED
}

func (x *Purchase) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Purchase) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Purchase) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CreatePurchaseRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// Client-generated idempotency key to prevent duplicates.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePurchaseRequest) Reset() {
	*x = CreatePurchaseRequest{}
	mi := &file_billing_service_purchases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePurchaseRequest) ProtoMessage() {}

func (x *CreatePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePurchaseRequest.ProtoReflect.Descriptor instead.
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePurchaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePurchaseRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreatePurchaseRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreatePurchaseResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReturnCode       int32                  `protobuf:"varint,2,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	ReturnMessage    string                 `protobuf:"bytes,3,opt,name=return_message,json=returnMessage,proto3" json:"return_message,omitempty"`
	SubReturnCode    int32                  `protobuf:"varint,4,opt,name=sub_return_code,json=subReturnCode,proto3" json:"sub_return_code,omitempty"`
	SubReturnMessage string                 `protobuf:"bytes,5,opt,name=sub_return_message,json=subReturnMessage,proto3" json:"sub_return_message,omitempty"`
	OrderUrl         string                 `protobuf:"bytes,6,opt,name=order_url,json=orderUrl,proto3" json:"order_url,omitempty"`
	Zptranstoken     string                 `protobuf:"bytes,7,opt,name=zptranstoken,proto3" json:"zptranstoken,omitempty"`
	OrderToken       string                 `protobuf:"bytes,8,opt,name=order_token,json=orderToken,proto3" json:"order_token,omitempty"`
	QrCode           string                 `protobuf:"bytes,9,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePurchaseResponse) Reset() {
	*x = CreatePurchaseResponse{}
	mi := &file_billing_service_purchases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePurchaseResponse) ProtoMessage() {}

func (x *CreatePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePurchaseResponse.ProtoReflect.Descriptor instead.
func (*CreatePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePurchaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePurchaseResponse) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *CreatePurchaseResponse) GetReturnMessage() string {
	if x != nil {
		return x.ReturnMessage
	}
	return ""
}

func (x *CreatePurchaseResponse) GetSubReturnCode() int32 {
	if x != nil {
		return x.SubReturnCode
	}
	return 0
}

func (x *CreatePurchaseResponse) GetSubReturnMessage() string {
	if x != nil {
		return x.SubReturnMessage
	}
	return ""
}

func (x *CreatePurchaseResponse) GetOrderUrl() string {
	if x != nil {
		return x.OrderUrl
	}
	return ""
}

func (x *CreatePurchaseResponse) GetZptranstoken() string {
	if x != nil {
		return x.Zptranstoken
	}
	return ""
}

func (x *CreatePurchaseResponse) GetOrderToken() string {
	if x != nil {
		return x.OrderToken
	}
	return ""
}

func (x *CreatePurchaseResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type GetPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseRequest) Reset() {
	*x = GetPurchaseRequest{}
	mi := &file_billing_service_purchases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseRequest) ProtoMessage() {}

func (x *GetPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseRequest.ProtoReflect.Descriptor instead.
func (*GetPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{3}
}

func (x *GetPurchaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Purchase              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseResponse) Reset() {
	*x = GetPurchaseResponse{}
	mi := &file_billing_service_purchases_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseResponse) ProtoMessage() {}

func (x *GetPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseResponse.ProtoReflect.Descriptor instead.
func (*GetPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{4}
}

func (x *GetPurchaseResponse) GetData() *Purchase {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListPurchasesBySubscriptionRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	SubscriptionId string                   `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Query          *common.ListQueryRequest `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPurchasesBySubscriptionRequest) Reset() {
	*x = ListPurchasesBySubscriptionRequest{}
	mi := &file_billing_service_purchases_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPurchasesBySubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPurchasesBySubscriptionRequest) ProtoMessage() {}

func (x *ListPurchasesBySubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPurchasesBySubscriptionRequest.ProtoReflect.Descriptor instead.
func (*ListPurchasesBySubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{5}
}

func (x *ListPurchasesBySubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ListPurchasesBySubscriptionRequest) GetQuery() *common.ListQueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListPurchasesBySubscriptionResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*Purchase                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPurchasesBySubscriptionResponse) Reset() {
	*x = ListPurchasesBySubscriptionResponse{}
	mi := &file_billing_service_purchases_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPurchasesBySubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPurchasesBySubscriptionResponse) ProtoMessage() {}

func (x *ListPurchasesBySubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPurchasesBySubscriptionResponse.ProtoReflect.Descriptor instead.
func (*ListPurchasesBySubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{6}
}

func (x *ListPurchasesBySubscriptionResponse) GetData() []*Purchase {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPurchasesBySubscriptionResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPurchasesByUserRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         *common.ListQueryRequest `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPurchasesByUserRequest) Reset() {
	*x = ListPurchasesByUserRequest{}
	mi := &file_billing_service_purchases_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPurchasesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPurchasesByUserRequest) ProtoMessage() {}

func (x *ListPurchasesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPurchasesByUserRequest.ProtoReflect.Descriptor instead.
func (*ListPurchasesByUserRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{7}
}

func (x *ListPurchasesByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPurchasesByUserRequest) GetQuery() *common.ListQueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListPurchasesByUserResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*Purchase                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPurchasesByUserResponse) Reset() {
	*x = ListPurchasesByUserResponse{}
	mi := &file_billing_service_purchases_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPurchasesByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPurchasesByUserResponse) ProtoMessage() {}

func (x *ListPurchasesByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_purchases_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPurchasesByUserResponse.ProtoReflect.Descriptor instead.
func (*ListPurchasesByUserResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_purchases_proto_rawDescGZIP(), []int{8}
}

func (x *ListPurchasesByUserResponse) GetData() []*Purchase {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListPurchasesByUserResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_billing_service_purchases_proto protoreflect.FileDescriptor

const file_billing_service_purchases_proto_rawDesc = "" +
	"\n" +
	"\x1fbilling_service/purchases.proto\x12\x0fbilling_service\x1a\x1dbilling_service/billing.proto\x1a\x17common/pagination.proto\x1a\x14common/request.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x03\n" +
	"\bPurchase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\aplan_id\x18\x04 \x01(\tR\x06planId\x12.\n" +
	"\x06amount\x18\x05 \x01(\v2\x16.billing_service.MoneyR\x06amount\x127\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1f.billing_service.PurchaseStatusR\x06status\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"r\n" +
	"\x15CreatePurchaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xc1\x02\n" +
	"\x16CreatePurchaseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vreturn_code\x18\x02 \x01(\x05R\n" +
	"returnCode\x12%\n" +
	"\x0ereturn_message\x18\x03 \x01(\tR\rreturnMessage\x12&\n" +
	"\x0fsub_return_code\x18\x04 \x01(\x05R\rsubReturnCode\x12,\n" +
	"\x12sub_return_message\x18\x05 \x01(\tR\x10subReturnMessage\x12\x1b\n" +
	"\torder_url\x18\x06 \x01(\tR\borderUrl\x12\"\n" +
	"\fzptranstoken\x18\a \x01(\tR\fzptranstoken\x12\x1f\n" +
	"\vorder_token\x18\b \x01(\tR\n" +
	"orderToken\x12\x17\n" +
	"\aqr_code\x18\t \x01(\tR\x06qrCode\"$\n" +
	"\x12GetPurchaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x13GetPurchaseResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.billing_service.PurchaseR\x04data\"}\n" +
	"\"ListPurchasesBySubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12.\n" +
	"\x05query\x18\x02 \x01(\v2\x18.common.ListQueryRequestR\x05query\"\x90\x01\n" +
	"#ListPurchasesBySubscriptionResponse\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.billing_service.PurchaseR\x04data\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination\"e\n" +
	"\x1aListPurchasesByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x05query\x18\x02 \x01(\v2\x18.common.ListQueryRequestR\x05query\"\x88\x01\n" +
	"\x1bListPurchasesByUserResponse\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.billing_service.PurchaseR\x04data\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination*\xa7\x01\n" +
	"\x0ePurchaseStatus\x12\x1f\n" +
	"\x1bPURCHASE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PURCHASE_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PURCHASE_STATUS_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16PURCHASE_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18PURCHASE_STATUS_CANCELED\x10\x042\xcb\x03\n" +
	"\x0fPurchaseService\x12a\n" +
	"\x0eCreatePurchase\x12&.billing_service.CreatePurchaseRequest\x1a'.billing_service.CreatePurchaseResponse\x12X\n" +
	"\vGetPurchase\x12#.billing_service.GetPurchaseRequest\x1a$.billing_service.GetPurchaseResponse\x12\x88\x01\n" +
	"\x1bListPurchasesBySubscription\x123.billing_service.ListPurchasesBySubscriptionRequest\x1a4.billing_service.ListPurchasesBySubscriptionResponse\x12p\n" +
	"\x13ListPurchasesByUser\x12+.billing_service.ListPurchasesByUserRequest\x1a,.billing_service.ListPurchasesByUserResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_purchases_proto_rawDescOnce sync.Once
	file_billing_service_purchases_proto_rawDescData []byte
)

func file_billing_service_purchases_proto_rawDescGZIP() []byte {
	file_billing_service_purchases_proto_rawDescOnce.Do(func() {
		file_billing_service_purchases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_purchases_proto_rawDesc), len(file_billing_service_purchases_proto_rawDesc)))
	})
	return file_billing_service_purchases_proto_rawDescData
}

var file_billing_service_purchases_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_service_purchases_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_billing_service_purchases_proto_goTypes = []any{
	(PurchaseStatus)(0),                         // 0: billing_service.PurchaseStatus
	(*Purchase)(nil),                            // 1: billing_service.Purchase
	(*CreatePurchaseRequest)(nil),               // 2: billing_service.CreatePurchaseRequest
	(*CreatePurchaseResponse)(nil),              // 3: billing_service.CreatePurchaseResponse
	(*GetPurchaseRequest)(nil),                  // 4: billing_service.GetPurchaseRequest
	(*GetPurchaseResponse)(nil),                 // 5: billing_service.GetPurchaseResponse
	(*ListPurchasesBySubscriptionRequest)(nil),  // 6: billing_service.ListPurchasesBySubscriptionRequest
	(*ListPurchasesBySubscriptionResponse)(nil), // 7: billing_service.ListPurchasesBySubscriptionResponse
	(*ListPurchasesByUserRequest)(nil),          // 8: billing_service.ListPurchasesByUserRequest
	(*ListPurchasesByUserResponse)(nil),         // 9: billing_service.ListPurchasesByUserResponse
	(*Money)(nil),                               // 10: billing_service.Money
	(*timestamppb.Timestamp)(nil),               // 11: google.protobuf.Timestamp
	(*common.ListQueryRequest)(nil),             // 12: common.ListQueryRequest
	(*common.PaginationMetadata)(nil),           // 13: common.PaginationMetadata
}
var file_billing_service_purchases_proto_depIdxs = []int32{
	10, // 0: billing_service.Purchase.amount:type_name -> billing_service.Money
	0,  // 1: billing_service.Purchase.status:type_name -> billing_service.PurchaseStatus
	11, // 2: billing_service.Purchase.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: billing_service.Purchase.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 4: billing_service.GetPurchaseResponse.data:type_name -> billing_service.Purchase
	12, // 5: billing_service.ListPurchasesBySubscriptionRequest.query:type_name -> common.ListQueryRequest
	1,  // 6: billing_service.ListPurchasesBySubscriptionResponse.data:type_name -> billing_service.Purchase
	13, // 7: billing_service.ListPurchasesBySubscriptionResponse.pagination:type_name -> common.PaginationMetadata
	12, // 8: billing_service.ListPurchasesByUserRequest.query:type_name -> common.ListQueryRequest
	1,  // 9: billing_service.ListPurchasesByUserResponse.data:type_name -> billing_service.Purchase
	13, // 10: billing_service.ListPurchasesByUserResponse.pagination:type_name -> common.PaginationMetadata
	2,  // 11: billing_service.PurchaseService.CreatePurchase:input_type -> billing_service.CreatePurchaseRequest
	4,  // 12: billing_service.PurchaseService.GetPurchase:input_type -> billing_service.GetPurchaseRequest
	6,  // 13: billing_service.PurchaseService.ListPurchasesBySubscription:input_type -> billing_service.ListPurchasesBySubscriptionRequest
	8,  // 14: billing_service.PurchaseService.ListPurchasesByUser:input_type -> billing_service.ListPurchasesByUserRequest
	3,  // 15: billing_service.PurchaseService.CreatePurchase:output_type -> billing_service.CreatePurchaseResponse
	5,  // 16: billing_service.PurchaseService.GetPurchase:output_type -> billing_service.GetPurchaseResponse
	7,  // 17: billing_service.PurchaseService.ListPurchasesBySubscription:output_type -> billing_service.ListPurchasesBySubscriptionResponse
	9,  // 18: billing_service.PurchaseService.ListPurchasesByUser:output_type -> billing_service.ListPurchasesByUserResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_billing_service_purchases_proto_init() }
func file_billing_service_purchases_proto_init() {
	if File_billing_service_purchases_proto != nil {
		return
	}
	file_billing_service_billing_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_purchases_proto_rawDesc), len(file_billing_service_purchases_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_purchases_proto_goTypes,
		DependencyIndexes: file_billing_service_purchases_proto_depIdxs,
		EnumInfos:         file_billing_service_purchases_proto_enumTypes,
		MessageInfos:      file_billing_service_purchases_proto_msgTypes,
	}.Build()
	File_billing_service_purchases_proto = out.File
	file_billing_service_purchases_proto_goTypes = nil
	file_billing_service_purchases_proto_depIdxs = nil
}
