// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: billing_service/subscription_events.proto

package billing_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionEventService_GetSubscriptionEvent_FullMethodName   = "/billing_service.SubscriptionEventService/GetSubscriptionEvent"
	SubscriptionEventService_ListSubscriptionEvents_FullMethodName = "/billing_service.SubscriptionEventService/ListSubscriptionEvents"
)

// SubscriptionEventServiceClient is the client API for SubscriptionEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal/admin/debug service. Many systems don’t expose this publicly.
type SubscriptionEventServiceClient interface {
	GetSubscriptionEvent(ctx context.Context, in *GetSubscriptionEventRequest, opts ...grpc.CallOption) (*GetSubscriptionEventResponse, error)
	ListSubscriptionEvents(ctx context.Context, in *ListSubscriptionEventsRequest, opts ...grpc.CallOption) (*ListSubscriptionEventsResponse, error)
}

type subscriptionEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionEventServiceClient(cc grpc.ClientConnInterface) SubscriptionEventServiceClient {
	return &subscriptionEventServiceClient{cc}
}

func (c *subscriptionEventServiceClient) GetSubscriptionEvent(ctx context.Context, in *GetSubscriptionEventRequest, opts ...grpc.CallOption) (*GetSubscriptionEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscriptionEventResponse)
	err := c.cc.Invoke(ctx, SubscriptionEventService_GetSubscriptionEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionEventServiceClient) ListSubscriptionEvents(ctx context.Context, in *ListSubscriptionEventsRequest, opts ...grpc.CallOption) (*ListSubscriptionEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubscriptionEventsResponse)
	err := c.cc.Invoke(ctx, SubscriptionEventService_ListSubscriptionEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionEventServiceServer is the server API for SubscriptionEventService service.
// All implementations should embed UnimplementedSubscriptionEventServiceServer
// for forward compatibility.
//
// Internal/admin/debug service. Many systems don’t expose this publicly.
type SubscriptionEventServiceServer interface {
	GetSubscriptionEvent(context.Context, *GetSubscriptionEventRequest) (*GetSubscriptionEventResponse, error)
	ListSubscriptionEvents(context.Context, *ListSubscriptionEventsRequest) (*ListSubscriptionEventsResponse, error)
}

// UnimplementedSubscriptionEventServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionEventServiceServer struct{}

func (UnimplementedSubscriptionEventServiceServer) GetSubscriptionEvent(context.Context, *GetSubscriptionEventRequest) (*GetSubscriptionEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscriptionEvent not implemented")
}
func (UnimplementedSubscriptionEventServiceServer) ListSubscriptionEvents(context.Context, *ListSubscriptionEventsRequest) (*ListSubscriptionEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscriptionEvents not implemented")
}
func (UnimplementedSubscriptionEventServiceServer) testEmbeddedByValue() {}

// UnsafeSubscriptionEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionEventServiceServer will
// result in compilation errors.
type UnsafeSubscriptionEventServiceServer interface {
	mustEmbedUnimplementedSubscriptionEventServiceServer()
}

func RegisterSubscriptionEventServiceServer(s grpc.ServiceRegistrar, srv SubscriptionEventServiceServer) {
	// If the following call panics, it indicates UnimplementedSubscriptionEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionEventService_ServiceDesc, srv)
}

func _SubscriptionEventService_GetSubscriptionEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionEventServiceServer).GetSubscriptionEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionEventService_GetSubscriptionEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionEventServiceServer).GetSubscriptionEvent(ctx, req.(*GetSubscriptionEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionEventService_ListSubscriptionEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionEventServiceServer).ListSubscriptionEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionEventService_ListSubscriptionEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionEventServiceServer).ListSubscriptionEvents(ctx, req.(*ListSubscriptionEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionEventService_ServiceDesc is the grpc.ServiceDesc for SubscriptionEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing_service.SubscriptionEventService",
	HandlerType: (*SubscriptionEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSubscriptionEvent",
			Handler:    _SubscriptionEventService_GetSubscriptionEvent_Handler,
		},
		{
			MethodName: "ListSubscriptionEvents",
			Handler:    _SubscriptionEventService_ListSubscriptionEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_service/subscription_events.proto",
}
