// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/subscriptions.proto

package billing_service

import (
	common "github.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscriptionStatus represents the lifecycle state of a user's subscription.
// These states define whether the user has access to subscription benefits and
// whether the subscription is in good standing or has issues.
type SubscriptionStatus int32

const (
	// Unspecified status; should not be used
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED SubscriptionStatus = 0
	// Initial state after successful payment; waiting for user role/permissions to be activated
	SubscriptionStatus_SUBSCRIPTION_STATUS_PENDING SubscriptionStatus = 1
	// Subscription is active; user has full access to subscription benefits
	SubscriptionStatus_SUBSCRIPTION_STATUS_ACTIVE SubscriptionStatus = 2
	// Renewal payment failed; user retains access through current period end, then expires
	SubscriptionStatus_SUBSCRIPTION_STATUS_PAST_DUE SubscriptionStatus = 3
	// User initiated cancellation; user retains access through current period end, then expires
	SubscriptionStatus_SUBSCRIPTION_STATUS_CANCELED SubscriptionStatus = 4
	// Subscription period ended; user no longer has access to benefits (can renew)
	SubscriptionStatus_SUBSCRIPTION_STATUS_EXPIRED SubscriptionStatus = 5
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "SUBSCRIPTION_STATUS_UNSPECIFIED",
		1: "SUBSCRIPTION_STATUS_PENDING",
		2: "SUBSCRIPTION_STATUS_ACTIVE",
		3: "SUBSCRIPTION_STATUS_PAST_DUE",
		4: "SUBSCRIPTION_STATUS_CANCELED",
		5: "SUBSCRIPTION_STATUS_EXPIRED",
	}
	SubscriptionStatus_value = map[string]int32{
		"SUBSCRIPTION_STATUS_UNSPECIFIED": 0,
		"SUBSCRIPTION_STATUS_PENDING":     1,
		"SUBSCRIPTION_STATUS_ACTIVE":      2,
		"SUBSCRIPTION_STATUS_PAST_DUE":    3,
		"SUBSCRIPTION_STATUS_CANCELED":    4,
		"SUBSCRIPTION_STATUS_EXPIRED":     5,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_service_subscriptions_proto_enumTypes[0].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_billing_service_subscriptions_proto_enumTypes[0]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{0}
}

type Subscription struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId             string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Status             SubscriptionStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=billing_service.SubscriptionStatus" json:"status,omitempty"`
	CurrentPeriodStart *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	CurrentPeriodEnd   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	CancelAtPeriodEnd  bool                   `protobuf:"varint,7,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"`
	CanceledAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	ExpiredAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *Subscription) GetCurrentPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return nil
}

func (x *Subscription) GetCurrentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return nil
}

func (x *Subscription) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *Subscription) GetCanceledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CanceledAt
	}
	return nil
}

func (x *Subscription) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Subscription) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateSubscriptionRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// If you support trials, you can set an initial period here.
	InitialPeriodStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=initial_period_start,json=initialPeriodStart,proto3" json:"initial_period_start,omitempty"`
	InitialPeriodEnd   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=initial_period_end,json=initialPeriodEnd,proto3" json:"initial_period_end,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetInitialPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.InitialPeriodStart
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetInitialPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.InitialPeriodEnd
	}
	return nil
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *common.OperationMetadata `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSubscriptionResponse) GetData() *common.OperationMetadata {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Subscription          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriptionResponse) GetData() *Subscription {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListSubscriptionsByUserRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	UserId        string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         *common.ListQueryRequest `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsByUserRequest) Reset() {
	*x = ListSubscriptionsByUserRequest{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsByUserRequest) ProtoMessage() {}

func (x *ListSubscriptionsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsByUserRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsByUserRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{5}
}

func (x *ListSubscriptionsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSubscriptionsByUserRequest) GetQuery() *common.ListQueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListSubscriptionsByUserResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*Subscription            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsByUserResponse) Reset() {
	*x = ListSubscriptionsByUserResponse{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsByUserResponse) ProtoMessage() {}

func (x *ListSubscriptionsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsByUserResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsByUserResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{6}
}

func (x *ListSubscriptionsByUserResponse) GetData() []*Subscription {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListSubscriptionsByUserResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CancelSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// If true: set cancel_at_period_end=true.
	// If false: cancel immediately.
	AtPeriodEnd bool `protobuf:"varint,2,opt,name=at_period_end,json=atPeriodEnd,proto3" json:"at_period_end,omitempty"`
	// Idempotency for repeated cancel calls (recommended).
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{7}
}

func (x *CancelSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *CancelSubscriptionRequest) GetAtPeriodEnd() bool {
	if x != nil {
		return x.AtPeriodEnd
	}
	return false
}

func (x *CancelSubscriptionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *common.OperationMetadata `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_billing_service_subscriptions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscriptions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_subscriptions_proto_rawDescGZIP(), []int{8}
}

func (x *CancelSubscriptionResponse) GetData() *common.OperationMetadata {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_billing_service_subscriptions_proto protoreflect.FileDescriptor

const file_billing_service_subscriptions_proto_rawDesc = "" +
	"\n" +
	"#billing_service/subscriptions.proto\x12\x0fbilling_service\x1a\x17common/pagination.proto\x1a\x14common/request.proto\x1a\x15common/response.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x04\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.billing_service.SubscriptionStatusR\x06status\x12L\n" +
	"\x14current_period_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12currentPeriodStart\x12H\n" +
	"\x12current_period_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10currentPeriodEnd\x12/\n" +
	"\x14cancel_at_period_end\x18\a \x01(\bR\x11cancelAtPeriodEnd\x12;\n" +
	"\vcanceled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"canceledAt\x129\n" +
	"\n" +
	"expired_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe5\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12L\n" +
	"\x14initial_period_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x12initialPeriodStart\x12H\n" +
	"\x12initial_period_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x10initialPeriodEnd\"K\n" +
	"\x1aCreateSubscriptionResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.common.OperationMetadataR\x04data\"(\n" +
	"\x16GetSubscriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x17GetSubscriptionResponse\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.billing_service.SubscriptionR\x04data\"i\n" +
	"\x1eListSubscriptionsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x05query\x18\x02 \x01(\v2\x18.common.ListQueryRequestR\x05query\"\x90\x01\n" +
	"\x1fListSubscriptionsByUserResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.billing_service.SubscriptionR\x04data\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination\"\x91\x01\n" +
	"\x19CancelSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\"\n" +
	"\rat_period_end\x18\x02 \x01(\bR\vatPeriodEnd\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"K\n" +
	"\x1aCancelSubscriptionResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.common.OperationMetadataR\x04data*\xdf\x01\n" +
	"\x12SubscriptionStatus\x12#\n" +
	"\x1fSUBSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_ACTIVE\x10\x02\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_PAST_DUE\x10\x03\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_CANCELED\x10\x04\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATUS_EXPIRED\x10\x052\xd7\x03\n" +
	"\x13SubscriptionService\x12m\n" +
	"\x12CreateSubscription\x12*.billing_service.CreateSubscriptionRequest\x1a+.billing_service.CreateSubscriptionResponse\x12d\n" +
	"\x0fGetSubscription\x12'.billing_service.GetSubscriptionRequest\x1a(.billing_service.GetSubscriptionResponse\x12|\n" +
	"\x17ListSubscriptionsByUser\x12/.billing_service.ListSubscriptionsByUserRequest\x1a0.billing_service.ListSubscriptionsByUserResponse\x12m\n" +
	"\x12CancelSubscription\x12*.billing_service.CancelSubscriptionRequest\x1a+.billing_service.CancelSubscriptionResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_subscriptions_proto_rawDescOnce sync.Once
	file_billing_service_subscriptions_proto_rawDescData []byte
)

func file_billing_service_subscriptions_proto_rawDescGZIP() []byte {
	file_billing_service_subscriptions_proto_rawDescOnce.Do(func() {
		file_billing_service_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_subscriptions_proto_rawDesc), len(file_billing_service_subscriptions_proto_rawDesc)))
	})
	return file_billing_service_subscriptions_proto_rawDescData
}

var file_billing_service_subscriptions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_service_subscriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_billing_service_subscriptions_proto_goTypes = []any{
	(SubscriptionStatus)(0),                 // 0: billing_service.SubscriptionStatus
	(*Subscription)(nil),                    // 1: billing_service.Subscription
	(*CreateSubscriptionRequest)(nil),       // 2: billing_service.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),      // 3: billing_service.CreateSubscriptionResponse
	(*GetSubscriptionRequest)(nil),          // 4: billing_service.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),         // 5: billing_service.GetSubscriptionResponse
	(*ListSubscriptionsByUserRequest)(nil),  // 6: billing_service.ListSubscriptionsByUserRequest
	(*ListSubscriptionsByUserResponse)(nil), // 7: billing_service.ListSubscriptionsByUserResponse
	(*CancelSubscriptionRequest)(nil),       // 8: billing_service.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil),      // 9: billing_service.CancelSubscriptionResponse
	(*timestamppb.Timestamp)(nil),           // 10: google.protobuf.Timestamp
	(*common.OperationMetadata)(nil),        // 11: common.OperationMetadata
	(*common.ListQueryRequest)(nil),         // 12: common.ListQueryRequest
	(*common.PaginationMetadata)(nil),       // 13: common.PaginationMetadata
}
var file_billing_service_subscriptions_proto_depIdxs = []int32{
	0,  // 0: billing_service.Subscription.status:type_name -> billing_service.SubscriptionStatus
	10, // 1: billing_service.Subscription.current_period_start:type_name -> google.protobuf.Timestamp
	10, // 2: billing_service.Subscription.current_period_end:type_name -> google.protobuf.Timestamp
	10, // 3: billing_service.Subscription.canceled_at:type_name -> google.protobuf.Timestamp
	10, // 4: billing_service.Subscription.expired_at:type_name -> google.protobuf.Timestamp
	10, // 5: billing_service.Subscription.created_at:type_name -> google.protobuf.Timestamp
	10, // 6: billing_service.Subscription.updated_at:type_name -> google.protobuf.Timestamp
	10, // 7: billing_service.CreateSubscriptionRequest.initial_period_start:type_name -> google.protobuf.Timestamp
	10, // 8: billing_service.CreateSubscriptionRequest.initial_period_end:type_name -> google.protobuf.Timestamp
	11, // 9: billing_service.CreateSubscriptionResponse.data:type_name -> common.OperationMetadata
	1,  // 10: billing_service.GetSubscriptionResponse.data:type_name -> billing_service.Subscription
	12, // 11: billing_service.ListSubscriptionsByUserRequest.query:type_name -> common.ListQueryRequest
	1,  // 12: billing_service.ListSubscriptionsByUserResponse.data:type_name -> billing_service.Subscription
	13, // 13: billing_service.ListSubscriptionsByUserResponse.pagination:type_name -> common.PaginationMetadata
	11, // 14: billing_service.CancelSubscriptionResponse.data:type_name -> common.OperationMetadata
	2,  // 15: billing_service.SubscriptionService.CreateSubscription:input_type -> billing_service.CreateSubscriptionRequest
	4,  // 16: billing_service.SubscriptionService.GetSubscription:input_type -> billing_service.GetSubscriptionRequest
	6,  // 17: billing_service.SubscriptionService.ListSubscriptionsByUser:input_type -> billing_service.ListSubscriptionsByUserRequest
	8,  // 18: billing_service.SubscriptionService.CancelSubscription:input_type -> billing_service.CancelSubscriptionRequest
	3,  // 19: billing_service.SubscriptionService.CreateSubscription:output_type -> billing_service.CreateSubscriptionResponse
	5,  // 20: billing_service.SubscriptionService.GetSubscription:output_type -> billing_service.GetSubscriptionResponse
	7,  // 21: billing_service.SubscriptionService.ListSubscriptionsByUser:output_type -> billing_service.ListSubscriptionsByUserResponse
	9,  // 22: billing_service.SubscriptionService.CancelSubscription:output_type -> billing_service.CancelSubscriptionResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_billing_service_subscriptions_proto_init() }
func file_billing_service_subscriptions_proto_init() {
	if File_billing_service_subscriptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_subscriptions_proto_rawDesc), len(file_billing_service_subscriptions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_subscriptions_proto_goTypes,
		DependencyIndexes: file_billing_service_subscriptions_proto_depIdxs,
		EnumInfos:         file_billing_service_subscriptions_proto_enumTypes,
		MessageInfos:      file_billing_service_subscriptions_proto_msgTypes,
	}.Build()
	File_billing_service_subscriptions_proto = out.File
	file_billing_service_subscriptions_proto_goTypes = nil
	file_billing_service_subscriptions_proto_depIdxs = nil
}
