// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/subscription_events.proto

package billing_service

import (
	common "github.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mirrors the SUBSCRIPTION_EVENTS table
type SubscriptionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // UUID
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"` // FK -> subscriptions.id
	EventType      string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                // e.g. "subscription.created", "subscription.renewed", ...
	// Raw event payload (JSONB in DB)
	Payload       *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionEvent) Reset() {
	*x = SubscriptionEvent{}
	mi := &file_billing_service_subscription_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEvent) ProtoMessage() {}

func (x *SubscriptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscription_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionEvent) Descriptor() ([]byte, []int) {
	return file_billing_service_subscription_events_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscriptionEvent) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *SubscriptionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SubscriptionEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubscriptionEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetSubscriptionEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionEventRequest) Reset() {
	*x = GetSubscriptionEventRequest{}
	mi := &file_billing_service_subscription_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionEventRequest) ProtoMessage() {}

func (x *GetSubscriptionEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscription_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionEventRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionEventRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_subscription_events_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubscriptionEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSubscriptionEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SubscriptionEvent     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionEventResponse) Reset() {
	*x = GetSubscriptionEventResponse{}
	mi := &file_billing_service_subscription_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionEventResponse) ProtoMessage() {}

func (x *GetSubscriptionEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscription_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionEventResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionEventResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_subscription_events_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubscriptionEventResponse) GetData() *SubscriptionEvent {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListSubscriptionEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// Optional filter
	EventType     string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Page          int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionEventsRequest) Reset() {
	*x = ListSubscriptionEventsRequest{}
	mi := &file_billing_service_subscription_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionEventsRequest) ProtoMessage() {}

func (x *ListSubscriptionEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscription_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionEventsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionEventsRequest) Descriptor() ([]byte, []int) {
	return file_billing_service_subscription_events_proto_rawDescGZIP(), []int{3}
}

func (x *ListSubscriptionEventsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ListSubscriptionEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ListSubscriptionEventsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSubscriptionEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSubscriptionEventsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*SubscriptionEvent       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMetadata `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionEventsResponse) Reset() {
	*x = ListSubscriptionEventsResponse{}
	mi := &file_billing_service_subscription_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionEventsResponse) ProtoMessage() {}

func (x *ListSubscriptionEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_subscription_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionEventsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionEventsResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_subscription_events_proto_rawDescGZIP(), []int{4}
}

func (x *ListSubscriptionEventsResponse) GetData() []*SubscriptionEvent {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListSubscriptionEventsResponse) GetPagination() *common.PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_billing_service_subscription_events_proto protoreflect.FileDescriptor

const file_billing_service_subscription_events_proto_rawDesc = "" +
	"\n" +
	")billing_service/subscription_events.proto\x12\x0fbilling_service\x1a\x17common/pagination.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\x11SubscriptionEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"-\n" +
	"\x1bGetSubscriptionEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x1cGetSubscriptionEventResponse\x126\n" +
	"\x04data\x18\x01 \x01(\v2\".billing_service.SubscriptionEventR\x04data\"\x91\x01\n" +
	"\x1dListSubscriptionEventsRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x94\x01\n" +
	"\x1eListSubscriptionEventsResponse\x126\n" +
	"\x04data\x18\x01 \x03(\v2\".billing_service.SubscriptionEventR\x04data\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationMetadataR\n" +
	"pagination2\x8a\x02\n" +
	"\x18SubscriptionEventService\x12s\n" +
	"\x14GetSubscriptionEvent\x12,.billing_service.GetSubscriptionEventRequest\x1a-.billing_service.GetSubscriptionEventResponse\x12y\n" +
	"\x16ListSubscriptionEvents\x12..billing_service.ListSubscriptionEventsRequest\x1a/.billing_service.ListSubscriptionEventsResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_subscription_events_proto_rawDescOnce sync.Once
	file_billing_service_subscription_events_proto_rawDescData []byte
)

func file_billing_service_subscription_events_proto_rawDescGZIP() []byte {
	file_billing_service_subscription_events_proto_rawDescOnce.Do(func() {
		file_billing_service_subscription_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_subscription_events_proto_rawDesc), len(file_billing_service_subscription_events_proto_rawDesc)))
	})
	return file_billing_service_subscription_events_proto_rawDescData
}

var file_billing_service_subscription_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_billing_service_subscription_events_proto_goTypes = []any{
	(*SubscriptionEvent)(nil),              // 0: billing_service.SubscriptionEvent
	(*GetSubscriptionEventRequest)(nil),    // 1: billing_service.GetSubscriptionEventRequest
	(*GetSubscriptionEventResponse)(nil),   // 2: billing_service.GetSubscriptionEventResponse
	(*ListSubscriptionEventsRequest)(nil),  // 3: billing_service.ListSubscriptionEventsRequest
	(*ListSubscriptionEventsResponse)(nil), // 4: billing_service.ListSubscriptionEventsResponse
	(*structpb.Struct)(nil),                // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),          // 6: google.protobuf.Timestamp
	(*common.PaginationMetadata)(nil),      // 7: common.PaginationMetadata
}
var file_billing_service_subscription_events_proto_depIdxs = []int32{
	5, // 0: billing_service.SubscriptionEvent.payload:type_name -> google.protobuf.Struct
	6, // 1: billing_service.SubscriptionEvent.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: billing_service.GetSubscriptionEventResponse.data:type_name -> billing_service.SubscriptionEvent
	0, // 3: billing_service.ListSubscriptionEventsResponse.data:type_name -> billing_service.SubscriptionEvent
	7, // 4: billing_service.ListSubscriptionEventsResponse.pagination:type_name -> common.PaginationMetadata
	1, // 5: billing_service.SubscriptionEventService.GetSubscriptionEvent:input_type -> billing_service.GetSubscriptionEventRequest
	3, // 6: billing_service.SubscriptionEventService.ListSubscriptionEvents:input_type -> billing_service.ListSubscriptionEventsRequest
	2, // 7: billing_service.SubscriptionEventService.GetSubscriptionEvent:output_type -> billing_service.GetSubscriptionEventResponse
	4, // 8: billing_service.SubscriptionEventService.ListSubscriptionEvents:output_type -> billing_service.ListSubscriptionEventsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_billing_service_subscription_events_proto_init() }
func file_billing_service_subscription_events_proto_init() {
	if File_billing_service_subscription_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_subscription_events_proto_rawDesc), len(file_billing_service_subscription_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_subscription_events_proto_goTypes,
		DependencyIndexes: file_billing_service_subscription_events_proto_depIdxs,
		MessageInfos:      file_billing_service_subscription_events_proto_msgTypes,
	}.Build()
	File_billing_service_subscription_events_proto = out.File
	file_billing_service_subscription_events_proto_goTypes = nil
	file_billing_service_subscription_events_proto_depIdxs = nil
}
