// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: billing_service/webhook.proto

package billing_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZaloPayWebhookService_HandleCallback_FullMethodName = "/billing_service.ZaloPayWebhookService/HandleCallback"
)

// ZaloPayWebhookServiceClient is the client API for ZaloPayWebhookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZaloPayWebhookServiceClient interface {
	HandleCallback(ctx context.Context, in *CallbackPayload, opts ...grpc.CallOption) (*CallbackResponse, error)
}

type zaloPayWebhookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZaloPayWebhookServiceClient(cc grpc.ClientConnInterface) ZaloPayWebhookServiceClient {
	return &zaloPayWebhookServiceClient{cc}
}

func (c *zaloPayWebhookServiceClient) HandleCallback(ctx context.Context, in *CallbackPayload, opts ...grpc.CallOption) (*CallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, ZaloPayWebhookService_HandleCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZaloPayWebhookServiceServer is the server API for ZaloPayWebhookService service.
// All implementations should embed UnimplementedZaloPayWebhookServiceServer
// for forward compatibility.
type ZaloPayWebhookServiceServer interface {
	HandleCallback(context.Context, *CallbackPayload) (*CallbackResponse, error)
}

// UnimplementedZaloPayWebhookServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZaloPayWebhookServiceServer struct{}

func (UnimplementedZaloPayWebhookServiceServer) HandleCallback(context.Context, *CallbackPayload) (*CallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCallback not implemented")
}
func (UnimplementedZaloPayWebhookServiceServer) testEmbeddedByValue() {}

// UnsafeZaloPayWebhookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZaloPayWebhookServiceServer will
// result in compilation errors.
type UnsafeZaloPayWebhookServiceServer interface {
	mustEmbedUnimplementedZaloPayWebhookServiceServer()
}

func RegisterZaloPayWebhookServiceServer(s grpc.ServiceRegistrar, srv ZaloPayWebhookServiceServer) {
	// If the following call panics, it indicates UnimplementedZaloPayWebhookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZaloPayWebhookService_ServiceDesc, srv)
}

func _ZaloPayWebhookService_HandleCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZaloPayWebhookServiceServer).HandleCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZaloPayWebhookService_HandleCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZaloPayWebhookServiceServer).HandleCallback(ctx, req.(*CallbackPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// ZaloPayWebhookService_ServiceDesc is the grpc.ServiceDesc for ZaloPayWebhookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZaloPayWebhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing_service.ZaloPayWebhookService",
	HandlerType: (*ZaloPayWebhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleCallback",
			Handler:    _ZaloPayWebhookService_HandleCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_service/webhook.proto",
}
