// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: billing_service/webhook.proto

package billing_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// https://developers.zalopay.vn/v2/general/overview.html#callback_dac-ta-api_du-lieu-nhan-duoc-tu-callback
type CallbackPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Mac   string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	// 1: Order, 2: Agreement
	Type          int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackPayload) Reset() {
	*x = CallbackPayload{}
	mi := &file_billing_service_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackPayload) ProtoMessage() {}

func (x *CallbackPayload) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackPayload.ProtoReflect.Descriptor instead.
func (*CallbackPayload) Descriptor() ([]byte, []int) {
	return file_billing_service_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *CallbackPayload) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CallbackPayload) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *CallbackPayload) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CallbackData struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AppId      int32                  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppTransId string                 `protobuf:"bytes,2,opt,name=app_trans_id,json=appTransId,proto3" json:"app_trans_id,omitempty"`
	AppTime    int64                  `protobuf:"varint,3,opt,name=app_time,json=appTime,proto3" json:"app_time,omitempty"`
	Amount     int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AppUser    string                 `protobuf:"bytes,5,opt,name=app_user,json=appUser,proto3" json:"app_user,omitempty"`
	EmbedData  string                 `protobuf:"bytes,6,opt,name=embed_data,json=embedData,proto3" json:"embed_data,omitempty"`
	Item       string                 `protobuf:"bytes,7,opt,name=item,proto3" json:"item,omitempty"`
	ZpTransId  string                 `protobuf:"bytes,8,opt,name=zp_trans_id,json=zpTransId,proto3" json:"zp_trans_id,omitempty"`
	// https://developers.zalopay.vn/v2/general/overview.html#callback_dac-ta-api_cac-kenh-thanh-toan-ho-tro
	Channel        int32 `protobuf:"varint,9,opt,name=channel,proto3" json:"channel,omitempty"`
	UseFeeAmount   int64 `protobuf:"varint,10,opt,name=use_fee_amount,json=useFeeAmount,proto3" json:"use_fee_amount,omitempty"`
	DiscountAmount int64 `protobuf:"varint,11,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CallbackData) Reset() {
	*x = CallbackData{}
	mi := &file_billing_service_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackData) ProtoMessage() {}

func (x *CallbackData) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackData.ProtoReflect.Descriptor instead.
func (*CallbackData) Descriptor() ([]byte, []int) {
	return file_billing_service_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *CallbackData) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *CallbackData) GetAppTransId() string {
	if x != nil {
		return x.AppTransId
	}
	return ""
}

func (x *CallbackData) GetAppTime() int64 {
	if x != nil {
		return x.AppTime
	}
	return 0
}

func (x *CallbackData) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CallbackData) GetAppUser() string {
	if x != nil {
		return x.AppUser
	}
	return ""
}

func (x *CallbackData) GetEmbedData() string {
	if x != nil {
		return x.EmbedData
	}
	return ""
}

func (x *CallbackData) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *CallbackData) GetZpTransId() string {
	if x != nil {
		return x.ZpTransId
	}
	return ""
}

func (x *CallbackData) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *CallbackData) GetUseFeeAmount() int64 {
	if x != nil {
		return x.UseFeeAmount
	}
	return 0
}

func (x *CallbackData) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

// https://developers.zalopay.vn/v2/general/overview.html#callback_dac-ta-api_thong-tin-appserver-tra-ve-cho-zalopayserver-khi-nhan-callback
type CallbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// -1: MAC not equal
	// 0: Internal Error
	// 1: Success
	// 2: Duplicated
	ReturnCode    int32  `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	ReturnMessage string `protobuf:"bytes,2,opt,name=return_message,json=returnMessage,proto3" json:"return_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackResponse) Reset() {
	*x = CallbackResponse{}
	mi := &file_billing_service_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackResponse) ProtoMessage() {}

func (x *CallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_service_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackResponse.ProtoReflect.Descriptor instead.
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return file_billing_service_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackResponse) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *CallbackResponse) GetReturnMessage() string {
	if x != nil {
		return x.ReturnMessage
	}
	return ""
}

var File_billing_service_webhook_proto protoreflect.FileDescriptor

const file_billing_service_webhook_proto_rawDesc = "" +
	"\n" +
	"\x1dbilling_service/webhook.proto\x12\x0fbilling_service\"K\n" +
	"\x0fCallbackPayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"\xd1\x02\n" +
	"\fCallbackData\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\x05R\x05appId\x12 \n" +
	"\fapp_trans_id\x18\x02 \x01(\tR\n" +
	"appTransId\x12\x19\n" +
	"\bapp_time\x18\x03 \x01(\x03R\aappTime\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x19\n" +
	"\bapp_user\x18\x05 \x01(\tR\aappUser\x12\x1d\n" +
	"\n" +
	"embed_data\x18\x06 \x01(\tR\tembedData\x12\x12\n" +
	"\x04item\x18\a \x01(\tR\x04item\x12\x1e\n" +
	"\vzp_trans_id\x18\b \x01(\tR\tzpTransId\x12\x18\n" +
	"\achannel\x18\t \x01(\x05R\achannel\x12$\n" +
	"\x0euse_fee_amount\x18\n" +
	" \x01(\x03R\fuseFeeAmount\x12'\n" +
	"\x0fdiscount_amount\x18\v \x01(\x03R\x0ediscountAmount\"Z\n" +
	"\x10CallbackResponse\x12\x1f\n" +
	"\vreturn_code\x18\x01 \x01(\x05R\n" +
	"returnCode\x12%\n" +
	"\x0ereturn_message\x18\x02 \x01(\tR\rreturnMessage2n\n" +
	"\x15ZaloPayWebhookService\x12U\n" +
	"\x0eHandleCallback\x12 .billing_service.CallbackPayload\x1a!.billing_service.CallbackResponseB[ZYgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/billing_service;billing_serviceb\x06proto3"

var (
	file_billing_service_webhook_proto_rawDescOnce sync.Once
	file_billing_service_webhook_proto_rawDescData []byte
)

func file_billing_service_webhook_proto_rawDescGZIP() []byte {
	file_billing_service_webhook_proto_rawDescOnce.Do(func() {
		file_billing_service_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_service_webhook_proto_rawDesc), len(file_billing_service_webhook_proto_rawDesc)))
	})
	return file_billing_service_webhook_proto_rawDescData
}

var file_billing_service_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_billing_service_webhook_proto_goTypes = []any{
	(*CallbackPayload)(nil),  // 0: billing_service.CallbackPayload
	(*CallbackData)(nil),     // 1: billing_service.CallbackData
	(*CallbackResponse)(nil), // 2: billing_service.CallbackResponse
}
var file_billing_service_webhook_proto_depIdxs = []int32{
	0, // 0: billing_service.ZaloPayWebhookService.HandleCallback:input_type -> billing_service.CallbackPayload
	2, // 1: billing_service.ZaloPayWebhookService.HandleCallback:output_type -> billing_service.CallbackResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_service_webhook_proto_init() }
func file_billing_service_webhook_proto_init() {
	if File_billing_service_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_service_webhook_proto_rawDesc), len(file_billing_service_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_service_webhook_proto_goTypes,
		DependencyIndexes: file_billing_service_webhook_proto_depIdxs,
		MessageInfos:      file_billing_service_webhook_proto_msgTypes,
	}.Build()
	File_billing_service_webhook_proto = out.File
	file_billing_service_webhook_proto_goTypes = nil
	file_billing_service_webhook_proto_depIdxs = nil
}
