// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: posts.proto

package posts_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostsService_CreatePost_FullMethodName         = "/post.v1.PostsService/CreatePost"
	PostsService_UpdatePost_FullMethodName         = "/post.v1.PostsService/UpdatePost"
	PostsService_PublishPost_FullMethodName        = "/post.v1.PostsService/PublishPost"
	PostsService_UnpublishPost_FullMethodName      = "/post.v1.PostsService/UnpublishPost"
	PostsService_DeletePost_FullMethodName         = "/post.v1.PostsService/DeletePost"
	PostsService_IncrementPostViews_FullMethodName = "/post.v1.PostsService/IncrementPostViews"
	PostsService_IncrementPostLikes_FullMethodName = "/post.v1.PostsService/IncrementPostLikes"
	PostsService_GetPost_FullMethodName            = "/post.v1.PostsService/GetPost"
	PostsService_GetPostBySlug_FullMethodName      = "/post.v1.PostsService/GetPostBySlug"
	PostsService_ListPosts_FullMethodName          = "/post.v1.PostsService/ListPosts"
	PostsService_GetPostsByCategory_FullMethodName = "/post.v1.PostsService/GetPostsByCategory"
	PostsService_GetPostsByAuthor_FullMethodName   = "/post.v1.PostsService/GetPostsByAuthor"
	PostsService_GetPopularPosts_FullMethodName    = "/post.v1.PostsService/GetPopularPosts"
)

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PostCommandService handlers
type PostsServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostCommand, opts ...grpc.CallOption) (*CreatePostCommandResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostCommand, opts ...grpc.CallOption) (*UpdatePostCommandResponse, error)
	PublishPost(ctx context.Context, in *PublishPostCommand, opts ...grpc.CallOption) (*PublishPostCommandResponse, error)
	UnpublishPost(ctx context.Context, in *UnpublishPostCommand, opts ...grpc.CallOption) (*UnpublishPostCommandResponse, error)
	DeletePost(ctx context.Context, in *DeletePostCommand, opts ...grpc.CallOption) (*DeletePostCommandResponse, error)
	IncrementPostViews(ctx context.Context, in *IncrementPostViewsCommand, opts ...grpc.CallOption) (*IncrementPostViewsCommandResponse, error)
	IncrementPostLikes(ctx context.Context, in *IncrementPostLikesCommand, opts ...grpc.CallOption) (*IncrementPostLikesCommandResponse, error)
	GetPost(ctx context.Context, in *GetPostQuery, opts ...grpc.CallOption) (*GetPostQueryResponse, error)
	GetPostBySlug(ctx context.Context, in *GetPostBySlugQuery, opts ...grpc.CallOption) (*GetPostBySlugQueryResponse, error)
	ListPosts(ctx context.Context, in *ListPostsQuery, opts ...grpc.CallOption) (*ListPostsQueryResponse, error)
	GetPostsByCategory(ctx context.Context, in *GetPostsByCategoryQuery, opts ...grpc.CallOption) (*GetPostsByCategoryQueryResponse, error)
	GetPostsByAuthor(ctx context.Context, in *GetPostsByAuthorQuery, opts ...grpc.CallOption) (*GetPostsByAuthorQueryResponse, error)
	GetPopularPosts(ctx context.Context, in *GetPopularPostsQuery, opts ...grpc.CallOption) (*GetPopularPostsQueryResponse, error)
}

type postsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostsServiceClient(cc grpc.ClientConnInterface) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) CreatePost(ctx context.Context, in *CreatePostCommand, opts ...grpc.CallOption) (*CreatePostCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePostCommandResponse)
	err := c.cc.Invoke(ctx, PostsService_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UpdatePost(ctx context.Context, in *UpdatePostCommand, opts ...grpc.CallOption) (*UpdatePostCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePostCommandResponse)
	err := c.cc.Invoke(ctx, PostsService_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) PublishPost(ctx context.Context, in *PublishPostCommand, opts ...grpc.CallOption) (*PublishPostCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishPostCommandResponse)
	err := c.cc.Invoke(ctx, PostsService_PublishPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UnpublishPost(ctx context.Context, in *UnpublishPostCommand, opts ...grpc.CallOption) (*UnpublishPostCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpublishPostCommandResponse)
	err := c.cc.Invoke(ctx, PostsService_UnpublishPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) DeletePost(ctx context.Context, in *DeletePostCommand, opts ...grpc.CallOption) (*DeletePostCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePostCommandResponse)
	err := c.cc.Invoke(ctx, PostsService_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) IncrementPostViews(ctx context.Context, in *IncrementPostViewsCommand, opts ...grpc.CallOption) (*IncrementPostViewsCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementPostViewsCommandResponse)
	err := c.cc.Invoke(ctx, PostsService_IncrementPostViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) IncrementPostLikes(ctx context.Context, in *IncrementPostLikesCommand, opts ...grpc.CallOption) (*IncrementPostLikesCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementPostLikesCommandResponse)
	err := c.cc.Invoke(ctx, PostsService_IncrementPostLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPost(ctx context.Context, in *GetPostQuery, opts ...grpc.CallOption) (*GetPostQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostQueryResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPostBySlug(ctx context.Context, in *GetPostBySlugQuery, opts ...grpc.CallOption) (*GetPostBySlugQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostBySlugQueryResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPostBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) ListPosts(ctx context.Context, in *ListPostsQuery, opts ...grpc.CallOption) (*ListPostsQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPostsQueryResponse)
	err := c.cc.Invoke(ctx, PostsService_ListPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPostsByCategory(ctx context.Context, in *GetPostsByCategoryQuery, opts ...grpc.CallOption) (*GetPostsByCategoryQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostsByCategoryQueryResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPostsByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPostsByAuthor(ctx context.Context, in *GetPostsByAuthorQuery, opts ...grpc.CallOption) (*GetPostsByAuthorQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostsByAuthorQueryResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPostsByAuthor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPopularPosts(ctx context.Context, in *GetPopularPostsQuery, opts ...grpc.CallOption) (*GetPopularPostsQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularPostsQueryResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPopularPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
// All implementations should embed UnimplementedPostsServiceServer
// for forward compatibility.
//
// PostCommandService handlers
type PostsServiceServer interface {
	CreatePost(context.Context, *CreatePostCommand) (*CreatePostCommandResponse, error)
	UpdatePost(context.Context, *UpdatePostCommand) (*UpdatePostCommandResponse, error)
	PublishPost(context.Context, *PublishPostCommand) (*PublishPostCommandResponse, error)
	UnpublishPost(context.Context, *UnpublishPostCommand) (*UnpublishPostCommandResponse, error)
	DeletePost(context.Context, *DeletePostCommand) (*DeletePostCommandResponse, error)
	IncrementPostViews(context.Context, *IncrementPostViewsCommand) (*IncrementPostViewsCommandResponse, error)
	IncrementPostLikes(context.Context, *IncrementPostLikesCommand) (*IncrementPostLikesCommandResponse, error)
	GetPost(context.Context, *GetPostQuery) (*GetPostQueryResponse, error)
	GetPostBySlug(context.Context, *GetPostBySlugQuery) (*GetPostBySlugQueryResponse, error)
	ListPosts(context.Context, *ListPostsQuery) (*ListPostsQueryResponse, error)
	GetPostsByCategory(context.Context, *GetPostsByCategoryQuery) (*GetPostsByCategoryQueryResponse, error)
	GetPostsByAuthor(context.Context, *GetPostsByAuthorQuery) (*GetPostsByAuthorQueryResponse, error)
	GetPopularPosts(context.Context, *GetPopularPostsQuery) (*GetPopularPostsQueryResponse, error)
}

// UnimplementedPostsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostsServiceServer struct{}

func (UnimplementedPostsServiceServer) CreatePost(context.Context, *CreatePostCommand) (*CreatePostCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedPostsServiceServer) UpdatePost(context.Context, *UpdatePostCommand) (*UpdatePostCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedPostsServiceServer) PublishPost(context.Context, *PublishPostCommand) (*PublishPostCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishPost not implemented")
}
func (UnimplementedPostsServiceServer) UnpublishPost(context.Context, *UnpublishPostCommand) (*UnpublishPostCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpublishPost not implemented")
}
func (UnimplementedPostsServiceServer) DeletePost(context.Context, *DeletePostCommand) (*DeletePostCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedPostsServiceServer) IncrementPostViews(context.Context, *IncrementPostViewsCommand) (*IncrementPostViewsCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementPostViews not implemented")
}
func (UnimplementedPostsServiceServer) IncrementPostLikes(context.Context, *IncrementPostLikesCommand) (*IncrementPostLikesCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementPostLikes not implemented")
}
func (UnimplementedPostsServiceServer) GetPost(context.Context, *GetPostQuery) (*GetPostQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPost not implemented")
}
func (UnimplementedPostsServiceServer) GetPostBySlug(context.Context, *GetPostBySlugQuery) (*GetPostBySlugQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostBySlug not implemented")
}
func (UnimplementedPostsServiceServer) ListPosts(context.Context, *ListPostsQuery) (*ListPostsQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPosts not implemented")
}
func (UnimplementedPostsServiceServer) GetPostsByCategory(context.Context, *GetPostsByCategoryQuery) (*GetPostsByCategoryQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostsByCategory not implemented")
}
func (UnimplementedPostsServiceServer) GetPostsByAuthor(context.Context, *GetPostsByAuthorQuery) (*GetPostsByAuthorQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostsByAuthor not implemented")
}
func (UnimplementedPostsServiceServer) GetPopularPosts(context.Context, *GetPopularPostsQuery) (*GetPopularPostsQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularPosts not implemented")
}
func (UnimplementedPostsServiceServer) testEmbeddedByValue() {}

// UnsafePostsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostsServiceServer will
// result in compilation errors.
type UnsafePostsServiceServer interface {
	mustEmbedUnimplementedPostsServiceServer()
}

func RegisterPostsServiceServer(s grpc.ServiceRegistrar, srv PostsServiceServer) {
	// If the following call panics, it indicates UnimplementedPostsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostsService_ServiceDesc, srv)
}

func _PostsService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).CreatePost(ctx, req.(*CreatePostCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UpdatePost(ctx, req.(*UpdatePostCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_PublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPostCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PublishPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PublishPost(ctx, req.(*PublishPostCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UnpublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishPostCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UnpublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_UnpublishPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UnpublishPost(ctx, req.(*UnpublishPostCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).DeletePost(ctx, req.(*DeletePostCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_IncrementPostViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementPostViewsCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).IncrementPostViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_IncrementPostViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).IncrementPostViews(ctx, req.(*IncrementPostViewsCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_IncrementPostLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementPostLikesCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).IncrementPostLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_IncrementPostLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).IncrementPostLikes(ctx, req.(*IncrementPostLikesCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPost(ctx, req.(*GetPostQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPostBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostBySlugQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPostBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPostBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPostBySlug(ctx, req.(*GetPostBySlugQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_ListPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).ListPosts(ctx, req.(*ListPostsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPostsByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsByCategoryQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPostsByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPostsByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPostsByCategory(ctx, req.(*GetPostsByCategoryQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPostsByAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsByAuthorQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPostsByAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPostsByAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPostsByAuthor(ctx, req.(*GetPostsByAuthorQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPopularPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularPostsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPopularPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPopularPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPopularPosts(ctx, req.(*GetPopularPostsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// PostsService_ServiceDesc is the grpc.ServiceDesc for PostsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post.v1.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostsService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostsService_UpdatePost_Handler,
		},
		{
			MethodName: "PublishPost",
			Handler:    _PostsService_PublishPost_Handler,
		},
		{
			MethodName: "UnpublishPost",
			Handler:    _PostsService_UnpublishPost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostsService_DeletePost_Handler,
		},
		{
			MethodName: "IncrementPostViews",
			Handler:    _PostsService_IncrementPostViews_Handler,
		},
		{
			MethodName: "IncrementPostLikes",
			Handler:    _PostsService_IncrementPostLikes_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostsService_GetPost_Handler,
		},
		{
			MethodName: "GetPostBySlug",
			Handler:    _PostsService_GetPostBySlug_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _PostsService_ListPosts_Handler,
		},
		{
			MethodName: "GetPostsByCategory",
			Handler:    _PostsService_GetPostsByCategory_Handler,
		},
		{
			MethodName: "GetPostsByAuthor",
			Handler:    _PostsService_GetPostsByAuthor_Handler,
		},
		{
			MethodName: "GetPopularPosts",
			Handler:    _PostsService_GetPopularPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts.proto",
}
