// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: common/request.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Search        *string                `protobuf:"bytes,3,opt,name=search,proto3,oneof" json:"search,omitempty"`
	SortBy        *string                `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	SortOrder     *string                `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sort_order,omitempty"` // "asc" or "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueryRequest) Reset() {
	*x = ListQueryRequest{}
	mi := &file_common_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueryRequest) ProtoMessage() {}

func (x *ListQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueryRequest.ProtoReflect.Descriptor instead.
func (*ListQueryRequest) Descriptor() ([]byte, []int) {
	return file_common_request_proto_rawDescGZIP(), []int{0}
}

func (x *ListQueryRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListQueryRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListQueryRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListQueryRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *ListQueryRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

var File_common_request_proto protoreflect.FileDescriptor

const file_common_request_proto_rawDesc = "" +
	"\n" +
	"\x14common/request.proto\x12\x06common\"\xde\x01\n" +
	"\x10ListQueryRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x03 \x01(\tH\x02R\x06search\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\x04 \x01(\tH\x03R\x06sortBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tH\x04R\tsortOrder\x88\x01\x01B\a\n" +
	"\x05_pageB\b\n" +
	"\x06_limitB\t\n" +
	"\a_searchB\n" +
	"\n" +
	"\b_sort_byB\r\n" +
	"\v_sort_orderBIZGgithub.com/phanhotboy/nien-su-viet/libs/pkg/grpc/genproto/common;commonb\x06proto3"

var (
	file_common_request_proto_rawDescOnce sync.Once
	file_common_request_proto_rawDescData []byte
)

func file_common_request_proto_rawDescGZIP() []byte {
	file_common_request_proto_rawDescOnce.Do(func() {
		file_common_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_request_proto_rawDesc), len(file_common_request_proto_rawDesc)))
	})
	return file_common_request_proto_rawDescData
}

var file_common_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_request_proto_goTypes = []any{
	(*ListQueryRequest)(nil), // 0: common.ListQueryRequest
}
var file_common_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_request_proto_init() }
func file_common_request_proto_init() {
	if File_common_request_proto != nil {
		return
	}
	file_common_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_request_proto_rawDesc), len(file_common_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_request_proto_goTypes,
		DependencyIndexes: file_common_request_proto_depIdxs,
		MessageInfos:      file_common_request_proto_msgTypes,
	}.Build()
	File_common_request_proto = out.File
	file_common_request_proto_goTypes = nil
	file_common_request_proto_depIdxs = nil
}
