// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: search_service/users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "search_service";

/**
 * ============================================================
 * Common Message Types
 * ============================================================
 * User represents a user entity (minimal info for author)
 */
export interface User {
  id: string;
  email: string;
  name: string;
  avatar?: string | undefined;
}

/** GetUserByIdRequest represents a query to get a user by ID */
export interface GetUserByIdRequest {
  id: string;
}

export interface GetUserByIdResponse {
  data: User | undefined;
}

export const SEARCH_SERVICE_PACKAGE_NAME = "search_service";

/**
 * ============================================================
 * SERVICE DEFINITIONS - gRPC
 * ============================================================
 */

export interface UserServiceClient {
  getUserById(request: GetUserByIdRequest): Observable<GetUserByIdResponse>;
}

/**
 * ============================================================
 * SERVICE DEFINITIONS - gRPC
 * ============================================================
 */

export interface UserServiceController {
  getUserById(
    request: GetUserByIdRequest,
  ): Promise<GetUserByIdResponse> | Observable<GetUserByIdResponse> | GetUserByIdResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUserById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
