// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: historical_event_service/historical_events.proto

package historical_event_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoricalEventService_CreateEvent_FullMethodName     = "/historical_event_service.HistoricalEventService/CreateEvent"
	HistoricalEventService_UpdateEvent_FullMethodName     = "/historical_event_service.HistoricalEventService/UpdateEvent"
	HistoricalEventService_DeleteEvent_FullMethodName     = "/historical_event_service.HistoricalEventService/DeleteEvent"
	HistoricalEventService_GetEvent_FullMethodName        = "/historical_event_service.HistoricalEventService/GetEvent"
	HistoricalEventService_GetEventPreview_FullMethodName = "/historical_event_service.HistoricalEventService/GetEventPreview"
	HistoricalEventService_GetAllEvents_FullMethodName    = "/historical_event_service.HistoricalEventService/GetAllEvents"
)

// HistoricalEventServiceClient is the client API for HistoricalEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoricalEventServiceClient interface {
	CreateEvent(ctx context.Context, in *CreateHistoricalEventRequest, opts ...grpc.CallOption) (*CreateHistoricalEventResponse, error)
	UpdateEvent(ctx context.Context, in *UpdateHistoricalEventRequest, opts ...grpc.CallOption) (*UpdateHistoricalEventResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteHistoricalEventRequest, opts ...grpc.CallOption) (*DeleteHistoricalEventResponse, error)
	GetEvent(ctx context.Context, in *GetHistoricalEventRequest, opts ...grpc.CallOption) (*GetHistoricalEventResponse, error)
	GetEventPreview(ctx context.Context, in *GetHistoricalEventPreviewRequest, opts ...grpc.CallOption) (*GetHistoricalEventPreviewResponse, error)
	GetAllEvents(ctx context.Context, in *GetAllHistoricalEventsRequest, opts ...grpc.CallOption) (*GetAllHistoricalEventsResponse, error)
}

type historicalEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoricalEventServiceClient(cc grpc.ClientConnInterface) HistoricalEventServiceClient {
	return &historicalEventServiceClient{cc}
}

func (c *historicalEventServiceClient) CreateEvent(ctx context.Context, in *CreateHistoricalEventRequest, opts ...grpc.CallOption) (*CreateHistoricalEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHistoricalEventResponse)
	err := c.cc.Invoke(ctx, HistoricalEventService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historicalEventServiceClient) UpdateEvent(ctx context.Context, in *UpdateHistoricalEventRequest, opts ...grpc.CallOption) (*UpdateHistoricalEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHistoricalEventResponse)
	err := c.cc.Invoke(ctx, HistoricalEventService_UpdateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historicalEventServiceClient) DeleteEvent(ctx context.Context, in *DeleteHistoricalEventRequest, opts ...grpc.CallOption) (*DeleteHistoricalEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHistoricalEventResponse)
	err := c.cc.Invoke(ctx, HistoricalEventService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historicalEventServiceClient) GetEvent(ctx context.Context, in *GetHistoricalEventRequest, opts ...grpc.CallOption) (*GetHistoricalEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoricalEventResponse)
	err := c.cc.Invoke(ctx, HistoricalEventService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historicalEventServiceClient) GetEventPreview(ctx context.Context, in *GetHistoricalEventPreviewRequest, opts ...grpc.CallOption) (*GetHistoricalEventPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoricalEventPreviewResponse)
	err := c.cc.Invoke(ctx, HistoricalEventService_GetEventPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historicalEventServiceClient) GetAllEvents(ctx context.Context, in *GetAllHistoricalEventsRequest, opts ...grpc.CallOption) (*GetAllHistoricalEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllHistoricalEventsResponse)
	err := c.cc.Invoke(ctx, HistoricalEventService_GetAllEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoricalEventServiceServer is the server API for HistoricalEventService service.
// All implementations should embed UnimplementedHistoricalEventServiceServer
// for forward compatibility.
type HistoricalEventServiceServer interface {
	CreateEvent(context.Context, *CreateHistoricalEventRequest) (*CreateHistoricalEventResponse, error)
	UpdateEvent(context.Context, *UpdateHistoricalEventRequest) (*UpdateHistoricalEventResponse, error)
	DeleteEvent(context.Context, *DeleteHistoricalEventRequest) (*DeleteHistoricalEventResponse, error)
	GetEvent(context.Context, *GetHistoricalEventRequest) (*GetHistoricalEventResponse, error)
	GetEventPreview(context.Context, *GetHistoricalEventPreviewRequest) (*GetHistoricalEventPreviewResponse, error)
	GetAllEvents(context.Context, *GetAllHistoricalEventsRequest) (*GetAllHistoricalEventsResponse, error)
}

// UnimplementedHistoricalEventServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoricalEventServiceServer struct{}

func (UnimplementedHistoricalEventServiceServer) CreateEvent(context.Context, *CreateHistoricalEventRequest) (*CreateHistoricalEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedHistoricalEventServiceServer) UpdateEvent(context.Context, *UpdateHistoricalEventRequest) (*UpdateHistoricalEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedHistoricalEventServiceServer) DeleteEvent(context.Context, *DeleteHistoricalEventRequest) (*DeleteHistoricalEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedHistoricalEventServiceServer) GetEvent(context.Context, *GetHistoricalEventRequest) (*GetHistoricalEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedHistoricalEventServiceServer) GetEventPreview(context.Context, *GetHistoricalEventPreviewRequest) (*GetHistoricalEventPreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventPreview not implemented")
}
func (UnimplementedHistoricalEventServiceServer) GetAllEvents(context.Context, *GetAllHistoricalEventsRequest) (*GetAllHistoricalEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllEvents not implemented")
}
func (UnimplementedHistoricalEventServiceServer) testEmbeddedByValue() {}

// UnsafeHistoricalEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoricalEventServiceServer will
// result in compilation errors.
type UnsafeHistoricalEventServiceServer interface {
	mustEmbedUnimplementedHistoricalEventServiceServer()
}

func RegisterHistoricalEventServiceServer(s grpc.ServiceRegistrar, srv HistoricalEventServiceServer) {
	// If the following call panics, it indicates UnimplementedHistoricalEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoricalEventService_ServiceDesc, srv)
}

func _HistoricalEventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHistoricalEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalEventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalEventService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalEventServiceServer).CreateEvent(ctx, req.(*CreateHistoricalEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoricalEventService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHistoricalEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalEventServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalEventService_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalEventServiceServer).UpdateEvent(ctx, req.(*UpdateHistoricalEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoricalEventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHistoricalEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalEventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalEventService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalEventServiceServer).DeleteEvent(ctx, req.(*DeleteHistoricalEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoricalEventService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoricalEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalEventServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalEventService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalEventServiceServer).GetEvent(ctx, req.(*GetHistoricalEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoricalEventService_GetEventPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoricalEventPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalEventServiceServer).GetEventPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalEventService_GetEventPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalEventServiceServer).GetEventPreview(ctx, req.(*GetHistoricalEventPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoricalEventService_GetAllEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllHistoricalEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoricalEventServiceServer).GetAllEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoricalEventService_GetAllEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoricalEventServiceServer).GetAllEvents(ctx, req.(*GetAllHistoricalEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoricalEventService_ServiceDesc is the grpc.ServiceDesc for HistoricalEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoricalEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "historical_event_service.HistoricalEventService",
	HandlerType: (*HistoricalEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _HistoricalEventService_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _HistoricalEventService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _HistoricalEventService_DeleteEvent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _HistoricalEventService_GetEvent_Handler,
		},
		{
			MethodName: "GetEventPreview",
			Handler:    _HistoricalEventService_GetEventPreview_Handler,
		},
		{
			MethodName: "GetAllEvents",
			Handler:    _HistoricalEventService_GetAllEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "historical_event_service/historical_events.proto",
}
