package metrics

// https://github.com/riferrei/otel-with-golang/blob/main/main.go
// https://github.com/open-telemetry/opentelemetry-go/blob/main/example/prometheus/main.go
// https://opentelemetry.io/docs/instrumentation/go/manual/#metrics

import (
	"context"
	"time"

	"emperror.dev/errors"
	"github.com/phanhotboy/nien-su-viet/libs/pkg/config/environment"
	"github.com/phanhotboy/nien-su-viet/libs/pkg/config/settings"
	"github.com/phanhotboy/nien-su-viet/libs/pkg/logger"
	"github.com/samber/lo"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	"go.opentelemetry.io/otel/exporters/stdout/stdoutmetric"
	"go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
)

type OtelMetrics struct {
	serviceName string
	config      settings.MetricsOptions
	logger      logger.Logger
	appMetrics  AppMetrics
	environment environment.Environment
	provider    *metric.MeterProvider
}

// NewOtelMetrics adds otel metrics
func NewOtelMetrics(
	config settings.Config,
	logger logger.Logger,
) (*OtelMetrics, error) {
	otelMetrics := &OtelMetrics{
		serviceName: config.Server.ServiceName,
		config:      config.Metrics,
		logger:      logger,
		environment: config.Server.Env,
	}

	resource, err := otelMetrics.newResource()
	if err != nil {
		return nil, errors.WrapIf(err, "failed to create resource")
	}

	appMetrics, err := otelMetrics.initMetrics(resource)
	if err != nil {
		return nil, err
	}

	otelMetrics.appMetrics = appMetrics

	return otelMetrics, nil
}

func (o *OtelMetrics) Shutdown(ctx context.Context) error {
	return o.provider.Shutdown(ctx)
}

func (o *OtelMetrics) newResource() (*resource.Resource, error) {
	// https://github.com/uptrace/uptrace-go/blob/master/example/otlp-traces/main.go#L49C1-L56C5
	resource, err := resource.New(
		context.Background(),
		resource.WithFromEnv(),
		resource.WithTelemetrySDK(),
		resource.WithHost(),
		resource.WithOS(),
		resource.WithSchemaURL(semconv.SchemaURL),
		resource.WithAttributes(
			semconv.ServiceName(o.serviceName),
			semconv.ServiceVersion(o.config.Version),
			attribute.String("environment", o.environment.GetEnvironmentName()),
			semconv.TelemetrySDKVersionKey.String("v1.40.0"), // semconv version
			semconv.TelemetrySDKLanguageGo,
		))

	return resource, err
}

func (o *OtelMetrics) initMetrics(
	resource *resource.Resource,
) (AppMetrics, error) {
	metricsExporter, err := o.configExporters()
	if err != nil {
		return nil, err
	}

	batchExporters := lo.Map(
		metricsExporter,
		func(item metric.Reader, index int) metric.Option {
			return metric.WithReader(item)
		},
	)

	// https://opentelemetry.io/docs/instrumentation/go/exporting_data/#resources
	// Resources are a special type of attribute that apply to all spans generated by a process
	opts := append(
		batchExporters,
		metric.WithResource(resource),
	)

	// otel library collects metrics and send this metrics to some exporter like console or prometheus
	provider := metric.NewMeterProvider(opts...)

	// Register our MeterProvider as the global so any imported
	// instrumentation in the future will default to using it.
	otel.SetMeterProvider(provider)
	o.provider = provider

	appMeter := NewAppMeter(o.config.InstrumentationName)

	return appMeter, nil
}

func (o *OtelMetrics) configExporters() ([]metric.Reader, error) {
	ctx := context.Background()

	var exporters []metric.Reader

	// use some otel collector endpoints
	metricOpts := []otlpmetricgrpc.Option{
		otlpmetricgrpc.WithTimeout(5 * time.Second),
		otlpmetricgrpc.WithInsecure(),
	}

	if !o.config.UseOTLP { //nolint:nestif
		if o.config.UseStdout {
			console, err := stdoutmetric.New()
			if err != nil {
				return nil, errors.WrapIf(
					err,
					"error creating console exporter",
				)
			}

			consoleMetricExporter := metric.NewPeriodicReader(
				console,
				// Default is 1m. Set to 3s for demonstrative purposes.
				metric.WithInterval(3*time.Second))

			exporters = append(exporters, consoleMetricExporter)
			o.logger.Warn("otel collector exporter is disabled, no metrics will be sent to otel collector")
		}
	} else {
		if o.config.OtelCollectorOptions.Enabled {
			metricOpts = append(
				metricOpts,
				otlpmetricgrpc.WithEndpoint(
					o.config.OtelCollectorOptions.OTLPEndpoint,
				),
			)

			o.logger.Infof(
				"otel collector exporter is enabled, metrics will be sent to otel collector endpoint: %s",
				o.config.OtelCollectorOptions.OTLPEndpoint,
			)
			// send otel traces to otel collector endpoint
			// https://opentelemetry.io/docs/collector/
			exporter, err := otlpmetricgrpc.New(ctx, metricOpts...)
			if err != nil {
				return nil, errors.WrapIf(
					err,
					"failed to create otlpmetric exporter for otel collector",
				)
			}

			otelCollectorExporter := metric.NewPeriodicReader(
				exporter,
				// Default is 1m. Set to 3s for demonstrative purposes.
				metric.WithInterval(3*time.Second),
			)

			exporters = append(exporters, otelCollectorExporter)
		}
	}

	return exporters, nil
}
