// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: events/billing_event.proto

/* eslint-disable */
import { wrappers } from "protobufjs";
import { Money } from "../billing_service/billing";
import { PaymentAttemptStatus } from "../billing_service/payment_attempts";
import { PaymentTransactionStatus, PaymentTransactionType } from "../billing_service/payment_transactions";
import { PurchaseStatus } from "../billing_service/purchases";
import { SubscriptionStatus } from "../billing_service/subscriptions";
import { Struct } from "../google/protobuf/struct";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "events";

export interface SubscriptionSnapshot {
  subscriptionId: string;
  userId: string;
  planId: string;
  status: SubscriptionStatus;
  currentPeriodStart: Timestamp | undefined;
  currentPeriodEnd: Timestamp | undefined;
  cancelAtPeriodEnd: boolean;
  canceledAt: Timestamp | undefined;
  expiredAt: Timestamp | undefined;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}

export interface SubscriptionCreated {
  subscriptionId: string;
  userId: string;
  planId: string;
  status: SubscriptionStatus;
  currentPeriodStart: Timestamp | undefined;
  currentPeriodEnd: Timestamp | undefined;
  cancelAtPeriodEnd: boolean;
  canceledAt: Timestamp | undefined;
  expiredAt: Timestamp | undefined;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}

export interface SubscriptionUpdated {
  before: SubscriptionSnapshot | undefined;
  after:
    | SubscriptionSnapshot
    | undefined;
  /** Optional: what triggered this (webhook, admin, scheduler, etc.) */
  cause: string;
}

export interface SubscriptionCanceled {
  subscriptionId: string;
  userId: string;
  atPeriodEnd: boolean;
  canceledAt: Timestamp | undefined;
  cause: string;
}

export interface SubscriptionExpired {
  subscriptionId: string;
  userId: string;
  expiredAt: Timestamp | undefined;
  cause: string;
}

export interface PurchaseSnapshot {
  purchaseId: string;
  userId: string;
  subscriptionId: string;
  planId: string;
  amount: Money | undefined;
  status: PurchaseStatus;
  idempotencyKey: string;
  createdAt: Timestamp | undefined;
  completedAt: Timestamp | undefined;
}

export interface PurchaseCreated {
  purchase: PurchaseSnapshot | undefined;
}

export interface PurchaseCompleted {
  purchase:
    | PurchaseSnapshot
    | undefined;
  /** Helpful pointers for downstream consumers */
  successfulPaymentAttemptId: string;
  /** your internal PaymentTransaction id (if you create it) */
  captureTransactionId: string;
  /** "stripe", "momo", ... */
  provider: string;
  /** provider's charge/payment reference */
  providerReference: string;
}

export interface PurchaseFailed {
  purchase:
    | PurchaseSnapshot
    | undefined;
  /** Optional failure info (avoid leaking secrets) */
  provider: string;
  providerReference: string;
  /** normalized reason, if available */
  failureReason: string;
}

export interface PurchaseCanceled {
  purchase: PurchaseSnapshot | undefined;
  cause: string;
}

export interface PaymentAttemptSnapshot {
  paymentAttemptId: string;
  purchaseId: string;
  provider: string;
  status: PaymentAttemptStatus;
  amount: Money | undefined;
  providerTransactionId: string;
  checkoutUrl: string;
  expiresAt: Timestamp | undefined;
  createdAt: Timestamp | undefined;
  updatedAt: Timestamp | undefined;
}

export interface PaymentAttemptCreated {
  paymentAttempt: PaymentAttemptSnapshot | undefined;
}

export interface PaymentAttemptUpdated {
  before: PaymentAttemptSnapshot | undefined;
  after: PaymentAttemptSnapshot | undefined;
}

export interface PaymentAttemptSucceeded {
  paymentAttempt:
    | PaymentAttemptSnapshot
    | undefined;
  /** Optional pointer to the capture/payment transaction recorded */
  transactionId: string;
  providerReference: string;
}

export interface PaymentAttemptFailed {
  paymentAttempt: PaymentAttemptSnapshot | undefined;
  failureReason: string;
  /** e.g. error codes from provider */
  providerError: { [key: string]: any } | undefined;
}

export interface PaymentAttemptExpired {
  paymentAttempt: PaymentAttemptSnapshot | undefined;
}

export interface PaymentTransactionSnapshot {
  transactionId: string;
  paymentAttemptId: string;
  type: PaymentTransactionType;
  status: PaymentTransactionStatus;
  amount: Money | undefined;
  providerReference: string;
  processedAt: Timestamp | undefined;
  createdAt:
    | Timestamp
    | undefined;
  /** Keep arbitrary metadata minimal; include if consumers need it. */
  metadata: { [key: string]: any } | undefined;
}

export interface PaymentTransactionRecorded {
  transaction:
    | PaymentTransactionSnapshot
    | undefined;
  /** Optional: link refund -> capture, etc. (if you add related_transaction_id in DB) */
  relatedTransactionId: string;
}

export interface RefundRequested {
  /** your internal idempotent request id (could reuse event_id) */
  refundRequestId: string;
  purchaseId: string;
  /** The payment attempt/transaction you intend to refund */
  paymentAttemptId: string;
  captureTransactionId: string;
  amount: Money | undefined;
  reason: string;
  /** For convenience */
  provider: string;
  idempotencyKey: string;
  requestedAt: Timestamp | undefined;
}

export interface RefundSucceeded {
  purchaseId: string;
  paymentAttemptId: string;
  captureTransactionId: string;
  /** your internal PaymentTransaction id */
  refundTransactionId: string;
  amount: Money | undefined;
  provider: string;
  /** provider refund id */
  providerReference: string;
  succeededAt: Timestamp | undefined;
}

export interface RefundFailed {
  purchaseId: string;
  paymentAttemptId: string;
  amount: Money | undefined;
  provider: string;
  failureReason: string;
  providerError: { [key: string]: any } | undefined;
  failedAt: Timestamp | undefined;
}

export interface WebhookEventReceived {
  provider: string;
  externalEventId: string;
  eventType: string;
  receivedAt: Timestamp | undefined;
}

export interface WebhookEventProcessed {
  provider: string;
  externalEventId: string;
  eventType: string;
  processedAt:
    | Timestamp
    | undefined;
  /** Optional: what this webhook caused (helpful for observability) */
  emittedEventIds: string[];
}

export interface WebhookEventProcessingFailed {
  provider: string;
  externalEventId: string;
  eventType: string;
  errorMessage: string;
  failedAt: Timestamp | undefined;
}

export const EVENTS_PACKAGE_NAME = "events";

wrappers[".google.protobuf.Struct"] = { fromObject: Struct.wrap, toObject: Struct.unwrap } as any;
