// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: events/historical_event_events.proto

/* eslint-disable */

export const protobufPackage = "events";

export interface HistoricalEventCreatedEvent {
  id: string;
  authorId: string;
  name: string;
  thumbnail?: string | undefined;
  fromDateType: string;
  fromDay?: number | undefined;
  fromMonth?: number | undefined;
  fromYear: number;
  toDateType?: string | undefined;
  toDay?: number | undefined;
  toMonth?: number | undefined;
  toYear?: number | undefined;
  content: string;
  createdAt: string;
  updatedAt: string;
}

export interface HistoricalEventUpdatedEvent {
  id: string;
  name?: string | undefined;
  thumbnail?: string | undefined;
  fromDateType?: string | undefined;
  fromDay?: number | undefined;
  fromMonth?: number | undefined;
  fromYear?: number | undefined;
  toDateType?: string | undefined;
  toDay?: number | undefined;
  toMonth?: number | undefined;
  toYear?: number | undefined;
  content?: string | undefined;
  updatedAt?: string | undefined;
}

export interface HistoricalEventDeletedEvent {
  id: string;
  authorId: string;
}

export const EVENTS_PACKAGE_NAME = "events";
