// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: events/post_events.proto

/* eslint-disable */

export const protobufPackage = "events";

/** PostCreatedEventRequest represents an event when a post is created */
export interface PostCreatedEvent {
  id: string;
  title: string;
  slug: string;
  content: string;
  summary?: string | undefined;
  thumbnail?: string | undefined;
  authorId: string;
  categoryId?: string | undefined;
  views: number;
  likes: number;
  published: boolean;
  publishedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

/** PostUpdatedEvent represents an event when a post is updated */
export interface PostUpdatedEvent {
  id: string;
  title?: string | undefined;
  slug?: string | undefined;
  content?: string | undefined;
  summary?: string | undefined;
  thumbnail?: string | undefined;
  authorId?: string | undefined;
  categoryId?: string | undefined;
  views?: number | undefined;
  likes?: number | undefined;
  published?: boolean | undefined;
  publishedAt?: string | undefined;
  updatedAt?: string | undefined;
}

/** PostPublishedEvent represents an event when a post is published */
export interface PostPublishedEvent {
  id: string;
  publishedAt: string;
}

/** PostUnpublishedEvent represents an event when a post is unpublished */
export interface PostUnpublishedEvent {
  id: string;
}

/** PostDeletedEvent represents an event when a post is deleted */
export interface PostDeletedEvent {
  id: string;
}

/** PostViewsIncrementedEvent represents an event when post views are incremented */
export interface PostViewsIncrementedEvent {
  id: string;
  views: number;
}

/** PostLikesIncrementedEvent represents an event when post likes are incremented */
export interface PostLikesIncrementedEvent {
  id: string;
  likes: number;
}

export const EVENTS_PACKAGE_NAME = "events";
