// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: post_service/posts.proto

package posts_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostsService_CreatePost_FullMethodName         = "/post_service.PostsService/CreatePost"
	PostsService_UpdatePost_FullMethodName         = "/post_service.PostsService/UpdatePost"
	PostsService_PublishPost_FullMethodName        = "/post_service.PostsService/PublishPost"
	PostsService_UnpublishPost_FullMethodName      = "/post_service.PostsService/UnpublishPost"
	PostsService_DeletePost_FullMethodName         = "/post_service.PostsService/DeletePost"
	PostsService_DeletePosts_FullMethodName        = "/post_service.PostsService/DeletePosts"
	PostsService_IncrementPostViews_FullMethodName = "/post_service.PostsService/IncrementPostViews"
	PostsService_IncrementPostLikes_FullMethodName = "/post_service.PostsService/IncrementPostLikes"
	PostsService_GetPost_FullMethodName            = "/post_service.PostsService/GetPost"
	PostsService_GetPublishedPosts_FullMethodName  = "/post_service.PostsService/GetPublishedPosts"
	PostsService_GetAllPosts_FullMethodName        = "/post_service.PostsService/GetAllPosts"
	PostsService_GetPostsByCategory_FullMethodName = "/post_service.PostsService/GetPostsByCategory"
	PostsService_GetPostsByAuthor_FullMethodName   = "/post_service.PostsService/GetPostsByAuthor"
	PostsService_GetPopularPosts_FullMethodName    = "/post_service.PostsService/GetPopularPosts"
)

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PostsService handlers
type PostsServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	PublishPost(ctx context.Context, in *PublishPostRequest, opts ...grpc.CallOption) (*PublishPostResponse, error)
	UnpublishPost(ctx context.Context, in *UnpublishPostRequest, opts ...grpc.CallOption) (*UnpublishPostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
	DeletePosts(ctx context.Context, in *DeletePostsRequest, opts ...grpc.CallOption) (*DeletePostsResponse, error)
	IncrementPostViews(ctx context.Context, in *IncrementPostViewsRequest, opts ...grpc.CallOption) (*IncrementPostViewsResponse, error)
	IncrementPostLikes(ctx context.Context, in *IncrementPostLikesRequest, opts ...grpc.CallOption) (*IncrementPostLikesResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
	GetPublishedPosts(ctx context.Context, in *GetPublishedPostsRequest, opts ...grpc.CallOption) (*GetPublishedPostsResponse, error)
	GetAllPosts(ctx context.Context, in *GetAllPostsRequest, opts ...grpc.CallOption) (*GetAllPostsResponse, error)
	GetPostsByCategory(ctx context.Context, in *GetPostsByCategoryRequest, opts ...grpc.CallOption) (*GetPostsByCategoryResponse, error)
	GetPostsByAuthor(ctx context.Context, in *GetPostsByAuthorRequest, opts ...grpc.CallOption) (*GetPostsByAuthorResponse, error)
	GetPopularPosts(ctx context.Context, in *GetPopularPostsRequest, opts ...grpc.CallOption) (*GetPopularPostsResponse, error)
}

type postsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostsServiceClient(cc grpc.ClientConnInterface) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, PostsService_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, PostsService_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) PublishPost(ctx context.Context, in *PublishPostRequest, opts ...grpc.CallOption) (*PublishPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishPostResponse)
	err := c.cc.Invoke(ctx, PostsService_PublishPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UnpublishPost(ctx context.Context, in *UnpublishPostRequest, opts ...grpc.CallOption) (*UnpublishPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpublishPostResponse)
	err := c.cc.Invoke(ctx, PostsService_UnpublishPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, PostsService_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) DeletePosts(ctx context.Context, in *DeletePostsRequest, opts ...grpc.CallOption) (*DeletePostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePostsResponse)
	err := c.cc.Invoke(ctx, PostsService_DeletePosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) IncrementPostViews(ctx context.Context, in *IncrementPostViewsRequest, opts ...grpc.CallOption) (*IncrementPostViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementPostViewsResponse)
	err := c.cc.Invoke(ctx, PostsService_IncrementPostViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) IncrementPostLikes(ctx context.Context, in *IncrementPostLikesRequest, opts ...grpc.CallOption) (*IncrementPostLikesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementPostLikesResponse)
	err := c.cc.Invoke(ctx, PostsService_IncrementPostLikes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPublishedPosts(ctx context.Context, in *GetPublishedPostsRequest, opts ...grpc.CallOption) (*GetPublishedPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublishedPostsResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPublishedPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetAllPosts(ctx context.Context, in *GetAllPostsRequest, opts ...grpc.CallOption) (*GetAllPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPostsResponse)
	err := c.cc.Invoke(ctx, PostsService_GetAllPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPostsByCategory(ctx context.Context, in *GetPostsByCategoryRequest, opts ...grpc.CallOption) (*GetPostsByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostsByCategoryResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPostsByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPostsByAuthor(ctx context.Context, in *GetPostsByAuthorRequest, opts ...grpc.CallOption) (*GetPostsByAuthorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPostsByAuthorResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPostsByAuthor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPopularPosts(ctx context.Context, in *GetPopularPostsRequest, opts ...grpc.CallOption) (*GetPopularPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularPostsResponse)
	err := c.cc.Invoke(ctx, PostsService_GetPopularPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
// All implementations should embed UnimplementedPostsServiceServer
// for forward compatibility.
//
// PostsService handlers
type PostsServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	PublishPost(context.Context, *PublishPostRequest) (*PublishPostResponse, error)
	UnpublishPost(context.Context, *UnpublishPostRequest) (*UnpublishPostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
	DeletePosts(context.Context, *DeletePostsRequest) (*DeletePostsResponse, error)
	IncrementPostViews(context.Context, *IncrementPostViewsRequest) (*IncrementPostViewsResponse, error)
	IncrementPostLikes(context.Context, *IncrementPostLikesRequest) (*IncrementPostLikesResponse, error)
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
	GetPublishedPosts(context.Context, *GetPublishedPostsRequest) (*GetPublishedPostsResponse, error)
	GetAllPosts(context.Context, *GetAllPostsRequest) (*GetAllPostsResponse, error)
	GetPostsByCategory(context.Context, *GetPostsByCategoryRequest) (*GetPostsByCategoryResponse, error)
	GetPostsByAuthor(context.Context, *GetPostsByAuthorRequest) (*GetPostsByAuthorResponse, error)
	GetPopularPosts(context.Context, *GetPopularPostsRequest) (*GetPopularPostsResponse, error)
}

// UnimplementedPostsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostsServiceServer struct{}

func (UnimplementedPostsServiceServer) CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedPostsServiceServer) UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedPostsServiceServer) PublishPost(context.Context, *PublishPostRequest) (*PublishPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishPost not implemented")
}
func (UnimplementedPostsServiceServer) UnpublishPost(context.Context, *UnpublishPostRequest) (*UnpublishPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpublishPost not implemented")
}
func (UnimplementedPostsServiceServer) DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedPostsServiceServer) DeletePosts(context.Context, *DeletePostsRequest) (*DeletePostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePosts not implemented")
}
func (UnimplementedPostsServiceServer) IncrementPostViews(context.Context, *IncrementPostViewsRequest) (*IncrementPostViewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementPostViews not implemented")
}
func (UnimplementedPostsServiceServer) IncrementPostLikes(context.Context, *IncrementPostLikesRequest) (*IncrementPostLikesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementPostLikes not implemented")
}
func (UnimplementedPostsServiceServer) GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPost not implemented")
}
func (UnimplementedPostsServiceServer) GetPublishedPosts(context.Context, *GetPublishedPostsRequest) (*GetPublishedPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublishedPosts not implemented")
}
func (UnimplementedPostsServiceServer) GetAllPosts(context.Context, *GetAllPostsRequest) (*GetAllPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllPosts not implemented")
}
func (UnimplementedPostsServiceServer) GetPostsByCategory(context.Context, *GetPostsByCategoryRequest) (*GetPostsByCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostsByCategory not implemented")
}
func (UnimplementedPostsServiceServer) GetPostsByAuthor(context.Context, *GetPostsByAuthorRequest) (*GetPostsByAuthorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostsByAuthor not implemented")
}
func (UnimplementedPostsServiceServer) GetPopularPosts(context.Context, *GetPopularPostsRequest) (*GetPopularPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularPosts not implemented")
}
func (UnimplementedPostsServiceServer) testEmbeddedByValue() {}

// UnsafePostsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostsServiceServer will
// result in compilation errors.
type UnsafePostsServiceServer interface {
	mustEmbedUnimplementedPostsServiceServer()
}

func RegisterPostsServiceServer(s grpc.ServiceRegistrar, srv PostsServiceServer) {
	// If the following call panics, it indicates UnimplementedPostsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostsService_ServiceDesc, srv)
}

func _PostsService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_PublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).PublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_PublishPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).PublishPost(ctx, req.(*PublishPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UnpublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UnpublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_UnpublishPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UnpublishPost(ctx, req.(*UnpublishPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_DeletePosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).DeletePosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_DeletePosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).DeletePosts(ctx, req.(*DeletePostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_IncrementPostViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementPostViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).IncrementPostViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_IncrementPostViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).IncrementPostViews(ctx, req.(*IncrementPostViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_IncrementPostLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementPostLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).IncrementPostLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_IncrementPostLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).IncrementPostLikes(ctx, req.(*IncrementPostLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPublishedPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishedPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPublishedPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPublishedPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPublishedPosts(ctx, req.(*GetPublishedPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetAllPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetAllPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetAllPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetAllPosts(ctx, req.(*GetAllPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPostsByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPostsByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPostsByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPostsByCategory(ctx, req.(*GetPostsByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPostsByAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsByAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPostsByAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPostsByAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPostsByAuthor(ctx, req.(*GetPostsByAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPopularPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPopularPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostsService_GetPopularPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPopularPosts(ctx, req.(*GetPopularPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostsService_ServiceDesc is the grpc.ServiceDesc for PostsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post_service.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostsService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostsService_UpdatePost_Handler,
		},
		{
			MethodName: "PublishPost",
			Handler:    _PostsService_PublishPost_Handler,
		},
		{
			MethodName: "UnpublishPost",
			Handler:    _PostsService_UnpublishPost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostsService_DeletePost_Handler,
		},
		{
			MethodName: "DeletePosts",
			Handler:    _PostsService_DeletePosts_Handler,
		},
		{
			MethodName: "IncrementPostViews",
			Handler:    _PostsService_IncrementPostViews_Handler,
		},
		{
			MethodName: "IncrementPostLikes",
			Handler:    _PostsService_IncrementPostLikes_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostsService_GetPost_Handler,
		},
		{
			MethodName: "GetPublishedPosts",
			Handler:    _PostsService_GetPublishedPosts_Handler,
		},
		{
			MethodName: "GetAllPosts",
			Handler:    _PostsService_GetAllPosts_Handler,
		},
		{
			MethodName: "GetPostsByCategory",
			Handler:    _PostsService_GetPostsByCategory_Handler,
		},
		{
			MethodName: "GetPostsByAuthor",
			Handler:    _PostsService_GetPostsByAuthor_Handler,
		},
		{
			MethodName: "GetPopularPosts",
			Handler:    _PostsService_GetPopularPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post_service/posts.proto",
}
