package tracing

import (
	"context"
	"os"
	"time"

	"emperror.dev/errors"
	"github.com/phanhotboy/nien-su-viet/libs/pkg/config/environment"
	"github.com/phanhotboy/nien-su-viet/libs/pkg/config/settings"
	"github.com/phanhotboy/nien-su-viet/libs/pkg/logger"
	"github.com/samber/lo"
	"go.opentelemetry.io/contrib/propagators/ot"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/exporters/stdout/stdouttrace"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	tracesdk "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
)

type TracingOpenTelemetry struct {
	serviceName string
	version     string
	config      settings.TracingOptions
	environment environment.Environment
	appTracer   AppTracer
	provider    *tracesdk.TracerProvider
}

// Create one tracer per package
// NOTE: You only need a tracer if you are creating your own spans

func NewOtelTracing(
	cfg settings.Config,
	l logger.Logger,
) (*TracingOpenTelemetry, error) {
	otelTracing := &TracingOpenTelemetry{
		serviceName: cfg.Server.ServiceName,
		version:     cfg.Server.Version,
		config:      cfg.Tracing,
		environment: cfg.Server.Env,
	}

	resource, err := otelTracing.newResource()
	if err != nil {
		return nil, errors.WrapIf(err, "failed to create resource")
	}

	appTracer, err := otelTracing.initTracer(resource)
	if err != nil {
		return nil, err
	}

	otelTracing.appTracer = appTracer

	return otelTracing, nil
}

func (o *TracingOpenTelemetry) Shutdown(ctx context.Context) error {
	return o.provider.Shutdown(ctx)
}

func (o *TracingOpenTelemetry) newResource() (*resource.Resource, error) {
	// https://github.com/uptrace/uptrace-go/blob/master/example/otlp-traces/main.go#L49C1-L56C5
	resource, err := resource.New(context.Background(),
		resource.WithFromEnv(),
		resource.WithTelemetrySDK(),
		resource.WithHost(),
		resource.WithOS(),
		resource.WithSchemaURL(semconv.SchemaURL),
		resource.WithAttributes(
			semconv.ServiceName(o.serviceName),
			semconv.ServiceVersion(o.version),
			attribute.String("environment", o.environment.GetEnvironmentName()),
			semconv.TelemetrySDKVersionKey.String("v1.40.0"), // semconv version
			semconv.TelemetrySDKLanguageGo,
		))

	return resource, err
}

func (o *TracingOpenTelemetry) initTracer(
	resource *resource.Resource,
) (AppTracer, error) {
	exporters, err := o.configExporters()
	if err != nil {
		return nil, err
	}

	var sampler tracesdk.Sampler
	if o.config.AlwaysOnSampler {
		sampler = tracesdk.AlwaysSample()
	} else {
		sampler = tracesdk.NeverSample()
	}

	batchExporters := lo.Map(
		exporters,
		func(item tracesdk.SpanExporter, index int) tracesdk.TracerProviderOption {
			return tracesdk.WithBatcher(item)
		},
	)

	// https://opentelemetry.io/docs/instrumentation/go/exporting_data/#resources
	// Resources are a special type of attribute that apply to all spans generated by a process
	opts := append(
		batchExporters,
		tracesdk.WithResource(resource),
		tracesdk.WithSampler(sampler),
	)

	provider := tracesdk.NewTracerProvider(opts...)

	// Register our tracerProvider as the global so any imported
	// instrumentation in the future will default to using it.
	otel.SetTracerProvider(provider)
	o.provider = provider

	// https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/ot/ot_propagator.go
	// https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/trace_context.go
	// https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/baggage.go/
	// https://trstringer.com/otel-part5-propagation/
	otel.SetTextMapPropagator(
		propagation.NewCompositeTextMapPropagator(
			ot.OT{}, // should be placed before `TraceContext` for preventing conflict
			propagation.Baggage{},
			propagation.TraceContext{},
		),
	)

	// https://trstringer.com/otel-part2-instrumentation/
	// Finally, set the tracer that can be used for this package. global app tracer
	appTracer := NewAppTracer(o.config.InstrumentationName)

	return appTracer, nil
}

func (o *TracingOpenTelemetry) configExporters() ([]tracesdk.SpanExporter, error) {
	ctx := context.Background()
	traceOpts := []otlptracegrpc.Option{
		otlptracegrpc.WithTimeout(5 * time.Second),
		otlptracegrpc.WithInsecure(),
	}

	var exporters []tracesdk.SpanExporter

	if o.config.UseStdout {
		stdExporter, err := stdouttrace.New(
			stdouttrace.WithWriter(
				os.Stdout,
			), // stdExporter default is `stdouttrace.WithWriter(os.Stdout)`, we can remove this also
			stdouttrace.WithPrettyPrint(), // make output json with pretty printing
		)
		if err != nil {
			return nil, errors.WrapIf(err, "creating stdout exporter")
		}

		exporters = append(exporters, stdExporter)
	}
	if o.config.UseOTLP {

		traceOpts = append(traceOpts, otlptracegrpc.WithEndpoint(o.config.OtlpProvider.OTLPEndpoint))

		// send otel metrics to an otel collector endpoint (default grpc port: 4317)
		// https://opentelemetry.io/docs/collector/
		// https://github.com/uptrace/uptrace-go/blob/master/example/otlp-traces/main.go#L29
		// https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracehttp/example_test.go#L70
		traceExporter, err := otlptracegrpc.New(ctx, traceOpts...)
		if err != nil {
			return nil, errors.WrapIf(err, "failed to create otlptracegrpc exporter")
		}

		exporters = append(exporters, traceExporter)
	}

	return exporters, nil
}
